### ISSUE TITLE
Scanning is not Accurate

### ISSUE THREAD

**Issue by MohsinQK** [mebjas/html5-qrcode#100]
Scanning the same bar code multiple times gives different values.

Tested in Android 10 Chrome
![WhatsApp Image 2020-08-13 at 4 14 47 AM (1)](https://user-images.githubusercontent.com/1622975/90077780-729dfa00-dd1c-11ea-8f74-d88772e59815.jpeg)

**Comment by max2ti** [comment]
see https://github.com/mebjas/html5-qrcode/issues/63

**Comment by mebjas** [comment]
Closing this issue here - will follow up on this problem at #63
