### ISSUE TITLE
Not able to scan the code. 

### ISSUE THREAD

**Issue by agrawalk9** [mebjas/html5-qrcode#109]
Always getting the error "QR Code no longer in front of camera. QR code parse error, error = Couldn't find enough finder patterns (found 0)"
My code - 
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="./html5-qrcode.js"></script>
</head>

<body>
    <div id="reader" width="600px"></div>

    

    <script>
        const video = document.getElementById('reader');

        const constraints = {
            facingMode: 'user'
        };

        const html5QrCode = new Html5Qrcode("reader");

        html5QrCode.start(
                constraints, // retreived in the previous step.
                {
                    fps: 0, // sets the framerate to 10 frame per second
                    qrbox: 250, // sets only 250 X 250 region of viewfinder to
                    // scannable, rest shaded.
                    // aspectRatio: 1.333,
                    // // .. let's say in beta configs below
                    // videoConstraints: {
                    //     aspectRatio: 1.77778 // <-- this would be honoured 
                    // }
                },
                qrCodeMessage => {
                    // do something when code is read. For example:
                    console.log(`QR Code detected: ${qrCodeMessage}`);
                },
                errorMessage => {
                    // parse error, ideally ignore it. For example:
                    console.log(`QR Code no longer in front of camera.`, errorMessage);
                })
            .catch(err => {
                // Start failed, handle it. For example,
                console.log(`Unable to start scanning, error: ${err}`);
            });

    </script>
</body>

</html>

**Comment by mebjas** [comment]
@agrawalk9

Thanks for filing the bug. Can you share more details on the environment i.e. the browser and the OS (+ version) you are testing this on?

Your code looks correct, except for setting `fps: 0,` (why?), but I assume this shouldn't be the root cause of the issue you are seeing. It'd also be good to post a sample QR code that you are testing on in case the error comes from there.

**Comment by mebjas** [comment]
Closing due to lack of response. @agrawalk9 - please feel free to reopen if this issue persists.
