### ISSUE TITLE
Request camera permission failed

### ISSUE THREAD

**Issue by vfa-loinh** [mebjas/html5-qrcode#115]
**Describe the bug**
Run with Line internal browser an error occurred when request camera permission

**To Reproduce**
1. Open link in Line App 
   - https://blog.minhazav.dev/research/html5-qrcode.html
2. Click on Request Camera Permission
3. See error

**Expected behavior**
Can request camera permission

**Screenshots**
https://ibb.co/LRYCJ63

**Smartphone (please complete the following information):**
 - Device: [e.g. Samsung A51]
 - OS: [e.g. Android 10]

**Additional context**

**Comment by dom2049** [comment]
I have the same issue as you. Posted before you. On one test address it asks for permission as it should, on the other I get the same error as you. On a desktop or mobile phone. It's been days now and I can't figure it out and no one is replying here.

**Comment by dom2049** [comment]
I have a feeling it could be about exotic domain name extensions? yours is .dev, mine is .app? .net is working.

**Comment by LoiNH** [comment]
> I have the same issue as you. Posted before you. On one test address it asks for permission as it should, on the other I get the same error as you. On a desktop or mobile phone. It's been days now and I can't figure it out and no one is replying here.

Thank for your answer, I'm also finding another solution.

**Comment by dom2049** [comment]
I found that my problem lies with the feature-policy response header and fixed the problem by setting the web.config of the site to what's below. Notice the "camera *" part... It was camera 'none' before for me.

<httpProtocol>
      <customHeaders>
        
        <add name="Feature-Policy" value="accelerometer 'none'; camera *; geolocation 'none'; gyroscope 'none'; magnetometer 'none'; microphone 'none'; payment *; usb 'none'" />
      </customHeaders>
    </httpProtocol>

**Comment by dom2049** [comment]
`<httpProtocol>
      <customHeaders>
        <add name="Feature-Policy" value="accelerometer 'none'; camera *; geolocation 'none'; gyroscope 'none'; magnetometer 'none'; microphone 'none'; payment *; usb 'none'" />
      </customHeaders>
    </httpProtocol>`

**Comment by mebjas** [comment]
This is very interesting, thanks for calling this out - there is a full read at https://developer.mozilla.org/en-US/docs/Web/HTTP/Feature_Policy/Using_Feature_Policy and I should probably call this out in main README

Can you confirm if fixing the `Feature-Policy` header on server side fixed this?

**Comment by mebjas** [comment]
I found out that there is a javascript API to check the list of allowed feature policies
```js
document.featurePolicy.allowsFeature("camera");
```

I'll add this to the library to make debugging easier.

Reference: https://developers.google.com/web/updates/2018/06/feature-policy#js

**Comment by mebjas** [comment]
But the key problem asked by @vfa-loinh is for the demo website which should have this feature policy enabled. I'll try to reproduce this in Line internal browser. @vfa-loinh Can you share any new context you may have into the issue or if this is still an issue?

**Comment by dom2049** [comment]
For me the feature-policy setting for the camera definitely resolved the issue. I was using nopCommerce that comes with the CSP headers preset in the web.config and they explicitly forbid the use of the camera("camera: 'none'). And that overrides browsers even asking for the permission from the user.
You can see where I figured it out after I received help after filing a bug with chromium. https://bugs.chromium.org/p/chromium/issues/detail?id=1131630

This was not mentioned anywhere else I googled around. In hindsight it makes perfect sense, but this was the first time I came into contact with CSP feature-policy header, and couldn't find anyone with the same problem using your scanner. Actually saw more people around the internet with similar issues of not being able to get the browser ask for camera permission. The nopCommerce custom headers excerpt from web.config is below. I see @vfa-loinh fixed his issue.

Cheers

` <customHeaders>
        <remove name="X-Powered-By" />
        
        <add name="X-XSS-Protection" value="1; mode=block" />
        
        <add name="X-Frame-Options" value="SAMEORIGIN" />
        
        <add name="X-Content-Type-Options" value="nosniff" />
        
        <add name="Strict-Transport-Security" value="max-age=31536000; includeSubDomains" />
        
        <add name="Content-Security-Policy" value="default-src 'self'; connect-src *; font-src * data:; frame-src *; img-src * data: blob:; media-src *; object-src *; script-src * 'unsafe-inline' 'unsafe-eval'; style-src * 'unsafe-inline';" />
        
        <add name="Referrer-Policy" value="same-origin" />
        
        <add name="Feature-Policy" value="accelerometer 'none'; camera '*'; geolocation 'none'; gyroscope 'none'; magnetometer 'none'; microphone 'none'; payment *; usb 'none'" />
      </customHeaders>`

**Comment by edilson20yadir** [comment]
Good afternoon.
I have a bug, that when the permissions are requested, it goes to the next execution and it does not list the cameras and it presents me with the following error ERR_FILE_NOT_FOUND in the html5-qrcode.min.js file
Thanks

**Comment by mebjas** [comment]
Thanks for confirmation. I'll close this bug in that case, please reopen if the issue persists.
