### ISSUE TITLE
How to make the camera focus automatically

### ISSUE THREAD

**Issue by sensationpanda** [mebjas/html5-qrcode#116]
when I scan a small size QR code, this can't match the QR code, If the camera can autofocus, it can solve this problem. Is anyone who knows how to make a camera autofocus? Thanks

**Comment by mebjas** [comment]
What is your test environment here? That would be device, OS, browser etc.

Can you share some screenshots as well if possible. Auto focus might be possible if the APIs are exposed by your environment.

**Comment by sensationpanda** [comment]
> What is your test environment here? That would be device, OS, browser etc.
> 
> Can you share some screenshots as well if possible. Auto focus might be possible if the APIs are exposed by your environment.

I tested it on my website, the device is iPhone, my problem is that if I scan a QR code that is less than 130 pixels, which cannot scan successfully. Because the size of the QR code is too small, the QR code will be very blurry and the camera cannot recognize it. But if I use the iPhone’s own camera scan function, the iPhone’s camera will automatically focus, and the code can be scanned successfully

Is there a way to solve the problem of scanning a small QR code

**Comment by mebjas** [comment]
Can you add a sample screenshot here? I'll try to see if something can be done to scan it.

**Comment by mebjas** [comment]
just fyi, I have created a new PR (experimental) that will allow the users to request for manual focus if the device's camera support the capability. But handling focus would be a very tricky option from the app level and it's better handled at the device's auto focus level.
