### ISSUE TITLE
Compatibility - [IOS] Safari - Button not Clickable to open camera

### ISSUE THREAD

**Issue by tayssirch** [mebjas/html5-qrcode#117]
Java Script Error 
SyntaxError Unexpected token '=' Expected an opening '(' before a method's parameter list
https://blog.minhazav.dev/research/h5q-direct
If you enter to this URL, the button "Start Scanning" is not working on Safari, 

Tested on:
Macbook Air - Safari
Iphone - Safari

here the error in the console:
https://ibb.co/WzvFZjb

**Comment by mebjas** [comment]
Yea that was a issue with my demo code, it was using the ECMA5 Javascript which I use for development, I switched it to using minified pure js code - it should work now.

I'll close this issue as resolved, please reopen if this is still happening for you.
