### ISSUE TITLE
Can't preselect environment camera

### ISSUE THREAD

**Issue by Silviobramas** [mebjas/html5-qrcode#119]
How can I pre select the environment camera in simple mode?

When I try to use the pro mode it's not possible to get an camera id. But when i use the simple mode I have an access to the cameras.
```js
Html5Qrcode.getCameras().then(cameras => {
          alert('test');
          //devices would be an array of objects of type:{ id: "id", label: "label" }
           if (devices && devices.length) {
            alert('test2');
               cameraId = devices[0].id;
                // .. use this to start scanning.
            }
      }).catch(err => {
              alert('Fehler');
      });
```

Any idea how to preselect the camera in simple mode or tu gat the camera id in pro mode?
Thanks

**Comment by mebjas** [comment]
You can preselect the `environment` camera in `simple` mode (i.e. using `Html5Qrcode` class directly) by passing cameraConfig in place of cameraId

```js
const html5QrCode = new Html5Qrcode(/* element id */ "reader");
html5QrCode.start(
  { facingMode: "environment" }, 
  {
    fps: 10,    // Optional frame per seconds for qr code scanning
    qrbox: 250  // Optional if you want bounded box UI
  },
  qrCodeMessage => {
    // do something when code is read
  },
  errorMessage => {
    // parse error, ignore it.
  })
.catch(err => {
  // Start failed, handle it.
});
```

Reference: https://github.com/mebjas/html5-qrcode#start-scanning

As for using it in `Html5QrcodeScanner` which I assume is the pro mode (correct me if I am wrong) - it's not supported yet. I am still trying to understand how to best extend the support there (What would be the user interface?) - if you have any suggestions please add it to https://github.com/mebjas/html5-qrcode/issues/65

**Comment by mebjas** [comment]
It seems to be working for me, check out this demo written by [ScanApp](https://scanapp.org) - [Demo using `Html5Qrcode` class](https://scanapp.org/demo/html5qrcode-class)
