### ISSUE TITLE
Compatibility - [Linux] [Firefox] - [aspectRatio]

### ISSUE THREAD

**Issue by mzijlstra** [mebjas/html5-qrcode#122]
**Describe the bug**
aspectRatio configuration doesn't work under Firefox because this constraint is not yet supported by Firefox, see: 
https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackConstraints/aspectRatio#Browser_compatibility

**Additional context**
By allowing the user to pass a full videoTrackConstraint object the problems caused by this can be avoided (since the user can then specify width and height, which imply an aspect ratio). 

I made these changes and will include the diff here (I'm not very good with Git yet), if you want I'll attempt a pull request as well.
```
--- a/src/html5-qrcode.js
+++ b/src/html5-qrcode.js
@@ -94,9 +94,18 @@ class Html5Qrcode {
      *          |********************|
      *          |********************|
      *          ----------------------
-     *      - aspectRatio: Optional, desired aspect ratio for the video feed.
-     *          Ideal aspect ratios are 4:3 or 16:9. Passing very wrong aspect
-     *          ratio could lead to video feed not showing up.
+     *      - videoConstraints: Optional object, can specify the desired width, 
+     *          height, aspect ratio, and frame rate for the video feed. 
+     * 
+     *          const constraints = constraints = {
+     *              width: { min: 640, ideal: 1920, max: 1920 },
+     *              height: { min: 400, ideal: 1080 },
+     *              aspectRatio: 1.777777778,
+     *              frameRate: { max: 30 },
+     *          };
+     * 
+     *  Example from: https://developer.mozilla.org/en-US/docs/Web/API/Media_Streams_API/Constraints
+     *  Reference: https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackConstraints#Properties_of_video_tracks
      *      - disableFlip: Optional, if {@code true} flipped QR Code won't be
      *          scanned. Only use this if you are sure the camera cannot give
      *          mirrored feed if you are facing performance constraints.
@@ -300,14 +309,11 @@ class Html5Qrcode {
                 }
 
                 $this._localMediaStream = mediaStream;
-                if (!config.aspectRatio) {
+                if (!config.videoConstraints) {
                     setupVideo();
                 } else {
-                    const constraints = {
-                        aspectRatio : config.aspectRatio
-                    }
                     const track = mediaStream.getVideoTracks()[0];
-                    track.applyConstraints(constraints)
+                    track.applyConstraints(config.videoConstraints)
                         .then(_ => setupVideo())
                         .catch(error => {
                             console.log("[Warning] [Html5Qrcode] Constriants could not be satisfied, ignoring constraints", error);
```

**Comment by mebjas** [comment]
This feature request looks similar to https://github.com/mebjas/html5-qrcode/issues/97

Let me take this on and add support for passing video constraints directly as a hidden API for now. You can follow the conversation in https://github.com/mebjas/html5-qrcode/issues/97 to understand why I do not want to make it public yet but you can go ahead and use the latest version of library I publish.

If this would solve your requirement please close this issue and track https://github.com/mebjas/html5-qrcode/issues/97.

Thanks!

**Comment by mzijlstra** [comment]
You are right, passing the videoConstraints mentioned in #97 would solve this (specifically if width and height are included).

I'll close this request, and will track #97

Thanks!
