### ISSUE TITLE
[Feature request] Add support for flash Light

### ISSUE THREAD

**Issue by stefanodias** [mebjas/html5-qrcode#129]
Hello, in many cases we need Flash Light to reading QrCode, it's possible?

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by sondreb** [comment]
Anything happening with the "flashlight" branch/feature? Would love to have that feature available, and I see there is a branch that was worked on for it in 2021.

**Comment by ROBERT-MCDOWELL** [comment]
you could try to work on it and create a PR?

**Comment by ROBERT-MCDOWELL** [comment]
it seems to be ready for version 3
https://github.com/lafriks-fork/html5-qrcode/commit/23c8e76975b34947da2c783b366583c42c85edde

**Comment by sondreb** [comment]
@lafriks @mebjas ... any chance getting this merged?

**Comment by nexorianus** [comment]
giving this a push!
would also love to see this in the repo

**Comment by mebjas** [comment]
This is already possible with `Html5Qrcode` using `applyVideoConstraints(..)` API. I suppose I need to expose the current settings of the video track to make it full fledged.

Working on this right now for `version 2.2.5`. Here's what I plan to do:

1. Add support for torch button in `Html5QrcodeScanner` with a configuration (default false) as UI is not that good.
2. Expose `getRunningTrackSettings(..)` in both `Html5Qrcode` and `Html5QrcodeScanner`.
3. Make `getRunningTrackCapabilities(..)`, `applyVideoConstraints(..)` along with the new `getRunningTrackSettings(..)` non beta and add documentation for all these APIs.
4. After publishing add blog posts explaining how to enable torch as is with `Html5Qrcode`.

**Comment by mebjas** [comment]
The support is now in PR: https://github.com/mebjas/html5-qrcode/pull/570

Also, latest implementation has been deployed to https://scanapp.org (in case any one want to test and share more insights).

**Comment by mebjas** [comment]
Feature now submitted and published with `version 2.2.5`

You can checkout the demo on Android devices (Chrome) on https://scanapp.org or https://qrcode.minhazav.dev (to be published soon).

This is only supported for `Html5QrcodeScanner`, here's how to use it

```js
let html5QrcodeScanner = new Html5QrcodeScanner(
    "reader",
    {
        fps: 10,
        qrbox: qrboxFunction,
        // Important notice: this is experimental feature, use it at your
        // own risk. See documentation in
        // mebjas@/html5-qrcode/src/experimental-features.ts
        experimentalFeatures: {
            useBarCodeDetectorIfSupported: true
        },
        rememberLastUsedCamera: true,
        aspectRatio: 1.7777778,
        showTorchButtonIfSupported: true
    });
```

The `showTorchButtonIfSupported: true` part is the crucial one. It's off by default for now as I don't like the UI very much.

I'll write a blog post on how to use it for `Html5Qrcode` soon.

**Comment by mebjas** [comment]
The article
 - https://medium.com/p/ba931965fe78
 - https://scanapp.org/blog/2022/10/30/using-flash-or-torch-with-html5-qrcode.html

**Comment by diegomariani** [comment]
How can I change the language of the buttons and others library information?

**Comment by mebjas** [comment]
It's released.

Please check the change logs.

**Comment by nexorianus** [comment]
> It's released. Please check the change logs.

here on Github, yes.
but NPM still has v2.2.5 as its latest version.

```
✗ yarn add html5-qrcode@2.2.6
yarn add v1.22.19
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
Couldn't find any versions for "html5-qrcode" that matches "2.2.6"
? Please choose a version of "html5-qrcode" from this list: (Use arrow keys)
❯ 2.2.5 
  2.2.4 
  2.2.3
  ...
```

**Comment by mebjas** [comment]
Interesting, thanks for reporting this.

Will publish asap.

**Comment by mebjas** [comment]
Published: https://www.npmjs.com/package/html5-qrcode/v/2.2.6
