### ISSUE TITLE
qr-reader-results - special characters

### ISSUE THREAD

**Issue by Martin-SK** [mebjas/html5-qrcode#134]
Hi, when QR code is decoded output in **qr-reader-results** is **without special characters**. 

**Screenshot:** 
https://prnt.sc/vfnyn0

It possible to fix that? Thanks

**Comment by max2ti** [comment]
Maybe part of this is relevant https://github.com/mebjas/html5-qrcode/issues/63#issuecomment-669829605

**Comment by mebjas** [comment]
@Martin-SK Thanks for raising this, As @max2ti shared this has been a issue for a while now. It's similar to https://github.com/mebjas/html5-qrcode/issues/63.

To address this I have been considering to move to ZXing js based library. I have created a prototype in `beta-zxing` branch. Based on my testing the library seems to be able to scan the QR code you have shared reliably.

This is what I got from decoding the shared QR Code
```
Díky QR generátoru si můžete vytvořit svůj vlastní QR kód, který můžete libovolně používat na svých stránkách nebo ho vkládat k tištěnému textu. Váš vytvořený kód pak může kdokoliv vyfotit a načíst zdarma přes QR čtečku
```
Please CMIIW if this is wrong.
 
You can try out the demo here: https://blog.minhazav.dev/research/html5-qrcode-beta 
Here's the minified code to experiment with: [link to minified js](https://raw.githubusercontent.com/mebjas/html5-qrcode/beta-zxing/minified/html5-qrcode.min.js)

Can you try out the beta demo with similar QR codes and share if you find any issues? If the results look good, I'll move the underlying code base to use `ZXing`. It comes with some extra benefits like support for barcode etc but requires some refactor but the cost benefit seems good.

**Comment by Martin-SK** [comment]
Hi, now everything works correctly. 

I tried different QR codes with special characters and everything is ok. 

Good job

**Comment by vklaus** [comment]
It really works perfectly now! In official version I have to use:
`message = decodeURIComponent(escape(qrCodeMessage));`

But since the probem with bad results (#63) I will have to use only new (beta) version.
Thank you! 👍👍👍

**Comment by mebjas** [comment]
Code has now been migrated to use `Zxing-js` in v2.0.0. Hoping for it to fix the decode issues.

Support added with https://github.com/mebjas/html5-qrcode/pull/173

 - Demo: https://blog.minhazav.dev/research/html5-qrcode
 - Github release: https://github.com/mebjas/html5-qrcode/releases/tag/V2.0.0
 - NPM: https://www.npmjs.com/package/html5-qrcode

**Comment by vklaus** [comment]
It seems to me that version 2.0 is great and works well with special characters.
Thank you!

**Comment by mebjas** [comment]
Thanks for verification @vklaus 

@Martin-SK @max2ti - Would it be possible to verify this for your use cases, if it tends to fix I'd close this issue.

**Comment by mebjas** [comment]
Closing this issue as resolved.
