### ISSUE TITLE
Demo not Working on Current IOS

### ISSUE THREAD

**Issue by jkassis** [mebjas/html5-qrcode#138]
iPhone 8
ios 14.2

**Comment by mebjas** [comment]
Which browser?

**Comment by jkassis** [comment]
safari

**Comment by mebjas** [comment]
Thanks for pointing this out, there was a recent regression in demo code, which broke it for Safari IOS. This has been fixed now please retry.

**Comment by mebjas** [comment]
I have tested latest demo on iphone 7 safari and it works now.

**Comment by mebjas** [comment]
Marking as closed, please reopen if the issue still exists.
