### ISSUE TITLE
Error locator degree does not match number of roots

### ISSUE THREAD

**Issue by georgewei** [mebjas/html5-qrcode#140]
I've read [(https://github.com/mebjas/html5-qrcode/issues/55)], i'm not sure if it is solved. Today, I met the same error.

This is the test qrcode, which is generated by jquery's qrcode() function:

```
$('#qrcode-login').qrcode({
   width: 300,
   height: 300,
   text: the_qrcode_text
});
```
![test_qrcode](https://user-images.githubusercontent.com/28130/99789409-821fb100-2b5d-11eb-8df8-e25bf356bbc0.png)

**Comment by mebjas** [comment]
@georgewei Thanks for raising this, this has been a issue for a while now. As you reported it's similar to #55.

To address this I have been considering to move to ZXing js based library. I have created a prototype in `beta-zxing` branch. Based on my testing the library seems to be able to scan the QR code you have shared reliably.
 
You can try out the demo here: https://blog.minhazav.dev/research/html5-qrcode-beta 
Here's the minified code to experiment with: [link to minified js](https://raw.githubusercontent.com/mebjas/html5-qrcode/beta-zxing/minified/html5-qrcode.min.js)

Can you try out the beta demo with similar QR codes and share if you find any issues? If the results look good, I'll move the underlying code base to use `ZXing`. It comes with some extra benefits like support for barcode etc but requires some refactor but the cost benefit seems good.

**Comment by georgewei** [comment]
I've tried the demo, the scanned result is not stable:

> [1] - scan:2e25ea0dfbd84c0abffd50d180adf8ae
> [2] - scAn:2e25ea0dfbd84c0abffd50d180adf8ae
> [3] - scan:2e25ea0dæbd84c0abffd50d180adf8ae
> [4] - scan:2e25ea0dfbd84c0abffd50d180adf8ae
> [5] - scan:2e25ea0afbd84c0abffd50d180adf8ae
> [6] - scan:2e25ea0dfbd84c0abffd50d180adf8ae
> [7] - scan:2e25ea0`fbd84c0abffd50d180adf8ae
> [8] - scan:2e25ea0dfbd84c0abffd50d180adf8ae

The test qrcode:

**Comment by georgewei** [comment]
It's even worse for my first test qrcode in this thread:

> [1] - scan:04bbb8839ff74dc7a0e33bdbba1ff63ÁÁÁÀ
> [2] - scan:04bbb8839ff74dc7a3e33bdbba1dÈf63
> [3] - scan:04bbb8839ff74dc7a3e33bdbba1d¨f63
> [4] - scan:04bbb8839ff74dc7a3e33bdbba1dHf63
> [5] - scan:04bbb8839ff74dc7a3e33bdbba1fhf63
> [6] - sccn:04bbb8839ff74dc7a3e33bdbba1fèf63
> [7] - sccn:04bbb8839ff74dc7a3e33bdbba1fÈf63
> [8] - scan:04bbb8839ff74dc7a3e33bdbba1dÈf63
> [9] - sccn:04bbb8839ff74dc7a3e33bdbba1fHf63
> [10] - scan:04bbb8839ff74dc7a0e33bdbba1f(f63

**Comment by mebjas** [comment]
It seems to be related to the input feed, can you share what platform are you using to test? Even the new QR code seem to work fine but I am testing on Pixel 3.

**Comment by georgewei** [comment]
I'm using MI MIX 2, Android 9. These two codes can be recognized correctly by Wechat.

**Comment by georgewei** [comment]
@mebjas I've tried again, these two codes can be recognized correctly on my MAC. I think the strange result of the previous test dues to my old IBM X230 laptop: the resolution of its screen is only 1388*768. However, Wechat can recognize these 
codes correctly on both machines.

**Comment by georgewei** [comment]
@mebjas This issue is misinformed. It dues to the wrong code in my qrCodeSuccessCallback handler which throws an exception but not catched, then the caller function qrcode.decode() fails.

btw, I've tried to integrated the code of ZXing branch into my project, it works well right now.
