### ISSUE TITLE
[Feature Request] select environment camera by default

### ISSUE THREAD

**Issue by Zaffer** [mebjas/html5-qrcode#147]
Can you please make the front facing camera { camera: environment } the default selection in your easy code version? No one scans a QR code with there selfie cam! 

I have done use testing and very always faces this issue when the first use the plugin. It opens to selfie first and then they don't know what to do next. This will save much frustration and be better user experience.

Additionally, can add a swap camera button please? To quickly change camera while it is busy scanning? The problem is now once scanning, the users are trying to change the camera but have to first click stop scanning, and then camera selection, choose a camera, and click scan again. This can be replaced with one click, swap camera. (This just stop, next camera, scan again in one button).

Thanks!

**Comment by Yididiyah** [comment]
I'm also facing the same issue. There has to be a consistent way to select which camera to use by default from the code, similar to the what MediaDevices.getUserMedia() has facing mode prop.

**Comment by mebjas** [comment]
Closing here as redundant.
