### ISSUE TITLE
TypeError: cannot read property 'then' of undefined 

### ISSUE THREAD

**Issue by bapak71** [mebjas/html5-qrcode#157]
Hi. I got this error when trying to use this qrcode scanner. I've tried it on my own server

https://booking.lawwa.online/qrcode2/scanner.php

and also on the demo page

https://blog.minhazav.dev/research/html5-qrcode.html

the error trigger when i click on [Request Camera Permissions]

.. is it problem with my phone ?

i'm using vivo - android ver 9.

thanks in advance

really hope this could work for me.

![Screenshot_20210129_023703](https://user-images.githubusercontent.com/2958113/106189630-83b3c800-61e3-11eb-9808-b986fbf4f9f1.jpg)

**Comment by georgewei** [comment]
Which browser are you using? Both your demo and the author's work fine on my MI Mix 2, Android 9, Yandex 20.4.4(A Chrome compatible browser).

**Comment by bapak71** [comment]
somehow i manage to get it working today... thanks anyway.

**Comment by bapak71** [comment]
i know i already close this - just for note - i just realise the issue only raise when i use VIVO browser. 

it is ok when i open using mobile chrome.

**Comment by mebjas** [comment]
I see, looks like VIVO browser doesn't support promise APIs, is that a common browser used?

**Comment by georgewei** [comment]
Global Smartphone Market Share of Q3, 2020, by IDC

https://www.idc.com/promo/smartphone-market-share/vendor

Vivo was back to top 5 and owned 8.9% market share.
