### ISSUE TITLE
Iam getting this "QR code parse error"

### ISSUE THREAD

**Issue by sameerdodai58** [mebjas/html5-qrcode#158]
Iam getting this "QR code parse error, error = couldn't find enough finder patterns" very frequently almost all the time 8 attempts fails out of 10. Don't why this issue occurs .
Iam using chrome on android 10 in samsung mobile and verion of library is (v1.0.5)

    <div id="reader" style="max-width:100;width:250px;height:300px; border: 1px solid blue; float: left"></div>
    <br>
    <div id="message" style="max-width:100;width:250px;height:300px; border: 1px solid blue; float: left;font-size: 25px"></div>
    <div id="error_message">
    </div>
    <input type="file" id="qr-input-file" accept="image/*" capture style="font-size: 25px;padding: 150px">
    <script type="text/javascript">

        const html5QrCode = new Html5Qrcode("reader");
        const fileinput = document.getElementById('qr-input-file');
        fileinput.addEventListener('change', e => {
            if (e.target.files.length == 0) {
                return;
            }
            const imageFile = e.target.files[0];
            html5QrCode.scanFile(imageFile, true)
            .then(qrCodeMessage => {
                console.log(qrCodeMessage);
                document.getElementById("error_message").innerHTML ="";
                document.getElementById("message").innerHTML =qrCodeMessage
            })
            .catch(err => {
                document.getElementById("message").innerHTML ="";
                document.getElementById("error_message").innerHTML =`${err}`
            });
        });
        html5QrCode.clear();
    </script>

**Comment by mebjas** [comment]
In the latest version starting v2.0.0 we have ported the library to Zxing-js which extends support for more codes and makes QR code scanning robust. Would it be possible to verify this with latest version?

Support added with https://github.com/mebjas/html5-qrcode/pull/173

 - Demo: https://blog.minhazav.dev/research/html5-qrcode
 - Github release: https://github.com/mebjas/html5-qrcode/releases/tag/V2.0.0
 - NPM: https://www.npmjs.com/package/html5-qrcode

**Comment by mebjas** [comment]
Marking as closed, please reopen if this issue still exists.
