### ISSUE TITLE
Expanding qrScanSuccess() with additional parameters or return the qrMessage itself.

### ISSUE THREAD

**Issue by rajpancha1** [mebjas/html5-qrcode#160]
Hello Minhaz and all:
I am new to this forum. And I am not an expert in javascript.

This is a great project. Thank you,  Minhaz.

**Is your feature request related to a problem? No
I'm using html5-qrcode.js  to scan QRcode and populate the key:value pairs from the result qrMessage on to the HTML5 page text fields.

** A clear and concise description of what the problem is: 
An option to return the first successful qrMessage instead of user intervention to stop the scanning.

**Describe the solution you'd like**
Have qrScanSuccess() return the first successfully scanned qrMessage to the client application so that application can parse it to populate the fields.

**Describe alternatives you've considered**

I have copied the html5-qrcode.js  and qrcode.js to my project to customize it. Before I resort to passing down the edit field parameters to the qrcode.js at:
        ------------------------
        if (qrcode.callback != null)
                console.log("================> At Line 1781"); 
                qrcode.callback(qrcode.result, element1, element2,  element3 :waffle: etc. );
        return qrcode.result;
       -----------------------------
I want to consult the experts for a better way to extract qrMessage to populate the edit fields on the html5 page.

I would greatly appreciate guidance or examples from the forum members.

Minhaz, does this request  qualify as candidate for a more generalized feature extension? At a minimum return the qrMessage to the client application's space from the callback().

Thanks,
RP

**Comment by mebjas** [comment]
> An option to return the first successful qrMessage instead of user intervention to stop the scanning.

The way to handle this would be

```js
let html5QrcodeScanner = new Html5QrcodeScanner(
  "reader", 
  { 
      fps: 10,
      qrbox: { width: 300, height: 300 },
  
  });
function onScanSuccess(decodedText, decodedResult) {
    html5QrcodeScanner.clear();
    // next action you want to take
}
html5QrcodeScanner.render(onScanSuccess);
```
