### ISSUE TITLE
Read Barcode (EAN, UPC, ...)

### ISSUE THREAD

**Issue by daffymarco** [mebjas/html5-qrcode#163]
Hello!

This API is very nice, but I need to read EAN, UPC, ITF-14, 128, and so on... It's possible update to this options too?

Thank you.

**Comment by mebjas** [comment]
Support added with https://github.com/mebjas/html5-qrcode/pull/173

 - Demo: https://blog.minhazav.dev/research/html5-qrcode
 - Github release: https://github.com/mebjas/html5-qrcode/releases/tag/V2.0.0
 - NPM: https://www.npmjs.com/package/html5-qrcode
