### ISSUE TITLE
Opening the camera writes error messages in the console

### ISSUE THREAD

**Issue by ianaltosaar** [mebjas/html5-qrcode#165]
Once the camera is activated and the user wants to scan the QR code, there's a continuous error message in the console.

The camera works, the scanning works but new lines of error messages are constantly written in the console. Error messages below.

![console](https://user-images.githubusercontent.com/72142534/111138187-4daa8780-8588-11eb-91e8-42823a069f9b.png)

**To Reproduce**

Happens every time when the user starts to use the camera/scanner.

**Desktop :

 - Browser  = chrome
 - Version = 88

**Comment by ianaltosaar** [comment]
Forgot to add that this problem only applies to the beta version https://github.com/mebjas/html5-qrcode/tree/beta-zxing

**Comment by JimmyBjorklund** [comment]
Try the latest version, its fixe for me there 2.0.1

**Comment by mebjas** [comment]
This should now be fixed in version 2.0.1 --> closing!

**Comment by ianaltosaar** [comment]
Thanks, it worked.
