### ISSUE TITLE
unable to query supported devices.

### ISSUE THREAD

**Issue by tobiashld** [mebjas/html5-qrcode#166]
The Code results in an log message "unable to query supported devices. I've tried many variations of Codes for Example. the transpiled one and the minified versions but it's always the same result. I'm just getting into coding and i don't know what i should do. 
The Devices i've tried the code on were my pc (runnin on windows 10) and my Iphone X (runnin on ios 14.4).

**Comment by diwakar2000** [comment]
same problem with me

**Comment by mebjas** [comment]
@tobiashld @diwakar2000 

Few question:
1. Is the demo website running for you on the same set of devices - [link to demo](https://blog.minhazav.dev/research/html5-qrcode) ?
2. Can you share screenshot of developer console running the demo app - in case there is more information there.

**Comment by tobiashld** [comment]
1. Yes, I tested it on my iphone on my own website and on the demo website. Everything was fine on the demo website but on my website there was the good old "unable to query supported devices" error.
2. 
![qrcodeproblem](https://user-images.githubusercontent.com/42995595/114759440-70ce7f80-9d5e-11eb-9eb4-63bbbb3f77f1.PNG) this is a screenshot of the console log from the demo website and this 
![qrcodeproblemOwnSite](https://user-images.githubusercontent.com/42995595/114759481-82178c00-9d5e-11eb-9716-b22284f900f5.PNG) is a screenshot of the console log from my own site.

**Comment by diwakar2000** [comment]
For me, the problem was that I was using it on a site without SSL
certificate. So, my problem has been fixed. Thank you for the follow up.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by mebjas** [comment]
Ah this has happened in the past, let me add a better error messaging in the interim to surface this issue faster to users / developers. @tobiashld  is it possible you are having similar issue? Is there an online link I can try?

**Comment by tobiashld** [comment]
its very likely hahaha @mebjas I was already planing on using a ssl certificate. If the qr code scanner is not working with an implemented ssl certificate i am going to open another issue or so but i think we can close this one for now.
