### ISSUE TITLE
[Feature request] Add support for argument to hide file based scan option.

### ISSUE THREAD

**Issue by vincent12dev** [mebjas/html5-qrcode#176]
Hi, 
how to use only camera without file "Scan an image File".

Best regards

**Comment by mebjas** [comment]
Currently this is not supported, changed this to feature request.

**Comment by OpenSourceSucks** [comment]
$("#qr-reader__status_span").parent().css('visibility', 'hidden');
		$("#qr-reader__status_span").parent().css('display', 'none');
		$("#qr-reader__dashboard_section_swaplink").css('visibility', 'hidden');
		$("#qr-reader__dashboard_section_swaplink").css('display', 'none');

**Comment by mebjas** [comment]
This was implemented with https://github.com/mebjas/html5-qrcode/pull/434
