### ISSUE TITLE
[Feature Request] Add support for providing the code formats to support

### ISSUE THREAD

**Issue by mebjas** [mebjas/html5-qrcode#177]
Since Version 2.0.0 the library has added support for various code formats (2D and 1D formats). Not every users might have this usecase, add support for passing a list to override this - by default it could parse every formats.

Add documentation and write up on this.

**Comment by mooreaa** [comment]
I think this is a good idea, especially if it would improve the performance knowing what types of barcodes to look for.
This is done on various barcode scanner units and can really improve acquisition time, especially on older/slower devices.

**Comment by DerDee** [comment]
TLDR: +1
This would be very nice to have since this module would be used in different products with different set of code formats it should read. To be able to select format using some form of configuration would remove the step from rebuilding this project for every product.

**Comment by mebjas** [comment]
Hoping to get this out in next version asap (see linked PR)

**Comment by mebjas** [comment]
Feature support to be launched in version 2.0.8

 - Github release: https://github.com/mebjas/html5-qrcode/releases/tag/V2.0.8
 - NPM: https://www.npmjs.com/package/html5-qrcode/v/2.0.8
