### ISSUE TITLE
Error after last update

### ISSUE THREAD

**Issue by jbrasero** [mebjas/html5-qrcode#180]
Hi, after last update, it's not working my app and I'm getting following error...

html5-qrcode.min.js:4 Uncaught TypeError: Cannot read property 'scanFile' of undefined
    at HTMLInputElement.<anonymous> (html5-qrcode.min.js:4)

Any idea? 
Thanks and best regards,
 Jesús

**Comment by mebjas** [comment]
I cannot reproduce this on Chrome/MacOS - can you share where you are seeing this issue (which browser / device?)

**Comment by jbrasero** [comment]
Hi! Thanks for your review. My app was working and suddenly I receive these error.
Now fails on Chrome/MacOS and Safari/MacOS
Thanks for you help & support

<img width="1402" alt="safari" src="https://user-images.githubusercontent.com/10437309/115159811-3aae3a00-a095-11eb-8b54-7747c803acc5.png">

**Comment by jbrasero** [comment]
Hi, I have solved  including the zxing.js script... on my page.
 <script src="https://unpkg.com/@zxing/library@0.18.5/umd/index.js"></script>
Thanks
