### ISSUE TITLE
Modify images path

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [mebjas/html5-qrcode#192]
Would it be nicer to have a "relative" path of the GIF images rather than point to github website?
Talk about camera-scan.gif and file-scan.gif
thanks

**Comment by mebjas** [comment]
> Would it be nicer to have a "relative" path of the GIF images rather than point to github website?

I am not sure I understand `relative` path here? `relative` to what? - It could be done, but would require the library to be always bundled with the assets.

What issues are you facing with the assets being hosted on Github?

**Comment by ROBERT-MCDOWELL** [comment]
it's just to avoid to call images out of own server. for exemple if the website is offline.
just say that since I cannot reminify your code, on Fedora the only minify is yui-compressor which destroy completely your code :(

**Comment by mebjas** [comment]
There was a PR in the past to inline the assets (https://github.com/mebjas/html5-qrcode/pull/95/files) which didn't get fully merged. Also there might be a way to have the assets as lightweight SVGs built into the the scripts.

Need to dig more into this.

**Comment by ROBERT-MCDOWELL** [comment]
indeed, svg loaded locally or even from base64 encode will avoid url request dependency

**Comment by mebjas** [comment]
@ROBERT-MCDOWELL - this PR should also address the need for a relative asset
