### ISSUE TITLE
[Feature Request] Use native detector if supported

### ISSUE THREAD

**Issue by AlfonsoML** [mebjas/html5-qrcode#195]
**Is your feature request related to a problem? Please describe.**
Chromium has added native support to detect barcodes, so using it would be interesting as it can lead to better performance in the long term.

**Describe the solution you'd like**
Use the native API: https://web.dev/shape-detection/

**Additional context**
The API is available only in Chromium on Android, CrOS and MacOS, but it's detectable so the rest of browsers/OS can keep on working with the current code.

**Comment by ROBERT-MCDOWELL** [comment]
are the browsers garantee security about private data from the barcodes? I didn't see any whitepapers or articles preserving barcodes private data and confidentiality

**Comment by AlfonsoML** [comment]
You might want to raise your concerns in https://github.com/WICG/shape-detection-api/issues
The only concern that I've found is this one from Mozilla https://github.com/mozilla/standards-positions/issues/21

**Comment by mebjas** [comment]
Thanks for sharing this, for starters now we have support for intermediate shim layers, (those implement [QrcodeDecoder](https://github.com/mebjas/html5-qrcode/blob/master/src/code-decoder.ts#L17) interface) we should be able to plug native decoders.

I'll tryout `BarcodeDetector` and run some performance test around it.

**Comment by mebjas** [comment]
I prototyped this approach and it seems to run faster on my Macbook / Google Chrome. Need to test this on more devices including mobile devices. On the Mac it seemed to be running at 2x speed as compared to ZXing based decoder and have support for majority of the formats listed

**Comment by mebjas** [comment]
Using native library has clear performance benefits but the support is not good yet.


| Device | With ZXing | With BarcodeDecoder |
|--|--|--|
| Macbook Pro 16, Google Chrome | 21 ms |  10 ms|
| Pixel 4 Google Chrome | 56 ms | 23 ms |
| Pixel 4a Google Chrome | 92 ms| 47.3 ms |
| (low end) Android Device Google Chrome | 373 ms | 77.5 ms|
