### ISSUE TITLE
Issue with open/close camera

### ISSUE THREAD

**Issue by ucola** [mebjas/html5-qrcode#196]
**Describe the bug**
We implement a "camera" icon, for open close directly the reader. On first time (press button, we start the camera, the qrcode is reading out) we stop the camera. If we press again on the camera icon, we became an error on console.

```
html5-qrcode.min.js:4 Uncaught (in promise) TypeError: Cannot read property 'getVideoTracks' of null
    at html5-qrcode.min.js:4
    at new Promise (<anonymous>)
    at a.value (html5-qrcode.min.js:4)
    at HTMLButtonElement.<anonymous> (:113)
```

**Expected behavior**
Our Implementation is like bellow

```
window.addEventListener('load', function () {
        const html5QrCode = new Html5Qrcode('qrReader');
        let cameraStatus = false;
        let cameraButtons = document.querySelectorAll('.camera-button');
        let outputMessages = document.querySelectorAll('#outputMessages');
        cameraButtons.forEach(el => el.addEventListener('click', event => {
            outputMessages.innerHTML = '';

            if (cameraStatus == true) {
                html5QrCode.stop();
                cameraStatus = false;
            }
            else {
                var resultid = el.getAttribute('data-qrresultid');
                var resultContainer = document.getElementById(resultid);
                html5QrCode.start(
                    {
                        facingMode: "environment"
                    },
                    {
                        fps: 20,
                        qrbox: 250
                    },
                    qrCodeMessage => {
                        console.log('Code: ' + qrCodeMessage);
                        resultContainer.value = qrCodeMessage;
                        html5QrCode.stop();
                    },
                    errorMessage => {
                        // Error on scanning
                    }
                ).catch(err => {
                    outputMessages.innerHTML = 'Error on start camera.';
                });
                cameraStatus = true;
            }
        }));
    });
```

**Smartphone (please complete the following information):**
 - Device: Pixel 5
 - OS: Android
 - Browser Chrome
 - Version 90.0.4430.91

**Comment by Techn1c4l** [comment]
This error appears when you try to stop already stopped reader. There is no video tracks attached to the stream, so there is nothing stop. You should check if the code in your if statement somehow executes more than one time. Something like this:

if (cameraStatus == true)
{
    console.log("You should not see this message twice in a row");
    html5QrCode.stop();
    cameraStatus = false;
}

If you see the message more than one time per button click, something wrong with your code flow i.e. you are not starting the reader again, you're trying to stop it.

**Comment by ROBERT-MCDOWELL** [comment]
or use a try/catch to avoid JS error. unpredictable physical devices sometimes ruins the javascript code, so it's important to take care of the time/run/status of the code managing physical devices since each device react differently from time to react,exec and return state.

**Comment by ucola** [comment]
@Techn1c4l thank you, somewhere else (code) was closing the camera, that was the issue
