### ISSUE TITLE
Compatibility - [Mendix] ] - Reference error for ZXing

### ISSUE THREAD

**Issue by jeremyteh** [mebjas/html5-qrcode#199]
**Describe the bug**
Unable to detect ZXing when implementing the QRCode library and integrating into mendix HTML  snippet

**Describe the browser:**
 - OS: Windows
 - Browser: chrome 
 - Version: 90

**Screenshots**
<img width="445" alt="Screenshot 2021-05-14 at 10 44 15 AM" src="https://user-images.githubusercontent.com/26730409/118214266-0108fd00-b4a2-11eb-9b51-f06cca03535f.png">

**Comment by mebjas** [comment]
Can you confirm if you are using the `dist/html5-qrcode.min.js` ?

**Comment by mebjas** [comment]
Closing due to lack of information. Please reopen if the issue persists.
