### ISSUE TITLE
MediaStreamTrack.getSources() deprecated.

### ISSUE THREAD

**Issue by Prestodus** [mebjas/html5-qrcode#2]
MediaStreamTrack.getSources() seems to be deprecated and can be replaced by MediaDevices.enumerateDevices().

**Comment by mebjas** [comment]
@Prestodus feel free to send a pull, I'll verify and merge.
Too stuck up between work these days to learn and write :p

**Comment by mebjas** [comment]
- [ ] @mebjas look into this and onboard

**Comment by mebjas** [comment]
Added support to the latest APIs with backward support for the former.

Demo: https://blog.minhazav.dev/research/html5-qrcode.html
