### ISSUE TITLE
facingMode Not working

### ISSUE THREAD

**Issue by haspden** [mebjas/html5-qrcode#201]
I am having some real issues with `faceingMode` not working correctly.

in my javascript to start the scanner (html5-qrcode-test.js)  I have

```
function docReady(fn) {
    // see if DOM is already available
    if (document.readyState === "complete" || document.readyState === "interactive") {
        // call on next available tick
        setTimeout(fn, 1);
    } else {
        document.addEventListener("DOMContentLoaded", fn);
    }
} 

docReady(function() {
    var resultContainer = document.getElementById('qr-reader-results');
    var lastResult, countResults = 0;
    
    var html5QrcodeScanner = new Html5QrcodeScanner(
        "qr-reader", { facingMode: { exact: "environment"}}, { fps: 10, qrbox: 250 });
    
    function onScanSuccess(qrCodeMessage) {
    //do something on success here
    }
```
    

however, this is not calling the rear camera, and still displaying a list of cameras
    
in my HTML file I have referenced a local copy of the minified JS file

 ```
   <div id="qr-reader" style="width:100%"></div>
    <div id="qr-reader-results"></div>

  <script src="html5-qrcode.min.js"></script>
  <script src="html5-qrcode-test.js"></script>
  
```
  
  Any thoughts ?

**Comment by mebjas** [comment]
Please note that `facingMode` option is only supported for `Html5Qrcode` class and not `Html5QrcodeScanner` class.

I'll work on implementing it soon, please track this feature request at https://github.com/mebjas/html5-qrcode/issues/139

**Comment by mebjas** [comment]
Closing this issue as duplicate
