### ISSUE TITLE
Scan camera and file links inverted in last git

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [mebjas/html5-qrcode#211]
when the JS is loaded,
by default the camera scan type is launched, but the link below the button "request permissions"
should show the link that switch to "Scan an image file" rather than "Scan using camera directly"

**Comment by mebjas** [comment]
you are right, thanks for reporting.

Working on the fix

**Comment by mebjas** [comment]
fix released to https://github.com/mebjas/html5-qrcode/releases/tag/V2.0.6
