### ISSUE TITLE
Save selected cameraID for html5QrcodeScanner method

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [mebjas/html5-qrcode#214]
Is there a way to save the cameraID selected and attach it
when the page is reloaded later?

**Comment by mebjas** [comment]
Duplicate of https://github.com/mebjas/html5-qrcode/issues/85 - please follow that issue, I'll take that on soon

**Comment by mebjas** [comment]
Please reopen if that is not the case. Also, it'd be helpful if you could share full use-case in https://github.com/mebjas/html5-qrcode/issues/85
