### ISSUE TITLE
[Feature Request] Return the code format scanned.

### ISSUE THREAD

**Issue by mebjas** [mebjas/html5-qrcode#224]
In the QR Code decoded result, return the code format scanned.

Feature request raised by other users before:

By @GumballLab at [demo page](https://blog.minhazav.dev/research/html5-qrcode)
> When a code is detected is it possible to know the type of code?
> This would be very useful if you what to just read QR codes, for example.

By @lanost at discussion: https://github.com/mebjas/html5-qrcode/discussions/148#discussioncomment-860060
> Is there a way in which I can get the code type on success. Like code-128 or qr_code? I have a scenario where I need to know which type of code is scanned by the scanner, is it a barcode or a qr code etc.
>
> Without using any framework

**Comment by mebjas** [comment]
WIP demo updated to demo blog - https://blog.minhazav.dev/research/html5-qrcode

**Comment by vlassie66** [comment]
Hello mebjas. I want to use your code web application. Now there are a few people with an iphone and using rememberLastUsedCamera: true doesn't seem to work. How could I fix that?
