### ISSUE TITLE
Having issues with the camera image

### ISSUE THREAD

**Issue by GuyInCorner** [mebjas/html5-qrcode#229]
Having issues with the camera image:

- The camera image doesn't fill the phone screen.
- There are only two guide lines on the left, none on the right and they're not centered.
- The shaded area appears somewhat random and makes no sense.

This link is on a phone using a config of {fps: 10, qrbox: 225 }
https://www.dropbox.com/s/hrtj9sv8danwmn4/html5-qrcode_shader.jpeg?dl=0

I tried removing the qrbox and then it wouldn't scan at all.
What can I do to get a better image?

Tried this on iOS iPhone SE and google Pixel 2

**Comment by mebjas** [comment]
Can you share the screenshots for my better understanding?

**Comment by GuyInCorner** [comment]
Here's the image I get on the phone.  

- There are only two corners of the QRCode bounding box. 
- The image doesn't fill the screen
- The shaded area is a tiny spot in the top left

![html5-qrcode_shader](https://user-images.githubusercontent.com/61481372/146784316-226c7b6a-e262-4131-884f-d63c8ae3c3ea.jpeg)

**Comment by mebjas** [comment]
Can you share your code on codepen?

**Comment by GuyInCorner** [comment]
I'll dig it up.

**Comment by GuyInCorner** [comment]
Here's the file in which I use the html5-qrcode.  It's messy from various attempts at things as I don't consider it complete.  It's a qml file but it runs javascript in an html dom in the browser so don't worry about that part.  I'm using the PureQML framework.  At the end of the day it's all HTML and javascript.

The key parts were taken from the examples.  The privscan() function is where I set the config is set.

[QRCodeScan.zip](https://github.com/mebjas/html5-qrcode/files/7747383/QRCodeScan.zip)

**Comment by GuyInCorner** [comment]
I have solved the problem.  It was my issue.  I inadvertently created an extra reader div that was not needed.
