### ISSUE TITLE
Minified Js Path wrong

### ISSUE THREAD

**Issue by ameyamjoshi** [mebjas/html5-qrcode#244]
**Minified js path not found**

When we try to use github link it shows page not found . 

The path which is mentioned in current README.md is "https://raw.githubusercontent.com/mebjas/html5-qrcode/master/minified/html5-qrcode.min.js" and it gives 404 pag not found . 

To use the functionality I had to download source code and use in my project .
![github](https://user-images.githubusercontent.com/52293882/123516571-60217a80-d6ba-11eb-8887-874522b97278.png)

**Comment by Cr0aten** [comment]
Try this:  https://github.com/mebjas/html5-qrcode/raw/master/dist/html5-qrcode.min.js

**Comment by mebjas** [comment]
Thanks for raising this issue - fixed with https://github.com/mebjas/html5-qrcode/commit/09985974736fcea38c39d810ff7270699495efc5

@Cr0aten thanks for providing quick pointer
