### ISSUE TITLE
not found any camera from mobile

### ISSUE THREAD

**Issue by mirkoprog** [mebjas/html5-qrcode#25]
not found any camera on mobile and i dont have error in console, it work on pc.
i have try with your code but is same

this is my code
[index.txt](https://github.com/mebjas/html5-qrcode/files/4496589/index.txt)

**Comment by mebjas** [comment]
Ok this code is a clone of demo code. As @ziobit mentioned in another comment - are you trying this in `http` or `https` version?

**Comment by mirkoprog** [comment]
Http

**Comment by mebjas** [comment]
So it'd work only on localhost http. Otherwise, you need to use `https` for servers - this is a requirement by browsers to access Camera as it's a privacy concerning permission.

I have updated this in `README`

**Comment by mirkoprog** [comment]
ok thanks a lot, now i can open the camera but when i frame a qrcode nothing happens

**Comment by mebjas** [comment]
Can you share a video ?

**Comment by mebjas** [comment]
@mirkoprog any updates on this?

**Comment by mebjas** [comment]
Closing this bug as obsolete. @mirkoprog please feel free to reopen if this continues to happen.

**Comment by ashujill** [comment]
Qr code not scanning on safari browser please help me

**Comment by mebjas** [comment]
@ashutoshs4 Which demo were you testing?

**Comment by magizergi** [comment]
The scanner works when it is on live server like when I click golive in vscode but when i open the html file directly  the scanner ask permission but display couldn't find camera id error on console when start scanning
