### ISSUE TITLE
Should this work when the barcode is rotated to 90 degrees ?

### ISSUE THREAD

**Issue by tiendung88** [mebjas/html5-qrcode#254]
I have tested in 1d barcode but this does not work when barcode is rotated >40 degrees, Is there any solution for this ?. sorry, my english is not good

**Comment by ROBERT-MCDOWELL** [comment]
I think this is a normal behavior of a converntional barcode scanner. the code must be the most parallel possible to the scanner itself. for codes like qrcode I tested all angles possible and it works.

**Comment by mebjas** [comment]
+1 to @ROBERT-MCDOWELL 

Further support coming in https://github.com/mebjas/html5-qrcode/issues/372 please subscribe to that issue.
