### ISSUE TITLE
Html5Qrcode.getCameras is not a function

### ISSUE THREAD

**Issue by HamzaAlvi719** [mebjas/html5-qrcode#256]
I have followed the guide and implemented the same code. But I get this error every time and I can't resolve it.

**Comment by ROBERT-MCDOWELL** [comment]
what browser and version?

**Comment by HamzaAlvi719** [comment]
@ROBERT-MCDOWELL and @mebjas my browser is chromium and version is Version 92.0.4515.107 (Official Build) snap (64-bit)

**Comment by ROBERT-MCDOWELL** [comment]
are you sure your html5Qrcode object is created when the page is fully loaded?
