### ISSUE TITLE
Recognized scan-region for small viewports

### ISSUE THREAD

**Issue by OneDivZero** [mebjas/html5-qrcode#26]
**Bug**
There seems to be a problem with the recognized scan-region for small viewports. I printed a qr-code in the size of a hand and I'm trying it to scan with an iPhone 7 using a qr-box with 350x350px (and boxsize in code is not set, thus it should use full dimension). 

You have to hold your phone about 0,5m far away only for having a chance to get a match. And then it only succeeds in round about one out of ten trials. It works great with macbook-cam, when using a qr-box with more than 600+ px. But reducing step by step the size also works bad on desktop browser.

**Describe the browser:**
 - OS: iOS on iPhone 7
 - Browser: Safari
 - Version: latest

**Screenshots**
Fails on desktop too:

![202004120_200432-CapturFiles](https://user-images.githubusercontent.com/1638511/80673257-1ede0c80-8aaf-11ea-9d1e-f283f8ac5a41.png)

**Additional context**
Box: 350x350
BoxSize in JS: null

I can provide a playground if required.

**Comment by OneDivZero** [comment]
Maybe related to
https://github.com/mebjas/html5-qrcode/issues/21
?

**Comment by mebjas** [comment]
In that case I'll fix https://github.com/mebjas/html5-qrcode/issues/21 first and we can see if this is still an issue

**Comment by OneDivZero** [comment]
That would be great! Hope you'll find time as soon as possible. Just asking a bit obtrusive, cause the core of my project depends on your solution and I already checked out other libs. But either they are not really maintained and extremely buggy or to complex to integrate (e.g. they require server-side processing which is not an applicable use-case for me). 

Just FYI: I'm working on an open-source covid19-project :-)
best regards from germany

**Comment by mebjas** [comment]
@OneDivZero I have fixed https://github.com/mebjas/html5-qrcode/issues/21 with a recent push. I have also updated the [demo code](https://blog.minhazav.dev/research/html5-qrcode)

Can you validate if it fixes this issue for you?

**Comment by OneDivZero** [comment]
Yes that looks great ... It works on my iPhone as expected. I will acquire some friends for doing a test on different devices for further confirmation. Thank you!

**Comment by mebjas** [comment]
![image](https://user-images.githubusercontent.com/3007365/80812970-a6d12d00-8bfb-11ea-86e7-ff6fcc2919bd.png)

Validated to work fine on IPhone 7, Safari browser. Unfortunately only safari is supported on iphone due to issue in Webkit for ios

**Comment by mebjas** [comment]
Thanks for confirmation!

**Comment by mebjas** [comment]
@OneDivZero Closing this issue, feel free to reopen if this is found in some other device/browser or create a new issue.

**Comment by OneDivZero** [comment]
kk ... will share my test-results in a new issue

btw: I picked up the latest script from github, but I don't see the green edges?

**Comment by mebjas** [comment]
@OneDivZero - Can you check for console logs, the white/green edges should be visible if there is enough region left in the viewfinder to render based on width and the qrbox size configured.

Also, since looking for logs in mobile devices is harder, I was thinking if I should add a debug option which somehow makes more logs / error visible.

What do you think?
