### ISSUE TITLE
Improper case for qrbox variable in react example

### ISSUE THREAD

**Issue by kzha0** [mebjas/html5-qrcode#266]
**Describe the bug**
I copied the code that loads the QR scanner from the react example, but the QR box wasn't showing up.  This is a part of the code from the example:

        function createConfig(props) {
          var config = {};
          if (props.fps) {
            config.fps = props.fps;
          }
          if (props.qrBox) {
            config.qrBox = props.qrBox;
          }
          if (props.aspectRatio) {
            config.aspectRatio = props.aspectRatio;
          }
          if (props.disableFlip !== undefined) {
            config.disableFlip = props.disableFlip;
          }
          return config;
        }

When I tried changing the case of the variable that controls the QR box size from `qrBox` to `qrbox`, the QR box showed up. After some digging, I found that this is due to improper case as currently, the library only accepts the `qrcode` variable for the configuration object.

I believe this issue is significant to react users who would like to have a qr code scanner widget without going through all the docs just by simply copying the code from the example. However, I might also be missing something where the authors are planning to change the case of the said variable in the future.

**Comment by mebjas** [comment]
thanks for reporting this @kzha0 - please feel free to send a PR if you are interested. Alternatively I'll make the fix.

thanks!

**Comment by kzha0** [comment]
#271 #

**Comment by mebjas** [comment]
Fixed with https://github.com/mebjas/html5-qrcode/pull/271
