### ISSUE TITLE
Checksums?

### ISSUE THREAD

**Issue by uncovery** [mebjas/html5-qrcode#269]
Hi, I tried another JS QR code library and that would sometimes return faulty text (one letter different etc), so I wanted to know if this one has a checksum functionality included or not.

thanks!.

**Comment by ROBERT-MCDOWELL** [comment]
it's an interesting idea indeed, here a nice link of javascript hash and checksum
https://codepen.io/ImagineProgramming/post/checksum-algorithms-in-javascript-checksum-js-engine
patch welcome!

**Comment by ROBERT-MCDOWELL** [comment]
The problem being that checksum is done first on the correct data, but how to guess a correct data from a barcode never sacnned?

**Comment by mebjas** [comment]
> The problem being that checksum is done first on the correct data, but how to guess a correct data from a barcode never sacnned?

+1, closing this as infeasible.
