### ISSUE TITLE
CODE_39 seems like unsupported

### ISSUE THREAD

**Issue by vikashhd** [mebjas/html5-qrcode#274]
We are not able to scan Code_39 bar code. We need immediate support.

**Comment by denguyen-tvit** [comment]
Hi @vikashhd  
Code_39 has already support, please detail your testing case, and upload the barcode that you are testing.

**Comment by mebjas** [comment]
Closing for now, @vikashhd - if this issue persists, please reopen (or comment on existing issues on CODE 39)
