### ISSUE TITLE
How to set QRBOX dimensions (height and width)

### ISSUE THREAD

**Issue by mbhardwaj27** [mebjas/html5-qrcode#278]
There is no option to set the **_height and the width_** for the qr-box. I have to set the dimensions for the qr-box for my bar code scanning app.

**Comment by mbhardwaj27** [comment]
Any solution for this?

**Comment by mebjas** [comment]
This sounds reasonable, looking into this.

**Comment by benaloui** [comment]
> There is no option to set the **_height and the width_** for the qr-box. I have to set the dimensions for the qr-box for my bar code scanning app.

I have the same needs. It's better to change the height and the width when the app try to read a barcode.

**Comment by benaloui** [comment]
> 
> 
> This sounds reasonable, looking into this.

Do you find any issue ?

**Comment by benaloui** [comment]
@mebjas hi dude, do you think that we can hope to obtain any solution for resezing barcode dimension on a soon version ? I'm really need this solution in few days.
Thank you for you answer.
Kind regards

**Comment by mebjas** [comment]
Published with `version 2.0.13` - https://github.com/mebjas/html5-qrcode/releases/tag/v2.0.13

(on Github as well as npm)

**Comment by CodingWithTashi** [comment]
Just what I need, Great package!

**Comment by RakeshBeni** [comment]
i want to adjust camera height and width . how is it possible

**Comment by fyrus7** [comment]
The only resizing is the QR box inselft, not the area outside the scan box. The outside only can change width, changing height effect nothing.
