### ISSUE TITLE
lodash / underscore not working on pages with html5-qrcode added

### ISSUE THREAD

**Issue by joshbmarshall** [mebjas/html5-qrcode#284]
**Describe the bug**
Using html5-qrcode in a html5 application, any lodash calls like _.debounce fail with an unknown function error.

**To Reproduce**
1. Add html5-qrcode to a page that also has lodash
2. try to call _.debounce() function
3. See error in console

**Expected behavior**
Both lodash and html5-qrcode to co-exist

**Example**
See jsfiddle https://jsfiddle.net/joshmarshall/v51z90w8/7/

**Comment by mebjas** [comment]
@janfschmidt I tried to run the attached jsfiddle link, I can see the console error - but rest of the things seem to work fine. Can you confirm if there is issue beyond the error seen on console?

**Comment by joshbmarshall** [comment]
@mebjas the qrcode scanner keeps working BUT the lodash functions do not

**Comment by mebjas** [comment]
Working on a fix

**Comment by mebjas** [comment]
Can you try with latest version of the code - https://unpkg.com/html5-qrcode@2.1.0/html5-qrcode.min.js

^ I tried, seemed to work for me.

(I am still verifying different components and will update documentations later.)

**Comment by mebjas** [comment]
Thanks for confirming, closing
