### ISSUE TITLE
Broken script link in Vue.js section

### ISSUE THREAD

**Issue by Sighi-04** [mebjas/html5-qrcode#286]
The following link:
https://unpkg.com/html5-qrcode/minified/html5-qrcode.min.js
from the Vue.js section of the project currently returns a 404 and cannot be used.

**Comment by mebjas** [comment]
Thanks for pointing out, example updated.

**Comment by mebjas** [comment]
Fixed with https://github.com/mebjas/html5-qrcode/commit/12a04bb48cfbcbe4c2ca2a63652d405bdfd69c32

Please check again.

**Comment by Sighi-04** [comment]
> Fixed with [12a04bb](https://github.com/mebjas/html5-qrcode/commit/12a04bb48cfbcbe4c2ca2a63652d405bdfd69c32)
> 
> Please check again.

Thanks, just checked it and it works.
