### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'Html5Qrcode')

### ISSUE THREAD

**Issue by memiljamel** [mebjas/html5-qrcode#322]
Hi, I'm using React JS and getting this error message. Is it true that Html5Qrcode properties can't be read?. I just imported it and haven't done any code writing.

// I only imported the library and get error
`import Html5QrcodeScanner from 'html5-qrcode';`

how to fix it?

**Comment by mebjas** [comment]
Working on a fix.

**Comment by mebjas** [comment]
I have verified this to work with react, closing.
