### ISSUE TITLE
No dist folder anymore!?

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [mebjas/html5-qrcode#326]
Last git does not have the dist folder anymore. :-\

**Comment by ROBERT-MCDOWELL** [comment]
Since now I simply update from the last git and just take the minified JS.

**Comment by mebjas** [comment]
I see, I can add that process back.

**Comment by ROBERT-MCDOWELL** [comment]
agree, I just have a bad habit with git and updates ;)
