### ISSUE TITLE
Field-Test for compatibility (Mobile-Only)

### ISSUE THREAD

**Issue by OneDivZero** [mebjas/html5-qrcode#34]
Maybe we can keep this ticket running for continuous feedback.

**Keys:**
Cams: Num of cams
QR: Does QR-Scanning work?
File: Does File-Scanning work?
AS: AutoSelect back-camera (pattern-matching on label)
SC: Stream-Close after scan (currently a problem; TBR)

... AS is not relevant for your code-base, but I'll just copy and paste my test-table ... just ignore it

**Error-Cases:**
1) Just really nothings happens, even no camera-access-dialog
1) Unable to close the stream
3) VideoError, error = Error getting userMedia; error = NotReadableError: Could not start video source

**Symbols:**
✅  ... everything is fine
🔴  ... does not work as excpected
⚪  ... not yet checked
❓  ... not yet clear or missing feedback

**Comment by OneDivZero** [comment]
2020-05-03

![image](https://user-images.githubusercontent.com/1638511/80921170-fd15ab80-8d74-11ea-994d-955760ea481a.png)

**Comment by OneDivZero** [comment]
I can send you personally a link to my test-playground. I will not make this link publicly, cause I have a paid device-detection-solution running on it.

**Comment by mebjas** [comment]
This is pretty cool, @OneDivZero - I created a []() with https://github.com/mebjas/html5-qrcode/commit/c0cc7586a7a7878e8c4c0710adc41701302e3219

If you don't mind would you be interested in sending a pull request with devices you have already tested and in future send updates for if you test more. This would be very helpful for many who wouldn't have to do more exercise.

I'll also add devices I have tested.

**Comment by OneDivZero** [comment]
@mebjas cool! yes I can send a pull-request. I have an update on this topic too.

**Comment by mebjas** [comment]
Assigning it to you @OneDivZero - please close this issue once most of the list is ported.

**Comment by mebjas** [comment]
I am closing this as an issue for now, to cleanup list of issues to solve. Please feel free to send PR with devices you have tested so far - your contributions are highly appreciated!!
