### ISSUE TITLE
Compatibility - ANDROID CHROME- Camera goes black mostly on asus phones, with old and new versions.

### ISSUE THREAD

**Issue by IlhamriSKY** [mebjas/html5-qrcode#342]
**Describe the bug**
The camera turns black when opening the scan camera, chrome has been given access to the camera as well as the scan page. 
I tried your demo with the same device and it worked fine.

**Describe the browser:**
 - OS: [iOS, Android]
 - Browser [Chrome]

**Screenshots**
![scanblack](https://user-images.githubusercontent.com/18723904/139613300-ae96a524-4b92-45e8-8535-117b2f9f2e55.jpg)

**Additional context**
I am using Version 2.1.12 in laravel
This is how i use it

```javascript
    {!! HTML::script('assets/js/as/html5-qrcode.min.js') !!}
    <script>
        var url = '{{ route('entry.building.card', [ 'tokenbuliding']) }}';
        function docReady(fn) {
            // see if DOM is already available
            if (document.readyState === "complete"
                || document.readyState === "interactive") {
                // call on next available tick
                setTimeout(fn, 1);
            } else {
                document.addEventListener("DOMContentLoaded", fn);
            }
        }

        docReady(function () {
            var resultContainer = document.getElementById('qr-reader-results');
            var lastResult, countResults = 0;
            function onScanSuccess(decodedText, decodedResult) {
                if (decodedText !== lastResult) {
                    ++countResults;
                    lastResult = decodedText;
                    console.log(decodedText);
                    window.location.href = url.replace('tokenbuliding', decodedText);
                    html5QrcodeScanner.clear();
                }
            }

            var html5QrcodeScanner = new Html5QrcodeScanner(
                "qr-reader", { fps: 10, qrbox: {width: 250, height: 250}, aspectRatio: 1 });
            html5QrcodeScanner.render(onScanSuccess);
        });
    </script>
```

**Comment by braulio-balanza** [comment]
I am having the same issue with a client's Galaxy S10e using Chrome

**Comment by mebjas** [comment]
@braulio-balanza I tried on Google Chrome on Galaxy S10e on Browser stack and it seemed to work without exception. 

![image](https://user-images.githubusercontent.com/3007365/146753300-badbb535-5302-4333-b19c-0d44d49f4328.png)

Can you connect it with a PC and share if you see some useful logs or crash logs?

cc: @IlhamriSKY

**Comment by braulio-balanza** [comment]
Yeah, I have also tested on Samsung S10e, on Browser Stack and Lambda Test and it worked without exception as well. 

I do not have access to the device given that it is a remote client. 

One possibility that I can think of is that the device was in low battery mode and camera use was disabled, but I need to do further testing.

**Comment by mebjas** [comment]
Please reopen if this issue persists.
