### ISSUE TITLE
[Feature Request] Able to hide scan file image feature

### ISSUE THREAD

**Issue by lennoneo** [mebjas/html5-qrcode#351]
Hello mebjas,

i'm so grateful to be able to use this awesome product on my project, thank you for this.

I wish you can add feature to hide the scan image file link. i currently work on absence project in my office, in order to prevent the employee to use the absence-qr-code at home while they actually working from home.

I wish you can grant my wish.

Regards,
Dimas

**Comment by mebjas** [comment]
This sounds reasonable - I'll add support for this.

**Comment by MohmmadQunibi** [comment]
isn't this supposed to be supported in v2.2.0?
