### ISSUE TITLE
[Feature Request] Freeze the image (not clear) on success

### ISSUE THREAD

**Issue by aronchick** [mebjas/html5-qrcode#356]
Pretty low priority, but I'd love to freeze the image (not clear it) when the code is detected.

Is there any easy way to do this?

**Comment by mebjas** [comment]
not today, the `pause(..)` API could be extended to do this.

**Comment by mebjas** [comment]
To be added in version 2.1.4 with PR - https://github.com/mebjas/html5-qrcode/pull/365

**Comment by mebjas** [comment]
Implemented in `v2.1.4`

 - Github release: https://github.com/mebjas/html5-qrcode/releases/tag/v2.1.4
 - NPM: https://www.npmjs.com/package/html5-qrcode/v/2.1.4
