### ISSUE TITLE
Uncaught 'config.qrbox' dimensions values should not be greater than the width of the HTML element.

### ISSUE THREAD

**Issue by cungikawake** [mebjas/html5-qrcode#357]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mebjas** [comment]
What is the device display width and what is the value of `config.qrbox` in your example?

**Comment by mebjas** [comment]
@cungikawake gentle reminder to provide more context into this issue.

**Comment by mebjas** [comment]
I can reproduce this issue. So far it's an expected behavior.

Starting `v2.1.5` this shall be replaced with throwing a warning and truncating the `qrbox.width` to the size of the root element.
