### ISSUE TITLE
 Change camera with different cameraId in runtime?

### ISSUE THREAD

**Issue by kunambi** [mebjas/html5-qrcode#360]
Is it possible to change the camera during runtime? 

We currently start the camera by getting the `cameraId` from `#getCameras()` and then running `html5QrCode.start(cameraId, config)`. We also have a select dropdown which we populate with all cameras found. We would like to change which `cameraId` is being used in `html5QrCode` in real-time. 

Is it possible to do this?

**Comment by mebjas** [comment]
How about using

```js
html5qrcode.stop().then(_ => 
  html5qrcode.start(newCameraId, /** rest of the stuff */));
```

**Comment by kunambi** [comment]
Looks great! We will test this

**Comment by mebjas** [comment]
Please close this issue, if the workaround works for you.

**Comment by mebjas** [comment]
Closing assuming the workaround gets the work done.
