### ISSUE TITLE
Applied width of the scanner is "0"

### ISSUE THREAD

**Issue by ZhuanM** [mebjas/html5-qrcode#362]
**Describe the bug**
The behavior of applying the scanner width is confusing and most importantly incorrect. By trying to dynamically apply custom width to the scanner  (through JavaScript - due to responsive design reasons) I get mixed results. The first time I visualize the scanner I get the correct width that I've set. After stopping the scanner and start it again at later point in the code I get the default constant width which is "300" instead of the desired width of 700px that I've already set once at the beginning of my code. The reason being is that the element.clientWidth is "0" and it therefore gets the default width constant which is "300" and I get 300px of width on my scanner after setting it to 700px. I've tried using the `style` attribute of the scanner HTML element in order to set it to "700px" manually there but the result is the same regardless if I'm using JS to set it or the `style` attribute of the HTML element.

**To Reproduce**
I only set the width once based on the device's resolution and don't change the resolution whilst testing. I create the scanner using the `Html5Qrcode` class. I've set the width of the scanner HTML element to "700px" using JS or by using the `style` attribute of the scanner HTML element. I use the `start()` function to start the scanner -> the width is 700px as I've set it. I use the `stop()` function after successfully scanning a barcode. I use the `start()` function at a later point in the code to start the very same scanner object again -> element.clientWidth inside the `html5-qrcode.js` file is "0" and therefore it resorts to get the default width constant which is "300" -> my scanner HTML element is set to 300px instead of 700px.

**Expected behavior**
I expect to have consistency in the real width which I've set to my scanner HTML element and not resort to the default width of 300px.

**Screenshots**
This is the current official source code of the `html5-qrcode.js` inside the `esm` folder.
![github_issue](https://user-images.githubusercontent.com/26820098/145403997-a606df9d-392e-4509-b783-e4035094d8a1.png)

**_POOR_ Workaround**
This is my very poor but working workaround of this issue which gets the real set width of the scanner HTML element every time. The `rootElementWidth` variable is then replaced by the `realWidth` variable everywhere inside the file.
![github_issue_workaround](https://user-images.githubusercontent.com/26820098/145404042-63a4edb1-d94a-4f7b-9806-28515c516a07.png)

A possible solution is to simply not use `element.clientWidth` but rather a different property which is more accurate. I'm not personally informed on how exactly the `clientWidth` is generated but there seems to be information inside the `element` object which contains the accurate width that the developer has set.

**Additional context**
I'm using 2.1.3 version of the html5-qrcode library (installed via npm) alongside with Angular 11.

**Comment by mebjas** [comment]
Thanks for filing the bug and sharing such in depth information around it. I'm looking into this issue.

**Comment by mebjas** [comment]
@ZhuanM I need more help understanding the issue.

This is a possible repro of the issue you have stated - https://codepen.io/mebjas/pen/jOGwQrY?editors=1111 here I can `start()` and `stop()` many times without facing the issue.

**Comment by mebjas** [comment]
If I am understanding the issue wrong, please create an alternative codepen where I can repro this issue clearly.

**Comment by ZhuanM** [comment]
@mebjas I'm linking a CodeSandbox code since it allowed me to more easily integrate Angular and give a more realistic scenario of my personal use case and possibly the real issue.

Code:
https://codesandbox.io/s/serene-orla-cv5vl

Note:
In this case it turns out that even the first `start` it refuses to use the real set width. I've made it so that after a successful scan it will start scanning again after 2 seconds, but it's not necessary to focus on that since the issue is shown at the very first `start`. I've set the width by using the `width` HTML attribute (and even tried by using the `style` HTML attribute) and also by setting dynamically in the TypeScript file via the `scannerObserve()` function. You can remove either one so you have only one way of setting the width but the result is the same from what I've tested, regardless of which one you remove. I'm not sure if Angular itself has anything to do with the issue.

**Comment by mebjas** [comment]
Thanks for the example, I am able to repro this there. It's strange though as I haven't been able to repro this outside of angular example (same example as before - https://codepen.io/mebjas/pen/jOGwQrY?editors=1111). I can't help but wonder if there is something else at play here.

Need more debugging.
