### ISSUE TITLE
Error on start camera after cache is cleared

### ISSUE THREAD

**Issue by onuh** [mebjas/html5-qrcode#368]
When cache is cleared, the scanner displays error on attempt to scan with camera.

**Comment by mebjas** [comment]
what do you mean by cache is cleared?

**Comment by onuh** [comment]
When web browser cache is cleared, the scanner experiences error. On
Android Google chrome, view history and clear it. Or on Android APK, clear
app cache

**Comment by onuh** [comment]
Check out APK app here:
https://smartchurchattendance.com.ng/smartChurch/downloads/Smart_Church_Mobile_1_2.0.apk

**Comment by mebjas** [comment]
Can you share, what is the stack trace of the error in this case (in the console)?

**Comment by onuh** [comment]
NotReadableError: Could not start video source

**Comment by leocharrua** [comment]
Hello. I have the same error periodically in a PWA. 
Anyone has a clue?
![IMG-20211210-WA0055](https://user-images.githubusercontent.com/1721923/147248898-930da47b-6ff2-4b01-947d-76edaa5cc90e.jpg)

**Comment by mebjas** [comment]
I can reproduce this, the API seem to show error when run directly on the PWA. Need to check if there is a workaround or platform specific issue.

**Comment by onuh** [comment]
Ok thanks for this confirmation.

Regards.

**Comment by leocharrua** [comment]
Hello. Any news about this? I have a PWA in production and this error is very frustraiting for the user. Is there any work around or something?
Thanks

**Comment by leocharrua** [comment]
Hello. I think I could solve it. I had a error in a if condition when close the page and the "clear" part never run. Now:

```
 if (this.html5QrcodeScanner.getState() === Html5QrcodeScannerState.SCANNING) {
      this.html5QrcodeScanner.clear().then(async _ =>  { 
        ...

```
Doing the clear the error does not occur.

Thanks
