### ISSUE TITLE
[Feature Request] Expose start and stop interfaces for html5-qrcode

### ISSUE THREAD

**Issue by StenGruener** [mebjas/html5-qrcode#374]
**Is your feature request related to a problem? Please describe.**
In my project, I'd like to start and stop scanning from another component/callback, e.g., stop scanning when a qr code is detected.

**Describe the solution you'd like**
I'd like to see start and stop methods exposed in a public interface of html5-qrcode.

**Describe alternatives you've considered**
Currently, I hackaround simulating click events on buttons. I know, probably using the advanced component html5-qrcode-scanner would be the proper solution, however, it is not clear to me why start and stop are not exposed in the "beginner"-component as pause and resume are. 

Thanks for maintaning this component!

**Comment by mebjas** [comment]
> I'd like to see start and stop methods exposed in a public interface of html5-qrcode.

Do you mean with `Html5QrcodeScanner` - what do you expect will happen with `start()` and `stop()`?

**Comment by StenGruener** [comment]
yes i mean `Html5QrcodeScanner`. I expect the same behavious as clicking "start scanning" and "stop scannnig" buttons -> the video stream capture is stopped, and the "seracher ui" is also hidden.

**Comment by mebjas** [comment]
`Html5QrcodeScanner` is meant to be a e2e plugin with UI that can be used to easily integrate QR code scanning with success / error callbacks as response back to the client.

I am not sure how `start()` or `stop()` API will be used in this case, `render()` method is intended to render the whole UI and rest of the actions are automatically connected to users interaction with the plugin.

Ideally if you want a specific UI implementation, building on top of `Html5Qrcode` would be the best start with any kind of UI and interaction from client code.

`pause()` and `resume()` are other interaction mechanism purely for camera based scanning to give client more access to the viewfinder.

Can your usecase not be handled with these APIs?

**Comment by StenGruener** [comment]
okay, probably i will close the request
