### ISSUE TITLE
Camera stream is not showing.

### ISSUE THREAD

**Issue by raphcadiz** [mebjas/html5-qrcode#381]
**Describe the bug**
Camera stream is not showing.

**To Reproduce**
1. I have a sample link here https://tradieexpo.com.au/sample-page-2/
the camera stream is just showing white. I noticed it still scanned though

**Screenshots**
![1641348865288](https://user-images.githubusercontent.com/10813136/148150934-2ca1d756-930b-4462-a4da-bdc8b06bfe9b.JPEG)

**Smartphone (please complete the following information):**
 - Huawei P30 pro, Android 10

**Comment by mebjas** [comment]
The sample link is showing 404 error.

Meanwhile I tested using browser stack and it seemed to work just fine on Huawei P30, Android, Chrome. Can you check if scanapp.org is working fine for you?

**Comment by mebjas** [comment]
Please reopen if this issue still exists.
