### ISSUE TITLE
Compatibility - [Amazon Kindle] [Chrome] - [Doesn't scan barcodes]

### ISSUE THREAD

**Issue by vishakha-simply** [mebjas/html5-qrcode#388]
**Describe the bug**
Camera scanner not working on Amazon Kindle fire for scanning barcodes

**Describe the browser:**
Tried on Chrome

**Screenshots**
The camera scanner doesn't work at all, didn't scan anything for barcodes

**Comment by ROBERT-MCDOWELL** [comment]
are you sure your kindle has a builtin camera and give permissions to chrome to use it?

**Comment by vishakha-simply** [comment]
Oh, yeah it didn't ask for permission to use camera, but built-in camera is there

**Comment by ROBERT-MCDOWELL** [comment]
check if your kindle OS allow chrome to ask camera permissions.

**Comment by vishakha-simply** [comment]
I already checked in chrome browser and it allows camera access.
For the kindle OS, I turned on the settings to ask for permissions, it asked for permission in chrome but still didn't do anything

**Comment by ROBERT-MCDOWELL** [comment]
I think the issue come from the time permission is asked and camera ready. sometimes I see such kind of issue when the camera is slow to be ready.

**Comment by vishakha-simply** [comment]
Oh okay, is there anything that can be done ?

**Comment by ROBERT-MCDOWELL** [comment]
the best would be for developers to have a kindle on hands to test it. otherwise it will be only speculations

**Comment by vishakha-simply** [comment]
everything i use on kindle accesses camera fine, it just does not scan barcode for some reason

**Comment by zinglax** [comment]
I was having this issue and was going to post about it not working but I ended up getting it so scan bar codes for me.  I do have some experience with the different camera device settings in HTML5 and I did realized when I was opening the camera in Android Firefox the camera seemed to not be in auto-focus mode.  This makes it really tough to scan things, you have to be completely still, but with patience I did get it to scan a barcode.  On Android Chrome I had immediate success since it defaulted to an auto-focus mode.

**Comment by ROBERT-MCDOWELL** [comment]
@vishakha-simply 
did you check at https://scanapp.org/#reader if it works?

**Comment by mebjas** [comment]
@vishakha-simply Unfortunately this platform is not supported on browserstack so I cannot test and verify what is going on. Is there some stack trace you see on the browser alternatively what error does it show?

**Comment by vishakha-simply** [comment]
We decided to move to samsung tablets because of the kindle issues, thank you!
It works perfectly on samsung tab!
