### ISSUE TITLE
Initialize camera ZXing error! QR_CODE

### ISSUE THREAD

**Issue by flistonfr** [mebjas/html5-qrcode#390]
Hello!

I'm trying to initialize camera with default code from blog. 
![image](https://user-images.githubusercontent.com/94003074/149560857-6c93e3a2-54f9-47bb-98ad-b030b13d8514.png)

But when I open html I get this error:
![image](https://user-images.githubusercontent.com/94003074/149560720-50a47ca2-8e66-42dd-883d-41d3891601cd.png)

Can't figure out why!

Using version 2.1.6.

Thanks!

**Comment by samvandamme** [comment]
I'm having the same issue with html5QrCode when calling the start function:

```
TypeError: undefined is not an object (evaluating 'e.QR_CODE')
ZXingHtml5QrcodeDecoder — zxing-html5-qrcode-decoder.js:9
Html5QrcodeShim — code-decoder.js:54
Html5Qrcode — html5-qrcode.js:102:145
startCamera — 8e8738cb-e9ba-4355-b467-d057c55a9518:88
startCertainCameraButtonClicked — 8e8738cb-e9ba-4355-b467-d057c55a9518:63
invokeWithEvent — controller.ts:12
handleEvent — controller.ts:12
handleEvent — controller.ts:12
```

Any idea what's happening? I'm running `v2.2.8` and using Stimulus. Getting camera's is all fine.
