### ISSUE TITLE
[Feature Request] Resize video after QRCode Scanner has started

### ISSUE THREAD

**Issue by dieuminhs** [mebjas/html5-qrcode#393]
Hello!

I'm trying to find a way to resize my video (width: 100% and height: 100%) but I cant' find anyway to change its size since the video is not available before html5QrCode.start finished it business.
If there are others workaround, please let me now.

Thanks in advance.
Lancelot

Note: I want to resize the video and the qr-shaded-region with border resize corresponding to the video

**Comment by mebjas** [comment]
> I'm trying to find a way to resize my video (width: 100% and height: 100%)

Can you share screenshot of how the video shows up now and how you want it to be?

**Comment by dieuminhs** [comment]
> > I'm trying to find a way to resize my video (width: 100% and height: 100%)
> 
> Can you share screenshot of how the video shows up now and how you want it to be?

Thank you for your attention but I have solved it by using Javascript to change the width & height of the video to 100%, then I get the absolute width and height of the video and assign it to qr-shaded-region everytime the windows is resized

**Comment by fyrus7** [comment]
I know this is old, but can you share the adjustment? I try anything but only can resize the scan area not the the shade area, it keep 3:2 ratio on desktop and 2:3 ratio on mobile. still trying to set it to 1:1 ratio

**Comment by dieuminhs** [comment]
> I know this is old, but can you share the adjustment? I try anything but only can resize the scan area not the the shade area, it keep 3:2 ratio on desktop and 2:3 ratio on mobile. still trying to set it to 1:1 ratio

Unfortunately, I don't have the access to the code anymore. But my adjustment is based around the size of the windows and the video, my approach is to listen to the window resize event then change the shade area size (which is qr-shaded-region) accordingly. Good luck.
