### ISSUE TITLE
QRCODE IS NOT READING

### ISSUE THREAD

**Issue by ManeeshNandan** [mebjas/html5-qrcode#394]
While uploading QR code image. its not reading . 
![1](https://user-images.githubusercontent.com/12951827/150283731-7ba061f4-8e83-481f-83e7-11a485bf7f98.jpg)

**Comment by mebjas** [comment]
The code is too small, need to select a smaller image or have crop option to handle this if the image on itself is low resolution - but that feature is low priority.

Would the workaround of cropping it in gallery not work for you / users?
