### ISSUE TITLE
Uncaught cameraIdOrConfig is required

### ISSUE THREAD

**Issue by isia97** [mebjas/html5-qrcode#398]
Hi, I am using the end to end html2QrcodeScanner functionalities and it while it asks for camera permission as soon as it turns on it turns off and in console is this error "Uncaught cameraIdOrConfig is required". I also see some issues with cookies request, but since it's my first project like that I am not really sure if this is the reason.
I used the code given on the github, here it is. How can I solve this issue? 

![Zrzut ekranu 2022-01-23 180843](https://user-images.githubusercontent.com/98276334/150689675-fdd291d6-1063-42df-b05b-1d4f5c94aacf.png)
![Zrzut ekranu 2022-01-23 180651](https://user-images.githubusercontent.com/98276334/150689680-9476c894-bc9b-4fd4-96cf-eb12656d1513.png)
![Zrzut ekranu 2022-01-23 180629](https://user-images.githubusercontent.com/98276334/150689682-0ddc4d8d-a4c7-45a7-a8a5-ff6b74c78000.png)

**Comment by GustavoChiochetta** [comment]
This problem is happening on iPhone 11 in my application, does someone have a workaround for this??

**Comment by isia97** [comment]
It happens for me on PC Windows 10

**Comment by GustavoChiochetta** [comment]
is this happening on mobile devices for you as well?

**Comment by isia97** [comment]
On mobile it is showing NotAllowedError: Permission denied (Android)

**Comment by mebjas** [comment]
What library version, os, browser is this reproducible?

**Comment by GustavoChiochetta** [comment]
Hey, in my case it was actually a bug in my code, and in the way that I was getting the camera id, reading the documentation lead me to a better solution

**Comment by studioiyagi001** [comment]
Hi, I have a same error when executing my test file offline, but not happens when I move to html folder and execute from browser with localhost.
Seems it related to security issue? (https/localhost/others)

**Comment by cgewert** [comment]
I can confirm what @studioiyagi001 wrote: Using an HTTP Server the code works fine. When executing the script from a local file inside a browser the camera enumeration will contain found devices, but they won't have an ID and no label, which leads to the reported error.

**Comment by mebjas** [comment]
Thanks for responding. Looks like this is not a library issue.

**Comment by apoorv-me** [comment]
Few identified reasons so far:
1-Camera access only work for https and not http except for localhost or local server.
2- You cannot test this by opening the HTML file, it should be backed by a server

**Comment by nayanjyoti007** [comment]
Yes. Camera access work only https (Online Server) not your localhost
