### ISSUE TITLE
[Feature Request] Html5Qrcode cancel event to trigger stop

### ISSUE THREAD

**Issue by ubay25** [mebjas/html5-qrcode#399]
I am using the Html5Qrcode on my UI and using a click event to trigger the code below:
```
const html5QrCode = new Html5Qrcode("reader");
 const qrCodeSuccessCallback = (decodedText, decodedResult) => {
    alert(decodedText);
 };
 const config = { fps: 10, qrbox: { width: 250, height: 250 } };
 html5QrCode.start({ facingMode: "environment" }, config, qrCodeSuccessCallback);
```
While the camera/scanning is active, is there a way to call the stop function using a click event (i.e. Cancel button)?

**Comment by mebjas** [comment]
Wouldn't `stop()` or `pause()` help with this usecase?

reference: https://github.com/mebjas/html5-qrcode#documentation

**Comment by ubay25** [comment]
@mebjas sorry I missed that one. Thanks for replying though, amazing library! Great addition to my project.
