### ISSUE TITLE
[Feature Request] Add support to Upload picture

### ISSUE THREAD

**Issue by ChandraOrbit** [mebjas/html5-qrcode#4]
there is one request if possible.
can it be added to upload the image. so do not just rely on camera only but can to do scanning in the form of picture

**Comment by mebjas** [comment]
@ChandraOrbit I know it's too late but would like to take this up

**Comment by mebjas** [comment]
This one to be taken up if more request comes up.

**Comment by mebjas** [comment]
Add support for using `<input>` which can be used directly by cameras in the modern smartphones.

Some reference
 - https://developers.google.com/web/fundamentals/media/capturing-images
 - https://developers.google.com/web/fundamentals/media/recording-video

**Comment by mebjas** [comment]
Pull request sent - https://github.com/mebjas/html5-qrcode/pull/24

**Comment by mebjas** [comment]
Feature added, closing.
