### ISSUE TITLE
[Feature Request] Add SCAN_TYPE option int the config constructor

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [mebjas/html5-qrcode#405]
**Is your feature request related to a problem? Please describe.**
If the user has a sudden camera hardware problem so let's build the html5-qrcode scanner with the SCAN_FILE option only
and hide the switch file<->camera link

**Describe the solution you'd like**
Add in the constructor config option "scanType:[file,scanner,all]"
Add which scanner type to build the first time.

**Comment by mohsinaav** [comment]
Hi,
I will try to add this feature request.

Thanks.

**Comment by ROBERT-MCDOWELL** [comment]
Great! thanks
