### ISSUE TITLE
html5-qrcode on webview

### ISSUE THREAD

**Issue by mawaki** [mebjas/html5-qrcode#414]
Everything works well when I use html5-qrcode on the browser. I used WebView to package the web app for android, but I get the following error when I try to request camera permission.

NotAllowedError : Permission denied

I tried adding custom features to enable camera, but it did not work.

Thanks for your consideration.

**Comment by sarmuni** [comment]
I'm experiencing the same thing, can anyone please provide a solution, thank you.

**Comment by mawaki** [comment]
@sarmuni Check this solution:
https://stackoverflow.com/questions/61495505/android-webcam-error-in-webview-camera-permission-not-working

**Comment by sarmuni** [comment]
@mawaki Thanks for the advice, I'll try it out..

**Comment by ChristopherMora** [comment]
Mawaki pudiste revolver tu problema con la cámara ?

**Comment by ChristopherMora** [comment]
Yo tengo el mismo error al momento de usarlo en una web view me dice el mensaje de los permisos y no me deja abrir la cámara

**Comment by Macof08** [comment]
pudieron arreglarlo??? @ChristopherMora

**Comment by abifarhann** [comment]
Koyoe ga
