### ISSUE TITLE
Compatibility - Android Chrome - After granting permission the UI keeps showing 'Launching Camera' status even though I can see video rendered.

### ISSUE THREAD

**Issue by amitnjha** [mebjas/html5-qrcode#422]
**Describe the bug**
Compatibility - Android Chrome - After granting permission the UI keeps showing 'Launching Camera' status even though I can see video rendered. This also prevents from barcode being captured.
The same app works fine in desktops. I can see this issue only in Chrome in Android phones. iOS works fine.

**Describe the browser:**
 - OS: iOS, Android
 - Browser Chrome
 - Version [98.0.4758.87]

**Screenshots**
![Screenshot_20220214-162125](https://user-images.githubusercontent.com/1175344/153961097-5e08f0e4-d5b3-415b-a716-a33071b59aae.jpg)

**Additional context**

**Comment by amitnjha** [comment]
Closing.. It got resolved after for CSS changes.

**Comment by khurrammhd** [comment]
> Closing.. It got resolved after for CSS changes.

What CSS changes were required?

**Comment by sPRajapati** [comment]
What CSS changes are required...pls help..stuck here
