### ISSUE TITLE
Support for VIN bar codes (code_39_vin)

### ISSUE THREAD

**Issue by codainsw** [mebjas/html5-qrcode#424]
Can you please add support for automotive VIN barcode detection?
VIN barcodes, while similar to code 39,  seem to be a unique format type (code 39 vin), and I have not been able to get any to scan.

Thank you!

examples:
![image](https://user-images.githubusercontent.com/58780050/154557191-de08f9c2-4df3-4181-9e21-5eb0f256a6bc.png)

![image](https://user-images.githubusercontent.com/58780050/154557305-6c4e51e0-4200-4cd5-9bd3-4cbaae759a5a.png)

**Comment by waynebloss** [comment]
Is this feature available? I could not get it to work on the attached images.
