### ISSUE TITLE
Html5-QRCodescanner for attendance system using database

### ISSUE THREAD

**Issue by opl-git** [mebjas/html5-qrcode#427]
Hello, thank you for your awesome project.
First I want to say sorry for asking those very basic questions, but I am new to coding in JavaScript, I normally write in PHP. 

I'd like to use this library for my school as attendance system.
My idea is: every student owns a qr code
The teacher scans the code with his mobile device. After collecting all codes, the decoded values (name of each student) are written into a database.
I have two problems with that:

1: Can I collect a list of all decoded values?
My idea is that scanning, collecting and than writing the values into the database is much faster than doing this process for every student individually.
2. How can I pass those values to PHP, which I use to write the values into my database? 
Thank you in advance for your help! 

Kind regards
Dan

**Comment by mebjas** [comment]
Hi, @opl-git thanks for using the library.

For the question, I suppose this is not a question meant for github issue (meant for feature request or filing issues as maintainers have to spend time triaging the issues) - would you mind filing a stackoverflow question for this and maybe paste a link to that here for my visibility. I'll try to address your question there.

There is additional benefit of asking in stackoverflow - more folks with similar question can find and have resolution to the issue.

(please close this ticket afterwards).

**Comment by opl-git** [comment]
@mebjas Thank you for your answer.
Here is my stackoverflow link: https://stackoverflow.com/questions/71184597/html5-qrcodescanner-for-attendance-system
