### ISSUE TITLE
Button to start scanner and output value to an input text

### ISSUE THREAD

**Issue by 0x10101** [mebjas/html5-qrcode#428]
Hi guys, Im a beginner in web dev and would like to start scan on a button and then after code scan return value to an input text field.

I have tried many things but cant figure out.
The way is this
Inside webpage would be a button which when pressed will start the scann (maybe a modal box or whatever and onSuccess closes itself and output the value to an input text field into webpage.

Any help or example would be appreciated

**Comment by marcoris** [comment]
@0x10101 that is not an issue of the tool. You are just asking some questions because of your missing skills.
