### ISSUE TITLE
Listen to the stop scanning method on Html5QrcodeScanner

### ISSUE THREAD

**Issue by jahnavi310** [mebjas/html5-qrcode#445]
Hi there,

I am trying to implement a custom UI interface, I have a stop button with a click method in an ionic app which essentially calls the following function:

```
  stopScanner() {
    
    const html5QrCode = new Html5Qrcode('reader');
    html5QrCode
      .stop()
      .then(ignore => {
        // QR Code scanning is stopped.
      })
      .catch(err => {
        // Stop failed, handle it.
      });

  }
```

But when clicking on that button i get the following error message in the console:
Cannot stop, scanner is not running or paused.

Any idea what i could be doing wrong here?

Thanks in advance!

**Comment by jahnavi310** [comment]
Resolved, just needed to instansiate the scanner object at a higher level

**Comment by HaroldObasi** [comment]
hey @jahnavi310, please what do you mean by "Instansiate at a higher level"
