### ISSUE TITLE
'cameraIdOrConfig' object should have exactly 1 key, if passed as an object, found 2 keys

### ISSUE THREAD

**Issue by hktalent** [mebjas/html5-qrcode#446]
<img width="916" alt="image" src="https://user-images.githubusercontent.com/18223385/159116481-514e71d1-6cbb-401f-9e2a-20db68a04f57.png">

Unhandled Promise Rejection: Error getting userMedia, error = OverconstrainedError: Invalid constraint
<img width="652" alt="image" src="https://user-images.githubusercontent.com/18223385/159116701-810e3933-8988-4052-8f9d-5206a9828dc4.png">

In fact, I have initialized the video object with other components

test url
https://51pwn.com/:xxx

code
```
if(localVvId)
					{
						qWBox = $("#" + localVvId)
						html5QrcodeScanner = new Html5Qrcode(localVvId);
						var qb = { width: parseInt(qWBox.width()) || 250, height: parseInt(qWBox.height()) || 250 }
						var config = { fps: 10, qrbox: qb };
					
						html5QrcodeScanner.start({ deviceId: { exact: localVvId} ,facingMode: "environment" }, config, onScanSuccess);
						alert("init " + qb.width + ", " + qb.height)
					}
```

**Comment by bombayng** [comment]
This means you only need to configure deviceId or facingMode not both.

**Comment by hktalent** [comment]
need to configure deviceId 
thanks
