### ISSUE TITLE
[Feature Request] Could you please add CSS classes to the buttons

### ISSUE THREAD

**Issue by picocodes** [mebjas/html5-qrcode#447]
Specifically the Close Button.

**Comment by ROBERT-MCDOWELL** [comment]
you can contribute to it thanks

**Comment by mebjas** [comment]
Good idea, will be tracked at https://github.com/mebjas/html5-qrcode/issues/389

Marking this as a duplicate of https://github.com/mebjas/html5-qrcode/issues/389

Let's have more discussion there.
