### ISSUE TITLE
Option to pause scanning upon successful scan to avoid double ajax posts requests

### ISSUE THREAD

**Issue by larabarb** [mebjas/html5-qrcode#448]
**Is your feature request related to a problem? Please describe.**
Yes

**Describe the solution you'd like**
Option when using qr reader to post data, to pause the reader upon successful post request.

**Describe alternatives you've considered**
Dont know

**Additional context**
Option so Upon successful scan request the reader to stop scanning

**Comment by ROBERT-MCDOWELL** [comment]
create a boolean and compare it with the previous scan. if it's the same qr-code so bypass the result

**Comment by larabarb** [comment]
> create a boolean and compare it with the previous scan. if it's the same qr-code so bypass the result

Hey man, really thanks for your advice. Honestly i know nothing about js so i have no idea how to do it. i will keep on searching around for solutions. Thats why i said that this function could be just a parameter setting. 
For instance like the settings of fps aspect ratio etc. 

Anyway thanks a lot and if you could point me links that could help me achieve it that would be great. 

Thanks and take care.

**Comment by larabarb** [comment]
> 

Hey man sorry for bothering again for this but i think eventually that this is already designed....check this please:

https://blog.minhazav.dev/research/html5-qrcode
see this:
[4] Optional - Stop scanning after the code is scanned?

so i just added this:
html5QrcodeScanner.clear();
after my http post and it looks like its working fine.

**Comment by YTKowshik** [comment]
We are using something like the below to stop. 
`function StopQR() {
    html5QrCode.stop().then((ignore) => {
        // QR Code scanning is stopped.
    }).catch((err) => {
        // Stop failed, handle it.
    });
}`
After calling this we use `html5QrCode.clear();`.
We did that because camera sessions were open even after using clear.

**Comment by larabarb** [comment]
> We are using something like the below to stop. `function StopQR() { html5QrCode.stop().then((ignore) => { // QR Code scanning is stopped. }).catch((err) => { // Stop failed, handle it. }); }` After calling this we use `html5QrCode.clear();`. We did that because camera sessions were open even after using clear.

Thanks man.! Thanks a lot. 
Take care

**Comment by Guizboule** [comment]
You can use the method **_pause_**

```js
let shouldPauseVideo = true;
let showPausedBanner = false;
html5QrcodeScanner.pause(shouldPauseVideo, showPausedBanner);
```

**Comment by wadih** [comment]
To add to Guizboule's answer, then next step is the resume method:

```
html5Qrcode.resume()
```

https://scanapp.org/html5-qrcode-docs/docs/apis/classes/Html5Qrcode#resume
