### ISSUE TITLE
Qr code not recognised by the camera but recognised by the laser reader

### ISSUE THREAD

**Issue by nolup** [mebjas/html5-qrcode#458]
I use several label printers of different brands to print Qr codes.

I have no problem with almost all printers, but with TOSHIBA TEC printer yes. When it prints the Qr codes the smart phone's camera does not recognise them, but the laser readers do.

Does anyone know where the problem might lie?

I don't think it's a particular problem with the library as I can't read the codes with google lens or other applications either.

Below I include images of the problematic qr code.

https://drive.google.com/file/d/1ZNEM9BqYs9KRLLu4lwqjBZUp4F2tPfCJ/view?usp=sharing

https://drive.google.com/file/d/1QMrF4ZxGPjJHRncgbD8n2Jvyzu-EUiBo/view?usp=sharing

this should be the value of the qr: CC927E1070

Thanks.

**Comment by ROBERT-MCDOWELL** [comment]
this qr code looks very small, if it's under 2cm so this issue is already reported. it has a link with focus

**Comment by mebjas** [comment]
QR Codes look problematic, cannot decode.
