### ISSUE TITLE
Camera focus not working on some browsers

### ISSUE THREAD

**Issue by antonyf** [mebjas/html5-qrcode#464]
I have a working PWA using this html5 qrcode reader. What some clients are complaining about is the the camera does not focus

I researched some stuff and found a pollyfill for image capture which captures the stream and enables some advanced features like zoom and focus.. Could one not impliment something to the code to get a focus button for crappy phones?

**Comment by mebjas** [comment]
Duplicate of https://github.com/mebjas/html5-qrcode/issues/145.

Please track here directly.
