### ISSUE TITLE
Not ReadableError: could not start video source when switching from qrcode scanner to get usermedia

### ISSUE THREAD

**Issue by antonyf** [mebjas/html5-qrcode#466]
After scanning i stop the qrcode reader with html5Qrcode.stop().then(function(){
html5Qrcode.clear().then(function(){
go my my next step.. where i call getusermedia() to take a photo of the qrcode.. And then on some devices i get this error as per titile..
})
})

**To Reproduce**
scan a code stop and/or clear and then in the next step take a photo with samsung phone using getusermedia

**Comment by d3thomas** [comment]
I have the same issue. 

It only happens on mobile Chrome browsers (tested on Samsung Galaxy Note 20 Ultra,  S20 and Iphone 6)
Opening the productScanner results in an error with the message: `Not ReadableError: could not start video source when switching from qrcode scanner to get usermedia`

Also tested Firefox on Samsung > worked and Safari on Iphone > also worked.

Code to reproduce:

```
  const productScanner = new Html5Qrcode("reader", {
    experimentalFeatures: {
      useBarCodeDetectorIfSupported: true,
    },
  });
  productScanner
    .start(
      { facingMode: { exact: "environment" } },
      {
        fps: 10, // Optional, frame per seconds for qr code scanning
        qrbox: { width: 250, height: 250 }, // Optional, if you want bounded box UI
      },
      (decodedText, decodedResult) => {
        // do something when code is read
        console.log(`Code matched = ${decodedText}`, decodedResult);
      },
      (errorMessage) => {
        // parse error, ignore it.
      }
    )
    .catch((err) => {
      // Start failed, handle it.
      alert(err);
    });
```
