### ISSUE TITLE
Unable to scan qr codes with black background

### ISSUE THREAD

**Issue by StenGruener** [mebjas/html5-qrcode#468]
**Describe the bug**

**To Reproduce**
1. Go to: https://blog.minhazav.dev/research/html5-qrcode
2. Scan qr codes below
![image](https://user-images.githubusercontent.com/69786685/165891635-73e986d1-2a01-4e85-9bc1-5802a6876095.png)

**Expected behavior**
Right code should be scanned

**Smartphone (please complete the following information):**
 - Device: iphone 12
 - OS:  iOS15.4
 - Browser Safari

**Comment by StenGruener** [comment]
bump

**Comment by kbrawanski** [comment]
bump

**Comment by blacklionmedia** [comment]
bump

**Comment by mebjas** [comment]
planning to look into this - please track the parent issue (of which this is dup)

https://github.com/mebjas/html5-qrcode/issues/94
