### ISSUE TITLE
Compatibility - [OS] [Browser] - camera permissions break on iOS homescreen bookmark / pwa

### ISSUE THREAD

**Issue by machinaeXphilip** [mebjas/html5-qrcode#470]
- when I add a page using html5-qrcode to the homescreen, the camera permissions stop working.
- reproducable with scanapp.org > add to homescreen: leads to "Unable to query supported devices, unkown error".
- using it in safari without adding to homescreen works as expected

**Describe the browser:**
 - OS: iOS
 - Browser: safari / homescreen
 - Version iOS 12.55

**Screenshots**
see [this issue](https://github.com/mebjas/html5-qrcode/issues/349) for screenshots.

**Comment by myleftshoe** [comment]
Works on latest iOS 15.4.1 - PWA added to homescreen. Backwards compatibility issue.

**Comment by machinaeXphilip** [comment]
thanks. the phone i tested on is an 5 which stops at iOS 12.something.

could get it to work on another test device with ios 15.x

**Comment by convurt** [comment]
I am having issues on an iOS PWA as well.  It was working, and recently is has stopped.  Works great on the same phone directly in Safari and Chrome.  But when running on a page as a PWA, it ask for permissions, although never shows the camera.  I cant find any errors, I am questioning if the service worker is somehow breaking things?  Or the order of how the javascript is loading?  
![IMG_3172](https://user-images.githubusercontent.com/98235957/218142107-87ca3d8a-e8ae-43ee-a7e5-0abe20d2fbdf.PNG)
![IMG_3171](https://user-images.githubusercontent.com/98235957/218142109-c9789b92-5835-465e-acd0-fb283d16ef4d.jpg)
