### ISSUE TITLE
How to use html5-qrcode inside modal

### ISSUE THREAD

**Issue by mleister97** [mebjas/html5-qrcode#476]
**Describe the bug**
When using the root div, where the element should get mounted `<div id="reader" />`, parts are missing (e.g. the div `qr-shaded-region` is not even generated) and the configured sizes are not used at all.

I tried Bootstrap and Bulma CSS dependencies for testing different modals.

**To Reproduce**
Please see the following link: https://codesandbox.io/s/purple-bush-rw1ozi

**Expected behavior**
Normal use of the html5-qrcode reader should be possible

**Screenshots**
As you can see, the `qr-shaded-region` is missing. This is not the only bug when using in combination with a modal, tough.
![image](https://user-images.githubusercontent.com/16700053/167592715-7ef3547e-4bbb-4b0e-8ef0-1b62a3af9ab9.png)

**Comment by mleister97** [comment]
I would expect the following output:

![image](https://user-images.githubusercontent.com/16700053/167594068-fb5c4c65-9094-44d5-93c6-6eac2fe3d059.png)

**Comment by mapic100** [comment]
.......
  html5QrCode = new Html5Qrcode("reader");

  setTimeout(function () {
     html5QrCode
        .start({ facingMode: "environment" }, config, qrCodeSuccessCallback)
        .catch(function () {
          console.error("Error!");
        });
    }, 2000);
......

**Comment by mleister97** [comment]
Simply wait for the next tick after the DOM element (in my case the modal) is rendered. Can be done by using a `setTimeout(function () {` with `1` - `10` milliseconds.

**Comment by razorrazor** [comment]
I have a problem open an instance of html5qrcode inside a bootstrap modal window. If modal is opened and the screen resizes (for example, when you put your smartphone in landscape from portrait or viceversa) the modal suddenly closes and everything is gone (scanning stopped, no screen messages, ...).

Anybody with the same problem? Any idea to work around?

**Comment by razorrazor** [comment]
Problem solved!
The problem was that I tried to resize the qrbox attending to screen orientation, and the modal was autoclosing when I called the `html5Qrcode.start` after `html5Qrcode.stop`.
In order to adapt the qrbox size to screen orientation, I got inspiration from the following guide: _[](https://scanapp.org/blog/2022/01/09/setting-dynamic-qr-box-size-in-html5-qrcode.html)_.
