### ISSUE TITLE
[Feature Request] Please allow http to scan qr for local development

### ISSUE THREAD

**Issue by DBunthai** [mebjas/html5-qrcode#481]
**Is your feature request related to a problem? Please describe.**

When I do the local development I use an iPhone to scan the QR with the same network (Angluar Local).
I use a specific local IP to access Angular 172.20.10.4.
However, it has been restricted allow only https and localhost

**Comment by ROBERT-MCDOWELL** [comment]
this is a web browser restrictiion, nothing to do with html5-qrcode project.

**Comment by DBunthai** [comment]
It's from the code or browser?
https://github.com/mebjas/html5-qrcode/blob/master/src/html5-qrcode.ts#L746-L758

**Comment by ROBERT-MCDOWELL** [comment]
https -> browser
