### ISSUE TITLE
Error getting userMedia, error = NotReadableError:Could not start video source

### ISSUE THREAD

**Issue by mpn7** [mebjas/html5-qrcode#483]
**Describe the bug**
I think this is the same error as reported in #38. In my samsung S7 running android 8 this error appears when I execute `start()` quickly after `getCameras()`. The same does not happen in my oneplus 6 running android 11.

I call `getCameras()` only to ask permission. I don't use the cameraID's, if there's a better way to ask permission I would appreciate.

**To Reproduce**
Run `getCameras()` and `start()` in quick sucession in a low end android phone

**Desktop (please complete the following information):**
 - OS: Android
 - Browser: Chrome

**Smartphone (please complete the following information):**
 - Device: Samsung S7
 - OS: Android 8
 - Browser Chrome

**Comment by ROBERT-MCDOWELL** [comment]
you certainly have an Android or Browser restriction somewhere. try to see on your Android settings if Chrome is allowed to use your camera

**Comment by mpn7** [comment]
The camera works when I remove `getCameras()`. But I need to call it because it's the only way to ask permission to use the camera. If the user already gave permission without calling `getCameras()` it works fine

**Comment by ROBERT-MCDOWELL** [comment]
maybe there is something wrong with your samsung phone. it takes maybe more time for the camera to get initialized.
try another phone to see if it's the same. It would be interesting to update the project code with a promise() as camera and audio are mechanic stuff

**Comment by mpn7** [comment]
My config is like this:

`const config = { fps: 10, qrbox: { width: 250, height: 250 }, aspectRatio: 1, focusMode:"continuous"};`

It's still not working.

**Comment by mpn7** [comment]
I changed the config to this:
```
const formatsToSupport = [
        Html5QrcodeSupportedFormats.QR_CODE,
        Html5QrcodeSupportedFormats.UPC_A,
        Html5QrcodeSupportedFormats.UPC_E,
        Html5QrcodeSupportedFormats.UPC_EAN_EXTENSION,
];
const config = { fps: 10, qrbox: { width: 250, height: 250 }, aspectRatio: 1, focusMode:"continuous",formatsToSupport:formatsToSupport,advanced:[{zoom: 1.5}],experimentalFeatures:{useBarCodeDetectorIfSupported:true}};
```

This error happens on camera start, so I can't even scan any QR codes. The camera doesn't appear.


I'll leave the whole code here:

```

html5QrCode = new Html5Qrcode("reader");
    Html5Qrcode.getCameras().then(devices => {
        //ask permissions
    }).catch(err => {
        alert(err);
    });
	const qrCodeSuccessCallback = (decodedText, decodedResult) => {
	
        //do stuff
	};
    const formatsToSupport = [
        Html5QrcodeSupportedFormats.QR_CODE,
        Html5QrcodeSupportedFormats.UPC_A,
        Html5QrcodeSupportedFormats.UPC_E,
        Html5QrcodeSupportedFormats.UPC_EAN_EXTENSION,
      ];
	const config = { fps: 10, qrbox: { width: 250, height: 250 }, aspectRatio: 1, focusMode:"continuous",formatsToSupport:formatsToSupport,advanced:[{zoom: 1.5}],experimentalFeatures:{useBarCodeDetectorIfSupported:true}};
	
	// If you want to prefer Back camera
	html5QrCode.start({ facingMode: "environment" }, config, qrCodeSuccessCallback).catch(err => {
        alert(err);
    });

```

**Comment by ROBERT-MCDOWELL** [comment]
html5QrCode.start(<CAMERA ID>, config, qrCodeSuccessCallback).catch(err => ....

**Comment by ROBERT-MCDOWELL** [comment]
{ facingMode: "environment" } must be  in the config, then choose the camera ID of your back camera.

**Comment by mpn7** [comment]
It's working now! Thank you very much Robert.

**Comment by Yyuanbo** [comment]
I ran into the same problem, but still failed with the above configuration，
Error getting userMedia, error = NotReadableError:Could not start video source
**Smartphone：**
Device: IQOO Z5
OS: Android 11
Browser Wechat
I'll leave the whole code here:
```
this.html5QrCode.start(
              this.cameraId,
              {
                fps: 10,
                qrbox: 250, 
                facingMode: "environment",
                aspectRatio: 1.777778, 
                focusMode:"continuous",
                formatsToSupport:[
                  Html5QrcodeSupportedFormats.QR_CODE,
                  Html5QrcodeSupportedFormats.UPC_A,
                  Html5QrcodeSupportedFormats.UPC_E,
                  Html5QrcodeSupportedFormats.UPC_EAN_EXTENSION,
                ],
                advanced:[
                  {zoom: 1.5},
                ],
                experimentalFeatures:{
                  useBarCodeDetectorIfSupported:true,
                }
            },
            qrCodeMessage => {},
            errorMessage => {}
	).catch(err => {
	// Start failed, handle it. 
})
```
