### ISSUE TITLE
[Feature Request] Faster QR Code recognition??

### ISSUE THREAD

**Issue by emkowale** [mebjas/html5-qrcode#485]
I developed a cool inventory management app with this software. It dips our database and looks stuff up. It works great. My question... I'm using an iPhone. There is an app for iPhone called "QR Reader". If I open that app and get a qr code anywhere in the camera viewfinder (even outside of the square target) it scans. Even if it's crooked or on an angle! Html5-qrcode works great and I'm very grateful for it, but I have to line it up just right and have to be still and parallel to the label. I've just become use to the "practice" of using it. Please educate me on why "QR Reader" scans faster. Am I missing something?

**Comment by ROBERT-MCDOWELL** [comment]
you are not missing anything, html5-qrcode needs for now right alignment as the algorithm in JS does not (yet) support scanning from any angle.... but maybe I'm wrong and someone has a PR on this subject.

**Comment by emkowale** [comment]
The versatility of JS is pretty amazing as opposed to creating an apple app and being under their clutches. Hopefully someone will answer with some further insight to the angle scanning. Thanks for your reply.

**Comment by emkowale** [comment]
I guess I don't know what you mean by that. Please clarify.

**Comment by ROBERT-MCDOWELL** [comment]
share your code that create the html5-qrcode object

**Comment by emkowale** [comment]
//**************************************************************************************************************************
	// Updated by Eric on 3-19-21 AD
	//**************************************************************************************************************************
	function startScanning() {

		// This method will trigger user permissions
		Html5Qrcode.getCameras().then(cameras => {
			const formatsToSupport = [
				Html5QrcodeSupportedFormats.QR_CODE,
				Html5QrcodeSupportedFormats.UPC_A,
				Html5QrcodeSupportedFormats.UPC_E,
				Html5QrcodeSupportedFormats.UPC_EAN_EXTENSION,
			];

			const config = {
				fps: 30,
				qrbox: 150,
				rememberLastUsedCamera: true,
				aspectRatio: 1,
				experimentalFeatures: {
					useBarCodeDetectorIfSupported: false
				},
				formatsToSupport: formatsToSupport
			};

			const cameraMode = {
				facingMode: "environment"
			};


			if (cameras && cameras.length) {
				var cameraId = cameras[0].id;

				// .. use this to start scanning.
				html5QrCode.start(
					cameraMode,
					config,
					qrCodeMessage => {
						stockitProcessQrCode(qrCodeMessage);
					},
					errorMessage => {
						// parse error, ignore it.
						//console.log("errorMessage="+errorMessage);
					}
				)
				.catch(err => {
					// Start failed, handle it.
					console.log("err1="+err);
				});
			}
		})
		.catch(err => {
			// handle err
			console.log("err2="+err);
		});

	}

**Comment by ROBERT-MCDOWELL** [comment]
try

```
		const config = {
			fps: 8,
			qrbox: 250,
                        disableFlip: false,
                        focusMode: "continuous",
                        advanced:[{zoom:isMobile.Android ? 1.5 : 2.0}],
			rememberLastUsedCamera: true,
			aspectRatio: 1,
			experimentalFeatures: {
				useBarCodeDetectorIfSupported: true
			},
			formatsToSupport: formatsToSupport
		};
```

**Comment by emkowale** [comment]
WOW. My initial testing shows pretty great improvement. I had to set the focus mode to 1. It looks like the extra parameters did it! thanks!
