### ISSUE TITLE
Qr Content Does Not Work

### ISSUE THREAD

**Issue by devmdeniz** [mebjas/html5-qrcode#491]
**Describe the bug**
Qr content cant work

**Screenshots**
https://imgur.com/awmgfaG

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Version [102.0.5005.115 (Official Build)]

**Additional context**
i use 
```html
<html>
<head>
    <title>asdas-Qrcode Demo</title>
<body>
    <div id="qr-reader" style="width:500px"></div>
    <div id="qr-reader-results"></div>
</body>
<script src="/html5-qrcode.min.js"></script>
<script>
    function docReady(fn) {
        // see if DOM is already available
        if (document.readyState === "complete"
            || document.readyState === "interactive") {
            // call on next available tick
            setTimeout(fn, 1);
        } else {
            document.addEventListener("DOMContentLoaded", fn);
        }
    }

    docReady(function () {
        var resultContainer = document.getElementById('qr-reader-results');
        var lastResult, countResults = 0;
        function onScanSuccess(decodedText, decodedResult) {
            if (decodedText !== lastResult) {
                ++countResults;
                lastResult = decodedText;
                // Handle on success condition with the decoded message.
                console.log(`Scan result ${decodedText}`, decodedResult);
            }
        }

        var html5QrcodeScanner = new Html5QrcodeScanner(
            "qr-reader", { fps: 10, qrbox: 250 });
        html5QrcodeScanner.render(onScanSuccess);
    });
</script>
</head>
</html>
```
[this code](https://github.com/mebjas/html5-qrcode/blob/master/examples/html5/index.html) but i cant see anything.
but;
if i use [this code](https://github.com/mebjas/html5-qrcode/tree/master/examples/html5#readme):
i can see camera (qr reader) section. i thing it is working because when i show the qr code, a border turns green but
Doesn't write qr content anywhere
(the content of the picture, does not working on me) https://imgur.com/4FcrOGp

=

[I can only see this right now.](https://imgur.com/LZhv0dR)
but when I read the qr code, I can't see the content of the qr code like https://imgur.com/4FcrOGp

**Comment by ROBERT-MCDOWELL** [comment]
please be more precise on your issue subject. (all contents? specific content? etc...)

**Comment by devmdeniz** [comment]
I think I couldn't set it up properly. QR reading and camera events are working properly. It cant print the readed data in the "qr-reader-results" part. That's my only problem (sorry I guess I couldn't explain)

**Comment by devmdeniz** [comment]
> what do you see as result? did you try with more QR codes?

i tried in [this](https://blog.minhazav.dev/research/html5-qrcode) website and the result like [this](https://imgur.com/4FcrOGp)

and i scroll down and see the document
I applied the document
When I try to run the code, it detects the Qr code and the frame turns green.
but it cannot print the content of the qr code to the div

**Comment by ROBERT-MCDOWELL** [comment]
what's in decodedText and decodedResult?

**Comment by devmdeniz** [comment]
Just can you explain how can i make it work
this code:
```javascript
<script src="https://unpkg.com/html5-qrcode"></script>

<div id="qr-reader" style="width:500px"></div>

<div id="qr-reader-results"></div>



<script>

    var resultContainer = document.getElementById('qr-reader-results');

var lastResult, countResults = 0;



function onScanSuccess(decodedText, decodedResult) {

    if (decodedText !== lastResult) {

        ++countResults;

        lastResult = decodedText;

        // Handle on success condition with the decoded message.

        console.log(`Scan result ${decodedText}`, decodedResult);

    }

}



var html5QrcodeScanner = new Html5QrcodeScanner(

    "qr-reader", { fps: 10, qrbox: 250 });

html5QrcodeScanner.render(onScanSuccess);

</script>

```
<h1>You can watch this video to better understand the problem</h1>

[![Youtube Video](https://img.youtube.com/vi/hPSIbl6p3So/0.jpg)](https://youtube.com/shorts/hPSIbl6p3So?feature=share)

**Comment by devmdeniz** [comment]
> why the heck the qrcode you are scanning is changing in real time?

It doesn't change in real time, I just change the page myself

**Comment by ROBERT-MCDOWELL** [comment]
so the next qrcode doesn't show any result right?
if yes, so maybe it throw an error.
