### ISSUE TITLE
barcode not detect in camera scanner

### ISSUE THREAD

**Issue by fadilkun45** [mebjas/html5-qrcode#493]
why i dont get result scan the barcode via camera but in via file its work barcode code 128

**Comment by ROBERT-MCDOWELL** [comment]
please please please, before to open an issue fill in all needed informations or you will never get a good answer!!!!
it's like to ask to your doctor "I'm sick! please heal me" without to give any info to your doctor!!!

**Comment by fadilkun45** [comment]
okay
- browser : egde
- barcode Format : code 128

issue : scanner not detect the barcode via camera scan

still not enough ?

**Comment by ROBERT-MCDOWELL** [comment]
again, OS, browser AND versions
device etc...

**Comment by fadilkun45** [comment]
OS : windows 10 
browser version : Version 102.0.1245.44 (Official build) (64-bit)

**Comment by fadilkun45** [comment]
i think barcode hard to scan i test in my phone its work
