### ISSUE TITLE
don't work in price checker mini computer device

### ISSUE THREAD

**Issue by gena1116** [mebjas/html5-qrcode#497]
I want to use this app in price checker devices. But it don't work, an error: NotFoundError : Requested device not found, this device don't have any webCam, have only QRCode reader

**Comment by ROBERT-MCDOWELL** [comment]
what do you mean by qr code reader?

**Comment by gena1116** [comment]
https://sc04.alicdn.com/kf/H547ec3f1317e4e2396c831d7091850fbR/244145730/H547ec3f1317e4e2396c831d7091850fbR.jpg

I have price checker device(computer). There is an image link I gave. There is no Web Camera but it has qr reader hardwear. It can automatically read qr code but I cannot get that value in my next app..

**Comment by ROBERT-MCDOWELL** [comment]
html5-qrcode does not manage other devices than camera, I guess the qrcode scanner is plugged through usb and must have it's own protocol or integrated chipset decoding directly the qrcode and sending the result through it with a special software.
I really don't know if this can be achieved with JavaScript in browser.

**Comment by mebjas** [comment]
Library only works with camera and images on device. QR scanners not supported.

Closing.
