### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by NateZimmer** [mebjas/html5-qrcode#5]
This library would be incredibly neat if it worked for it is far tinier than many other implementations. However, when I use this in my browser I see no image from the camera and it yields the following error in the console: 

```
Uncaught TypeError: Failed to execute 'createObjectURL' on 'URL': No function was found that matched the signature provided.
    at successCallback (html5-qrcode.js:87)
```

Edit: i'm using chrome on a laptop: 
```
Version 71.0.3578.98 (Official Build) (64-bit)
```

**Comment by mebjas** [comment]
@NateZimmer Thanks for reporting. I have pushed the fix and updated the sample code in this repository. It's not yet updated in the demo link, so can you validate it's working status by running the sample code in your environment?

**Comment by mebjas** [comment]
@NateZimmer can you validate once?

**Comment by naton** [comment]
Is it possible to update the demo as well? This project would see far more traction if URLs in the README actually worked.

**Comment by mebjas** [comment]
Updated the code to support new apis against the deprecated ones. Added better documentation and fixed the demo code.

Demo code: https://blog.minhazav.dev/research/html5-qrcode.html

**Comment by mebjas** [comment]
Should have been fixed now. Closing for now.
Feel free to reopen if still able to reproduce the issue.
