### ISSUE TITLE
camera keep launching 

### ISSUE THREAD

**Issue by flughafencon** [mebjas/html5-qrcode#506]
Hello 

I just copy the code from here 

[https://minhazav.medium.com/qr-and-barcode-scanner-using-html-and-javascript-2cdc937f793d](url)

the code was pretty simple but after I click "allow" to the camera, it just keep launching and nothing else.

[qr2.txt](https://github.com/mebjas/html5-qrcode/files/9102962/qr2.txt)

all other demo works fine, just this code, I don't know which part was wrong.
here are the video I just took, you can notice after I click allow, the camera light turn on for a sec then off.
[https://www.youtube.com/watch?v=LNdz7zZfYSg](url)

thanks in advance!

**Comment by mebjas** [comment]
Please raise this kind of question on stackoverflow / discussion part -- that way the community can help you address it.

Please use Github issues for filing bugs in the code or raising feature requests.
