### ISSUE TITLE
Assigning 'qrcode' externally causes the library to fail decoding of QR codes.

### ISSUE THREAD

**Issue by antheroo** [mebjas/html5-qrcode#51]
**Describe the bug**
The library internally utilizes 3rd party 'qrcode' module for QR-code decoding tasks. However there is not sufficient abstraction such that assigning 'qrcode' to something else externally to the library will cause the library to fail and flag errors such as qrcode.decode() failures.

**To Reproduce**
1. Assign qrcode to something else after Html5Qrcode has been initialized:
```
const html5QrCode = new Html5Qrcode(/* element id */ "reader");
var qrcode = '';
```

2. Start html5QrCode as usual, but parse the error.

3. Observed error:
> QR code parse error, error = TypeError: qrcode.decode is not a function

**Expected behavior**
It would be ideal to have sufficient abstraction such that assigning 'qrcode' externally to something else will not cause the library to break. Either that or mention it as a reserved word in the README.

**Screenshots**
N/A

**Desktop (please complete the following information):**
- Any

**Smartphone (please complete the following information):**
- Any

**Additional context**
N/A

Thanks!
Andrew

**Comment by mebjas** [comment]
I have hidden qrcode behind a function, so that it cannot be overridden globally. This'd be published in `v1.1.3`
