### ISSUE TITLE
I am unable to use barcode scan on iphone using safari browser

### ISSUE THREAD

**Issue by rehanraqeeb786** [mebjas/html5-qrcode#512]
I used html5-barcode pro to get camera and scan using this camera. It worked perfect on Android and any other platform other then IOS safari. It scans some code but didnt perform any action on some of other. 
I also had this issue on android during development, but i use experimental feature and it starts working on all type of codes. I used this below
 experimentalFeatures: {
        useBarCodeDetectorIfSupported: false
    }
 
But now i had issue with iphone IOS safari , it scans limited bar-codes not all. Can you please help me out on this.

**Comment by ROBERT-MCDOWELL** [comment]
put it on true as it relays directly to the barcode scanner API of the browser.

**Comment by ROBERT-MCDOWELL** [comment]
without any error message or more info how people can help?? btw if with true it works on android so the issue is on IOs browsers themselves and elsewhere

**Comment by rehanraqeeb786** [comment]
It don't shows any error. It works perfectly on android and scan all of
things. But without showing any error it doesn't scan using iOS on safari
browser. Let me give you an example.
https://blog.minhazav.dev/research/html5-qrcode
If you open this URL in android and scan attached image , it works
perfectly.
But if you open this in iOS and scan, it don't gives and error nor scan
barcode.

Can you please help me out, i was working on this from two days.

**Comment by mebjas** [comment]
UPC_A, UPC_E support was improved in version 2.3.2 please retest.

This will work without experimental config.

Please reopen if this issue is still there.

**Comment by Hussyn72** [comment]
Did we find any solution for this ?

**Comment by jgudo** [comment]
Facing the same issue. Only in iOS Safari

**Comment by indykoning** [comment]
Unfortunately Safari is way behind in supporting these new things and does not have support for BarcodeDetector that is being used for native support.
And the fallback using a javascript polyfill to try and decode them is unfortunately slow and less precise and thus the lower success rate.

What i've used to greater success is a Webassembly zbar port, using https://github.com/undecaf/barcode-detector-polyfill
It still doesn't have an as-high success rate as it does on browsers that natively support BarcodeDetector but it gets close!
