### ISSUE TITLE
Query Support Device Error

### ISSUE THREAD

**Issue by ankurmds** [mebjas/html5-qrcode#516]
**Describe the bug**

**To Reproduce**
1. Go to  https://blog.minhazav.dev/research/html5-qrcode
2. Click on 'Request Camera Permissions '
3. See an error

**Screenshots**
![Screenshot from 2022-08-09 11-50-26](https://user-images.githubusercontent.com/103626145/183580568-d99940f9-c6d4-4a60-862a-74a0aca04886.png)

**Smartphone (please complete the following information):**
 - OS: iPhone 11 Pro Max v14.0
 - Browser: Chrome
 - Version:-  92.0.4515.90

**Comment by ROBERT-MCDOWELL** [comment]
You must use IOS version 14.5 min as 14.0 is buggy

**Comment by mebjas** [comment]
This was ios issue, should be fixed in latest versions.

Closing.
