### ISSUE TITLE
Html5QrcodeScanner needs css fix

### ISSUE THREAD

**Issue by mebjas** [mebjas/html5-qrcode#53]
The [demo](https://blog.minhazav.dev/research/html5-qrcode) page running `Html5QrcodeScanner` has more modern UI because of existing dependencies in the webpage.

OTOH, without any existing css the UI is much primitive. 

This gives an advantage that the UI of the scanner can implicitly match the theme of the website it's attached to.

Considering pros and cons - make minimal fixes to the style or alternatively make this configurable.

**Comment by Qiming-Liu** [comment]
Hi, I just write a simple CSS theme for it.
https://github.com/Qiming-Liu/html5-qrcode-css

**Comment by mebjas** [comment]
> Hi mebjas, I really love your html5-qrcode.
> I just write a simple CSS theme for it.

@Qiming-Liu Thanks for sharing this.

Additionally,
We need more of a UI overhaul as described in https://github.com/mebjas/html5-qrcode/issues/207 which changes some of the existing issues, redundancies, internationalization issues and probably even allow developers to customize the style without having to implement on top of `Html5Qrcode` directly.

Looking forward to hear more feedbacks on this soon for designers/UXRs

**Comment by mebjas** [comment]
Started a discussion for this - https://github.com/mebjas/html5-qrcode/discussions/213

**Comment by mebjas** [comment]
Marking this as a duplicate of https://github.com/mebjas/html5-qrcode/issues/389

Let's have more discussion there.
