### ISSUE TITLE
how to return code type

### ISSUE THREAD

**Issue by andy-yeung** [mebjas/html5-qrcode#538]
hi, how to get/return the code type? decodeResult just return [object]. I want to know what kind of type about the code.

**Comment by liushengqi000** [comment]
code in demo
```
function isUrl(e) {
    var t = new RegExp(/^((javascript:[\w-_]+(\([\w-_\s,.]*\))?)|(mailto:([\w\u00C0-\u1FFF\u2C00-\uD7FF-_]+\.)*[\w\u00C0-\u1FFF\u2C00-\uD7FF-_]+@([\w\u00C0-\u1FFF\u2C00-\uD7FF-_]+\.)*[\w\u00C0-\u1FFF\u2C00-\uD7FF-_]+)|(\w+:\/\/(([\w\u00C0-\u1FFF\u2C00-\uD7FF-]+\.)*([\w\u00C0-\u1FFF\u2C00-\uD7FF-]*\.?))(:\d+)?(((\/[^\s#$%^&*?]+)+|\/)(\?[\w\u00C0-\u1FFF\u2C00-\uD7FF:;&%_,.~+=-]+)?)?(#[\w\u00C0-\u1FFF\u2C00-\uD7FF-_]+)?))$/g);
    if (e.match(t))
        return !0;
    var n = new RegExp(/(http(s)?:\/\/.)?(www\.)?[-a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\+.~#?&//=]*)/g);
    return !!e.match(n)
}
function isPhoneNumber(e) {
    var t = new RegExp(/tel:[+]*[0-9]{3,}/g);
    return e.match(t)
}
function isWifi(e) {
    var t = new RegExp(/WIFI:S:(.*);T:(.*);P:(.*);H:(.*);;/g);
    return e.match(t)
}
function isUpi(e) {
    try {
        var t = new URL(e);
        return !(!t || null == t) && "upi:" === t.protocol
    } catch (e) {
        return !1
    }
}
function detectType(e) {
    return isUrl(e) ? TYPE_URL : isPhoneNumber(e) ? TYPE_PHONE : isWifi(e) ? TYPE_WIFI : isUpi(e) ? TYPE_UPI : TYPE_TEXT
}
```
decodeResult Example
```
decodeResult ={
  "decodedText":"1234567890913",
  "result":{
    "text":"1234567890913",
    "format":{
      "format":9,
      "formatName":"EAN_13"
    }
  }
}
```

**Comment by andy-yeung** [comment]
> code in demo
> 
> ```
> function isUrl(e) {
>     var t = new RegExp(/^((javascript:[\w-_]+(\([\w-_\s,.]*\))?)|(mailto:([\w\u00C0-\u1FFF\u2C00-\uD7FF-_]+\.)*[\w\u00C0-\u1FFF\u2C00-\uD7FF-_]+@([\w\u00C0-\u1FFF\u2C00-\uD7FF-_]+\.)*[\w\u00C0-\u1FFF\u2C00-\uD7FF-_]+)|(\w+:\/\/(([\w\u00C0-\u1FFF\u2C00-\uD7FF-]+\.)*([\w\u00C0-\u1FFF\u2C00-\uD7FF-]*\.?))(:\d+)?(((\/[^\s#$%^&*?]+)+|\/)(\?[\w\u00C0-\u1FFF\u2C00-\uD7FF:;&%_,.~+=-]+)?)?(#[\w\u00C0-\u1FFF\u2C00-\uD7FF-_]+)?))$/g);
>     if (e.match(t))
>         return !0;
>     var n = new RegExp(/(http(s)?:\/\/.)?(www\.)?[-a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\+.~#?&//=]*)/g);
>     return !!e.match(n)
> }
> function isPhoneNumber(e) {
>     var t = new RegExp(/tel:[+]*[0-9]{3,}/g);
>     return e.match(t)
> }
> function isWifi(e) {
>     var t = new RegExp(/WIFI:S:(.*);T:(.*);P:(.*);H:(.*);;/g);
>     return e.match(t)
> }
> function isUpi(e) {
>     try {
>         var t = new URL(e);
>         return !(!t || null == t) && "upi:" === t.protocol
>     } catch (e) {
>         return !1
>     }
> }
> function detectType(e) {
>     return isUrl(e) ? TYPE_URL : isPhoneNumber(e) ? TYPE_PHONE : isWifi(e) ? TYPE_WIFI : isUpi(e) ? TYPE_UPI : TYPE_TEXT
> }
> ```
> 
> decodeResult Example
> 
> ```
> decodeResult ={
>   "decodedText":"1234567890913",
>   "result":{
>     "text":"1234567890913",
>     "format":{
>       "format":9,
>       "formatName":"EAN_13"
>     }
>   }
> }
> ```


thank you for your reply. Since i am new to Javascript, I am learning js from this project but I don't know how to implement/gather these functions into qrCodeSuccessCallback function. Can you give me some idea?
here's my part of code:
`var html5QrCode = new Html5Qrcode("reader");
	
	const qrCodeSuccessCallback = (decodedText, decodedResult) => {
		var num = document.getElementById("t1").rows.length;
		var newRow=document.createElement("tr");
		var newCell=document.createElement("td");
		var anode = document.createTextNode(num+'.');
		var remove_str = document.getElementById("rows").innerText.replace(/\s/g,'');
		if (remove_str.includes(decodedText)){
			alert("Scanned");
		}
		else{
			newCell.appendChild(anode);
			newRow.appendChild(newCell);
			var newCell2 = document.createElement("td");
			nextId = nextId +1;
			table.append($('<tr id="tr_status#"'+nextId+'"><td>'+nextId+'</td><td>'+decodedText+'</td><td><select name="status#'+nextId+'"><option selected value="IN#'+nextId+'">In-Use</option><option value="Stock#'+nextId+'">Stock</option></select></td></tr>'));
			table.data('Tabledit').reload();
		}			
	};
	const config = { fps: 500, qrbox: { width: 250, height: 150 },disableFlip: false,
                        focusMode: "continuous",
                        advanced:[{zoom: 2.0}],
						rememberLastUsedCamera: true,
						aspectRatio: 1.333334,
						
						experimentalFeatures: {
							useBarCodeDetectorIfSupported: true
						},
						supportedScanTypes:[Html5QrcodeScanType.SCAN_TYPE_CAMERA,Html5QrcodeScanType.SCAN_TYPE_FILE],
						
						formatsToSupport: [
							Html5QrcodeSupportedFormats.CODE_39,
							Html5QrcodeSupportedFormats.DATA_MATRIX,
							Html5QrcodeSupportedFormats.CODE_128,
							Html5QrcodeSupportedFormats.CODE_93
						],
						
			};

	html5QrCode.start({ facingMode: "environment" }, config, qrCodeSuccessCallback);`

**Comment by andy-yeung** [comment]
oh, I found a solution.
it's only one command line that can return the code type.
`decodeResult.result.format.formatName`
