### ISSUE TITLE
Webpack example

### ISSUE THREAD

**Issue by syfgkjasdkn** [mebjas/html5-qrcode#54]
👋

Thank you for this library!

I wonder if it'd possible to add a webpack example for it? I've tried using it with a dynamic `import`:

```js
const qrcode = await import("html5-qrcode");
```
but the returned object is empty. I guess this is because there are no exports like `export {Html5Qrcode, Html5QrcodeScanner};` in https://github.com/mebjas/html5-qrcode/blob/master/html5-qrcode.js?

**Comment by mebjas** [comment]
Does this work - https://webpack.js.org/configuration/externals/

**Comment by syfgkjasdkn** [comment]
Hi @mebjas! Sorry, I'm no longer using your library.
