### ISSUE TITLE
Interleaved 2 of 5

### ISSUE THREAD

**Issue by peterknapp** [mebjas/html5-qrcode#545]
Hi,

is it possible to scan codes in "Interleaved 2 of 5" format? Just tried it and it failed. Does anyone has a workaround?

Rgds.

**Comment by mebjas** [comment]
Could you add more info on `Interleaved 2 of 5` format or add some samples.

**Comment by peterknapp** [comment]
> Could you add more info on `Interleaved 2 of 5` format or add some samples.

Sure. This is an example. I was not able to scan such a code.

<img width="325" alt="Interleaved2of5" src="https://user-images.githubusercontent.com/4532026/197475073-0bf3bd06-131c-4a5d-be32-2b81857f4a1e.png">

**Comment by mebjas** [comment]
Can you try with this configuration

```js
	let html5QrcodeScanner = new Html5QrcodeScanner(
        "reader", 
        { 
            fps: 10,
            qrbox: qrboxFunction,
            // Important notice: this is experimental feature, use it at your
            // own risk. See documentation in
            // mebjas@/html5-qrcode/src/experimental-features.ts
            experimentalFeatures: {
                useBarCodeDetectorIfSupported: true
            },
            rememberLastUsedCamera: true,
            aspectRatio: 1.7777778
        });
```

Particularly relevant one is
```js
experimentalFeatures: {
    useBarCodeDetectorIfSupported: true
    },
```

**Comment by peterknapp** [comment]
YES! Thank you. I came across this config option "experimentalFeatures", but your code-snippet showed me how to implement ist properly! Again, thank you. Works now.

**Comment by mebjas** [comment]
Thanks for confirming. Looks like the js sdk I am using (zxing based) doesn't support it well.

Will revisit impl later.

**Comment by peterknapp** [comment]
Hi,

one additional question. EAN-Codes are still not working. This is known? This would be great if this type of Code will be recognised.

Rgds,
Peter

![tempImageofaQYt](https://user-images.githubusercontent.com/4532026/199451089-4ac8b802-053a-4637-b2e0-fbaee7d19a5b.gif)
