### ISSUE TITLE
what's the difference between https and http

### ISSUE THREAD

**Issue by SimpleSoft-2020** [mebjas/html5-qrcode#548]
If I use the https website to scan the barcode, the width and the height is valid, for example:
qrbox:  {width: 550, height: 250}, the scan box is a rectangle box with width 550 and height 250, it's great
![06c14ef7acb2f55151f1c8ff875003a](https://user-images.githubusercontent.com/64841105/191972599-134c2feb-27af-4ee4-8807-15bf41a69cfb.jpg)

But if use the http website to scan the barcode, the code is same for example:
qrbox:  {width: 550, height: 250}
![9a5b6aabecd6eeeb101af57d0ce7157](https://user-images.githubusercontent.com/64841105/191972509-681a1999-ae32-4d1f-a619-6ada2ff7f3a8.jpg)

But the code is invalid, it will not show the rectangle box view, and only use the code below:
qrbox: 550
It can show the scan box, but it's a squar box with width 550.
How can I use it in http website with a rectangle scan box?

**Comment by mebjas** [comment]
Camera access is not supported without `https` in web.
