### ISSUE TITLE
[Feature Request] Scan a new QR code image

### ISSUE THREAD

**Issue by sajesh1985** [mebjas/html5-qrcode#559]
My clients want's me to change the default QR image to a new QR code image(PFA). But I am unable to get the scan work for this.
Is there anyway I can get the scan work for this new QR image.
![New](https://user-images.githubusercontent.com/2425748/196521597-dc92d784-4fa1-415b-8f16-92bf10e9a1c5.png)

**Comment by mebjas** [comment]
I don't fully understand the requirement, please elaborate.

**Comment by mebjas** [comment]
Please reopen with more information!
