### ISSUE TITLE
Error : QR code parse error, error = couldn't find enough finder patterns

### ISSUE THREAD

**Issue by Martin-beeep** [mebjas/html5-qrcode#56]
Dear Sir/Madam, 

I test html5qrcode with below codes.  And, when I scanned QR code, below error message is responded in "errorMessage".  May I know how to fix it ? 

errorMessage=QR code parse error, error = couldn't find enough finder patterns

	<!DOCTYPE html>
	<html>
	<head>

	<script src="html5-qrcode.min.js"></script>

	</head>

	<body onload="checkcameras()">

	<div id="reader"></div>
	<p id="demo"></p>

	<script>

	function onScanSuccess(qrMessage) {
		console.log("QR matched = ${qrMessage}");
	}

	function onScanFailure(error) {
		console.warn("QR error = ${error}");
	}

	function checkcameras() { 

	Html5Qrcode.getCameras().then(devices => {
	  
	  if (devices && devices.length) {
		var cameraId = devices[1].id;
		const html5QrCode = new Html5Qrcode("reader", true);

		html5QrCode.start(
		  cameraId,     
		  {
			fps: 10,    
			qrbox: 500  
						
		  },
		  qrCodeMessage => {
			document.getElementById("demo").innerHTML = qrCodeMessage;	
		  },
		  errorMessage => {
			document.getElementById("demo").innerHTML = Date.now() + "--" + errorMessage;			
		  })
		.catch(err => {
		
		});
			
	  }
	}).catch(err => {

	});
	}

	</script> 

	</body>

	</html>

Martin.

**Comment by mebjas** [comment]
@Martin-beeep 
This error message is not a one time error message - qrcode scanner is continuously scanning the input from camera 10 times per second. Everytime it can decode the message
```js
qrCodeMessage => {
    document.getElementById("demo").innerHTML = qrCodeMessage;	
}
```
Will be called and every time it cannot 
```js
errorMessage => {
    document.getElementById("demo").innerHTML = Date.now() + "--" + errorMessage;			
})
```
Will be called.

Mostly this is due to composition that it's not able to find enough patterns - if you think you have good enough visible QR Code in the scene and still not getting the resullt then it's likely a bug - can you share the video of this here?

**Comment by Martin-beeep** [comment]
> @Martin-beeep
> This error message is not a one time error message - qrcode scanner is continuously scanning the input from camera 10 times per second. Everytime it can decode the message
> 
> ```js
> qrCodeMessage => {
>     document.getElementById("demo").innerHTML = qrCodeMessage;	
> }
> ```
> 
> Will be called and every time it cannot
> 
> ```js
> errorMessage => {
>     document.getElementById("demo").innerHTML = Date.now() + "--" + errorMessage;			
> })
> ```
> 
> Will be called.
> 
> Mostly this is due to composition that it's not able to find enough patterns - if you think you have good enough visible QR Code in the scene and still not getting the resullt then it's likely a bug - can you share the video of this here?

Thanks, mebjas.  

I tried to scan the attached QR code (qrcode-test.jpg).  I can scan it successfully by other QR code software.  

![qrcode-test](https://user-images.githubusercontent.com/66691355/84217506-eba38a00-aafe-11ea-8290-068fba649eda.JPG)

**Comment by mebjas** [comment]
Which environment are you trying this on? Mobile or PC or Mac also, could you share which browser?

**Comment by Martin-beeep** [comment]
> Which environment are you trying this on? Mobile or PC or Mac also, could you share which browser?

Thanks.  I tried in iPhone 11, iOS 13.5.1 and Safari.

**Comment by mebjas** [comment]
Thanks for the response. I pushed some changes just now and verified it to work on Safari on Ipad. Can you try once more - https://blog.minhazav.dev/research/html5-qrcode

**Comment by Martin-beeep** [comment]
> Thanks for the response. I pushed some changes just now and verified it to work on Safari on Ipad. Can you try once more - https://blog.minhazav.dev/research/html5-qrcode

Thanks a lot.  It works.

**Comment by mebjas** [comment]
Great!

Closing this bug, please update the library to latest from npm or release in Github - the latest version right now is `v1.1.3`
