### ISSUE TITLE
[Feature Request] Enable 'willReadFrequently' on html5 canvas

### ISSUE THREAD

**Issue by jbemmel** [mebjas/html5-qrcode#566]
**Is your feature request related to a problem? Please describe.**
Scanning performance can possibly be improved by providing a hint to the web browser about intended usage

**Describe the solution you'd like**
See [this spec](https://github.com/fserb/canvas2D/blob/master/spec/will-read-frequently.md)
```
// Javascript example
const canvas = document.createElement('canvas');
const ctx = canvas.getContext('2d', {willReadFrequently: true});
```
this would (probably) apply to https://github.com/mebjas/html5-qrcode/blob/master/third_party/zxing-js.umd.js

Originally developed for games, but high frequency fps scans could also benefit from this

**Describe alternatives you've considered**
It's a trivial performance enhancement

**Additional context**

**Comment by ROBERT-MCDOWELL** [comment]
willReadFrequently is not compatible with all browsers unfortunately. I did some video to canvas experiments with and without this option and for some reason the pixels didn't show up on the canvas at all on chrome....

**Comment by jbemmel** [comment]
Couldn't we detect the browser, and only enable this flag when a supported browser is used?

**Comment by ROBERT-MCDOWELL** [comment]
@jbemmel 
yes, possible, or wait until it's fully compatible.... for now strangely MSD shows that only safari does not support it, so it means chrome supports it but it's buggy for now... a git project had some similar issues with this option here
https://github.com/openlayers/openlayers/issues/14175

**Comment by mebjas** [comment]
Thanks for the pointer @jbemmel and thanks for the insights @ROBERT-MCDOWELL 

It'd be great to investigate the performance with and without this before using this. Keeping this issue open if someone is interested in the research.

**Comment by mebjas** [comment]
Added in v2.3.1 (in prod)
