### ISSUE TITLE
Two weird issues.

### ISSUE THREAD

**Issue by hy-net** [mebjas/html5-qrcode#574]
**First Issue**

![image](https://user-images.githubusercontent.com/55421612/199037192-b2340f13-06e4-4610-9ac6-ad034ffdd196.png)

It is working perfectly fine in my PC. But when browse with a mobile phone (Mi 9, and chrome) the above is shown when I try to pick a camera.

Seems like the text and background are of the same color, so I don't can't see the camera description.

Edit: ``navigator.mediaDevices.getUserMedia()`` is returning empty string (instead of null) in android. Seems like this is a permission issue. It will be better if we can show 'Camera 1', 'Camera 2' instead of the ``value`` (which is a very long guid), when the label is not available

**Second issue**

When trying to scan QR code on mobile phone (everything is working fine), the video is not render (not updating) even though the QR Code can be scanned and updated correctly.

It will render if I keep on scrolling the browser page, but appears as hang if I didn't scroll. if I point the camera to a QR Code, it can still be scanned correctly even though the video is static, 

Edit: The screen will render as long as my finger is touching the browser. Otherwise it will only show a static image.

**Comment by mebjas** [comment]
This is a good set of weird bugs, thanks for posting.

Would you mind converting it to two separate issues?

I'll start working on `Camera 1`, `Camera 2` suggestion.
