### ISSUE TITLE
Disable SSL requirement

### ISSUE THREAD

**Issue by martingpa** [mebjas/html5-qrcode#577]
I'm hosting a website in my computers localhost, however I have to open the website through my phone accesing it through the ip of my computer. However chrome obviously doesn't detect that the website is coming from my computers localhost and I cant use the QR code scanner as the page doesn't have SSL. I've tried to add SSL to the localhost but I haven't been succesfull so if you know how to disable this feature it would be great thanks!.

**Comment by mebjas** [comment]
It's not a library requirement but requirement by browser thats camera
access is only supported with ssl or in localhost.

Nothing much can be done about it.

**Comment by martingpa** [comment]
Thanks, I fixed the problem
