### ISSUE TITLE
Compatibility - Android WebView - Missing camera labels on camera selector

### ISSUE THREAD

**Issue by mikolajtutorum** [mebjas/html5-qrcode#578]
**Describe the bug**
Missing camera labels on camera selector and camera name on when selection is made within Android WebView App. Code based on Laravel PHP. No alternative display present like "Camera 1", "Camera 2" and so on if labels not found.

**Describe the browser:**
 - OS: Android
 - Browser: WebView

**Screenshots**
Actual result:
https://i.imgur.com/C0vL5Tk.png

Expected result:
https://i.imgur.com/uIZpoRU.png

**Comment by ROBERT-MCDOWELL** [comment]
I'm not sure webview has camera/mic access anyhow....

**Comment by mikolajtutorum** [comment]
> I'm not sure webview has camera/mic access anyhow....

If the app asks for video/audio permissions it does work. That includes this QR Reader. Only issue is getting the labels for camera names and if they are front or back facing. It shows up in regular browser apps like Chrome, Firefox, UC Browser, Opera.

**Comment by mebjas** [comment]
I'd like to try this out. Is there a reference project on Github I could quickly debug this on?

(It might be useful to add one for everyone's reference)

**Comment by mebjas** [comment]
I am able to reproduce this in DuckDuckGo browser.

Will try to implement something there!

Target version: V2.2.8

**Comment by mebjas** [comment]
Prototyped it will look like this

![Screenshot_20221105-005550](https://user-images.githubusercontent.com/3007365/200032557-21679229-3d21-4212-a22f-1f2558b6f6b6.png)
![Screenshot_20221105-005544](https://user-images.githubusercontent.com/3007365/200032567-eb50b4f0-e25f-4bdb-a233-fcbb906122aa.png)

**Comment by mebjas** [comment]
Published the feature in v2.2.8

Please update the library and verify!

Closing this issue, please reopen if you see some issue.
