### ISSUE TITLE
Navigator.getUserMedia() is deprecated, advised to use MediaDevices.getUserMedia() instead

### ISSUE THREAD

**Issue by IvanPime** [mebjas/html5-qrcode#6]
No work on Safari 12.0.3 and mobile devices

**Comment by mebjas** [comment]
Is it the latest code or the demo link that is not working?

**Comment by mebjas** [comment]
Support added, thanks for pointing out. Apologies for the delays.

Demo: https://blog.minhazav.dev/research/html5-qrcode.html
