### ISSUE TITLE
UPC-A and UPC-E is not detected on IOS devices (Chrome & Safari)

### ISSUE THREAD

**Issue by joshuaquirante** [mebjas/html5-qrcode#604]
Hi Im using iphon8 Plus (Google Chrome & Safari Browser) and when im trying to scan UPC-A and UPC-E, it is not detected by the app.

**Comment by mebjas** [comment]
Thanks for reporting this issue, I am looking at it.

Please follow this issue for updates: https://github.com/mebjas/html5-qrcode/issues/605
