### ISSUE TITLE
[Documentation] User guide implementation QR Scan for multiple input fields

### ISSUE THREAD

**Issue by iamSathishMohan** [mebjas/html5-qrcode#606]
I have a requirement to create a QR Scanner for multiple input fields in single page, which will populate the input field value once its decode the QR data. I have tried looking for an example, but couldn't find one. It will be great if this scenario documented in the examples.

Thank you in advance !!

**Comment by mebjas** [comment]
Could you use the same instance QR scanner instance for different input element? By retaining state of which input element is initiating the UI?
