### ISSUE TITLE
[Feature Request] Investigate support for bar code scanner

### ISSUE THREAD

**Issue by mebjas** [mebjas/html5-qrcode#61]
- [ ] Fast, robust javascript based bardcode scanner
 - [ ] Architecture to scan qrcode, barcode together
 - [ ] Plug this into the app

**Comment by mebjas** [comment]
Work in progress prototype for Barcode scanner in `beta-zxing` branch.

You can try out the demo here: https://blog.minhazav.dev/research/html5-qrcode-beta 
Here's the minified code to experiment with: [link to minified js](https://raw.githubusercontent.com/mebjas/html5-qrcode/beta-zxing/minified/html5-qrcode.min.js)

After testing with some different barcodes, I'll move it to prod. Feedbacks welcome.

**Comment by mebjas** [comment]
cc: @ianbroad

**Comment by ianbroad** [comment]
@mebjas Thank you, I just saw this.  I will give it a test and report back.

**Comment by mebjas** [comment]
Implemented
