### ISSUE TITLE
Error printed in loop

### ISSUE THREAD

**Issue by FilipeQ** [mebjas/html5-qrcode#610]
**Describe the bug**
When we use the api with the facingMode property we get the following error: 
QR code parse error, error = NotFoundException: No MultiFormat Readers were able to detect the code.

**To Reproduce**
1. We need to use the code html5QrCode.start({ facingMode: "environment" }, config, qrCodeSuccessCallback, qrCodeErrorCallback);
2. As user we need to select to scan
3. The error is displayed in the browser console

**Expected behavior**
I expected the scanner camera without any log error in loop

**Screenshots**
![image](https://user-images.githubusercontent.com/7237584/202420093-b927e145-a065-4f16-b8b7-89c3fc4ae6c1.png)

**Desktop (please complete the following information):**
 - any browser

**Additional context**
If I remove the facingMode property we dont have any error in console but if I enable the property to force the back camera the error show up in loop. 

Code:
`this.html5QrCode = new Html5Qrcode("reader");`

```
const qrCodeSuccessCallback = (decodedText, decodedResult) => {
                
                console.log(decodedText)
               
 };
```
```
const qrCodeErrorCallback = (err) => {
                console.error(err);
               
            };
```

```
const formatsToSupport = [
                Html5QrcodeSupportedFormats.CODE_128
            ];
```

```
const config = {
                fps: 10,
                qrbox: { width: 400, height: 150 },
                rememberLastUsedCamera: true,
                // Only support camera scan type.
                supportedScanTypes: [Html5QrcodeScanType.SCAN_TYPE_CAMERA],
                formatsToSupport: formatsToSupport
            };

            this.html5QrCode.start({ facingMode: "environment" }, config, qrCodeSuccessCallback, qrCodeErrorCallback);
```

**Comment by mebjas** [comment]
It's getting printed from your error callback.

Change it like this

```js
let qrCodeErrorCallback = function(-) { /* no op */ }
```

To skip printing the errors to console.


---------
Additionally, for this kind of question please use Stackoverflow to get quicker answer. In case you don't get an answer there it's OK to create an issue here with the link to question. Having a question on SO will help future readers as well and will lead to faster time to resolution.


Closing this issue for now, please reopen if the issue persists.

**Comment by FilipeQ** [comment]
I know that the error is printed because i have the console.log but removing the console.log is not any solution. We have the error event to see and correct the errors.

 I want to know why the api is give me the error. I think this is not normal. It give me the error after i click to scan and this only happens with the config property facingMode: "environment"
