### ISSUE TITLE
Turn off camera when file upload selected from scanner link

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [mebjas/html5-qrcode#613]
How to tunr off camera promise while it's initialising and the user decides to click back to file upload scanner?
for now the link goes to the file upload and shows the camera once initialization finished making the UI inconsistent....
I use html5qrcodeScanner. On of the solution would be to disable the swap link or even the whole UI while the camera is initializing

**Comment by ROBERT-MCDOWELL** [comment]
btw I use html5qrcodeScanner.

**Comment by mebjas** [comment]
Good point, this is a corner case.

**Comment by mebjas** [comment]
Will be fixed in `version 2.3.4`!

**Comment by mebjas** [comment]
Fixed & released

 - Github release: https://github.com/mebjas/html5-qrcode/releases/tag/v2.3.4
 - NPM: https://www.npmjs.com/package/html5-qrcode/v/2.3.4
