### ISSUE TITLE
Its working on localhost but not in production.

### ISSUE THREAD

**Issue by chhamza** [mebjas/html5-qrcode#619]
Working on localhost but in production not working on desktop (Andoid and iOS works)

Error says: "html5-qrcode:1 Uncaught (in promise) Error getting userMedia, error = NotAllowedError: Permission denied"

**Comment by mebjas** [comment]
Do you have SSL? Only works on https.

https://web.dev/media-capturing-images/

**Comment by mebjas** [comment]
Please reopen if this issue persists.
