### ISSUE TITLE
NotFoundError in Chrome / TypeError in Firefox

### ISSUE THREAD

**Issue by stacysealky** [mebjas/html5-qrcode#621]
In Chrome with MacOS, when start scan is clicked, it shows "NotFoundError: Requested device not found".

<img width="904" alt="Screen Shot 2022-11-22 at 1 43 23 PM" src="https://user-images.githubusercontent.com/26069780/203419408-5a4a191d-9c25-4f72-8b92-fcc428ad0fde.png">

In Firefox with MacOS, when start scan is clicked, it shows "TypeError: this.track.getCapabilities is not a function".

<img width="939" alt="Screen Shot 2022-11-22 at 1 39 55 PM" src="https://user-images.githubusercontent.com/26069780/203419422-d4ce65fa-4c23-4fcd-83d6-d1aa3db5b801.png">

**Comment by mebjas** [comment]
Was able to reproduce the Firefox error on Android as well. Will fix it
asap.

Reproduction of Mac issue pending.

**Comment by mebjas** [comment]
Firefox issue fixed for now with https://github.com/mebjas/html5-qrcode/pull/622

Published to npm and [Github](https://github.com/mebjas/html5-qrcode/releases/tag/v2.3.3) as `version 2.3.3`. Please retest.

Once again, thanks for the bug.

**Comment by stacysealky** [comment]
Hey @mebjas, 
Thank you so much for sharing this library with other developers. 
And thanks for fixing the issue so quickly!
I really admire your work and want to share my sincere appreciation for your awesome contribution to the open source.

Just a quick question though, do you think the 'html5-qrcode' library is production safe?

**Comment by mebjas** [comment]
What do you mean by production safe?
