### ISSUE TITLE
For mobile phone scanning area display adaptation problem

### ISSUE THREAD

**Issue by burning110-lab** [mebjas/html5-qrcode#626]
**Describe the bug**
For mobile phone scanning area display adaptation problem
 - What is not working and what is expected.
The scanning area should cover the entire screen
**Describe the browser:**
 - OS: Android
 - Browser chrome
 - Version Latest version

**Screenshots**
![372E2C6FDC37EFFBF4607BDE9D233DDD](https://user-images.githubusercontent.com/65691454/204126871-edd6cf50-c8a9-45c0-b80b-8615e2afe941.jpg)

**Additional context**

**Comment by burning110-lab** [comment]
I don't know why there is always a gray area at the bottom

**Comment by mebjas** [comment]
Try setting 16/9 aspect ratio?

```js
let html5QrcodeScanner = new Html5QrcodeScanner(
        "reader", 
        { 
            fps: 10,
            qrbox: {width: 250, height: 250},
            useBarCodeDetectorIfSupported: true,
            rememberLastUsedCamera: true,
            aspectRatio: 16/9,
        });
```

**Comment by mebjas** [comment]
Please reopen if the issue is not resolved.
