### ISSUE TITLE
Unable to scan QR Codes which have decoded text of less than 18 characters.

### ISSUE THREAD

**Issue by haripriya9209** [mebjas/html5-qrcode#629]
I have generated a QR Code from this website: https://www.the-qrcode-generator.com/ with the decoded text of:  id:1234567
Attaching smple QR Code: https://photos.app.goo.gl/zu6yQquw7kMbyAEQA
Html5-QRCode package is unable to detect this QRCode, and I am currently using the latest version: 2.3.3
I am testing in google chrome browser, the decoded text more than 18 characters works properly by using this package
Here is my code:
QrReader.js:
```
import React from 'react';
import "./QrReader.css";

const QrReader = ({handleClickAdvanced, display}) =>{
    
    return(
        <>
            <div className="qr-parent bg">
                <div className={display?"d-none":'qr-reader-container'}>
                    <div id="reader" style={{width:"300px"}}/>
                </div>
                <button className='button-styles' onClick={()=>handleClickAdvanced()} 
                    style={display?{visibility:"visible"}:{display:"none"}}
                    >
                        Scan
                </button>
            </div>
        </>
        
    )
}

export default QrReader;
```
ScanDetails.js

```
import { Html5Qrcode } from "html5-qrcode";

const ScanDetails = () =>{
const handleClickAdvanced = () =>{

        const qrConfig = {fps: 10, qrbox: {width: 200, height: 200}};

        useEffect(()=>{
                html5QrCode = new Html5Qrcode("reader");
            }, []);

        const qrCodeSuccessCallback = (decodeText, decodedResult)=>{
            console.log(decodeText);
       };

        html5QrCode.start(
            {facingMode: "environment"},
            qrConfig,
            qrCodeSuccessCallback
        ).catch((err) => {
            console.log(err)
        });
    };

return(
<div>
  <QrReader
  handleClickAdvanced={()=>{handleClickAdvanced()}}
  display={display}
  />
</div>
)
};

export default ScanDetails;
```

Even I tried many other codesandbox examples who used this package, even there the QR Code is not working.
Reproducing issue from codesandbox: https://codesandbox.io/s/html5-qrcode-uldr13?file=/src/App.js

**Comment by mebjas** [comment]
I am trying something out with version 2.3.4 to improve robustness.

Once deployed please try with that.

**Comment by mebjas** [comment]
`version 2.3.4` is deployed - please retry.

**Comment by haripriya9209** [comment]
Thanks a lot, this is working, as it was little urgency in our project and you made it work, thank you soo much
