### ISSUE TITLE
padding top of the scanner switch link

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [mebjas/html5-qrcode#633]
is it possible to add an extra padding top between the scanner switch link and the request camera button? for now it's quite tough to click on it on a smartphone without to touch the request camera button. I tried to add some padding top with javascript but does not work I dunno why

**Comment by mebjas** [comment]
In latest version all key elements have a public ID and class defined [here](https://github.com/mebjas/html5-qrcode/blob/master/src/ui/scanner/base.ts#L46)

For this one you can set css for `#html5-qrcode-anchor-scan-type-change`

```css
#html5-qrcode-anchor-scan-type-change {
    padding-top: 10px
}
```

**Comment by ROBERT-MCDOWELL** [comment]
ok thanks!
