### ISSUE TITLE
I am not able to scan code using camera

### ISSUE THREAD

**Issue by naitik-lodha** [mebjas/html5-qrcode#640]
When I click on scan using camera.It requests for camera permission but doesnt switch on the camera.

**Comment by cramaboule** [comment]
works for me  with the 2.3.4 If I remove:
experimentalFeatures: {
    useBarCodeDetectorIfSupported: true
}

**Comment by ROBERT-MCDOWELL** [comment]
you don't need to use experimentalFeatures for useBarCodeDetectorIfSupported

**Comment by cramaboule** [comment]
> you don't need to use experimentalFeatures for useBarCodeDetectorIfSupported

Yes, as it is by default 'enable'

supportedScanTypes: [Html5QrcodeScanType.SCAN_TYPE_CAMERA]
gives me problem too.

**Comment by ROBERT-MCDOWELL** [comment]
try to empty your browser cache completely.

**Comment by cramaboule** [comment]
> try to empty your browser cache completely.

yes

**Comment by cramaboule** [comment]
`supportedScanTypes` if ONLY camera is selected it gives me a bug!

**Comment by naitik-lodha** [comment]
Ok thanks a lot.
