### ISSUE TITLE
Uncaught TypeError when using camera only when Requesting Permissions in 2.3.4

### ISSUE THREAD

**Issue by mikerowe81** [mebjas/html5-qrcode#657]
Using the Html5QrcodeScanner, when supportedScanTypes is set to "camera only" in 2.3.4, clicking the Request Camera Permissions button causes the following error:

> Uncaught TypeError: Cannot read properties of null (reading 'style')
>     at Html5QrcodeScanner2.showHideScanTypeSwapLink (html5-qrcode-scanner.ts:1028:41)
>     at Html5QrcodeScanner2.createCameraListUi (html5-qrcode-scanner.ts:537:15)
>     at HTMLButtonElement.<anonymous> (html5-qrcode-scanner.ts:596:19)

I believe the issue is line [537 in html5-qrcode-scanner.ts](https://github.com/mebjas/html5-qrcode/blob/9dfb1a36daf56e09e4c8e1f9e572868d0c8af108/src/html5-qrcode-scanner.ts#L537)

```javascript
$this.showHideScanTypeSwapLink(false);
```

Perhaps it should be wrapped in...

```javascript
if (this.scanTypeSelector.hasMoreThanOneScanType()) {
    $this.showHideScanTypeSwapLink(false);
}
```
1. Install 2.3.4
2. Set config to camera only
`supportedScanTypes: [Html5QrcodeScanType.SCAN_TYPE_CAMERA]`
4. Click Request Camera Permissions Button
5. See error

Workaround was to create an empty element with the following ID...
```html
<div id="html5-qrcode-anchor-scan-type-change"></div>
```

**Comment by laviddichterman** [comment]
I'm also experiencing this issue on 2.3.4 but not on 2.3.3

**Comment by Helkyd** [comment]
Hi, 
Yesterday was working fine... 
Today for some reason is not... 
Using
"<script src="https://unpkg.com/html5-qrcode" type="text/javascript"></script>"


![image](https://user-images.githubusercontent.com/20396898/210136463-e90a0a6d-3ea1-4360-8e3f-73f1ee725fc3.png)
