### ISSUE TITLE
After destroying an Html5Qrcode Object the scanner continue running

### ISSUE THREAD

**Issue by LouisVenhoff** [mebjas/html5-qrcode#661]
**Describe the bug**
I am working at an mobile application which is uning this scanner library, after each scan i am leaving the scanner page and set the scanner object to null) after a few scans my application gets very slowly. In the performance monitor i can see that some Html5QrCode Methodes will be executed) so i think it continues living.

**To Reproduce**
1. Create an HTML5QrCode
2. Start the Scanner
3. Delete the reference of the Scanner
4. Check Performance
5. Repeate

**Expected behavior**
The HTML5Qrcode object should do not exist and do nothing when the ibject is set to null

Thank You

**Comment by MM1132** [comment]
As the documentation says, you should be calling the `stop()` function on the scanner object once done scanning. That seemed to do the trick for me.

**Comment by LouisVenhoff** [comment]
After the Stop function i have the same issue.
