### ISSUE TITLE
Violation setTimeout in html5qrcode.js

### ISSUE THREAD

**Issue by cfcoderatcodefactory** [mebjas/html5-qrcode#67]
When scanning with your library I get continuous console messages saying:
[Violation] 'setTimeout' handler took 73ms
This error is reported to occur on line 211 og html5qrcode.js.
NOTE: The scanning appears to work, though.

**Desktop (please complete the following information):**
 - OS: macOS latest
 - Browser: Chrome
 - Version: Latest

**Comment by mebjas** [comment]
Per https://stackoverflow.com/a/44824402/2614250,

> "Chrome violations" don't represent errors in either Chrome or your own web app. They are instead warnings to help you improve your app. In this case, Long running JavaScript and took 83ms of runtime are alerting you there's probably an opportunity to speed up your script.

I don't think this is more of an error but a warning. I expect it to sometime take this long as this part of code, reads a section of camera feed and try to decode QR code from it. It's expected to take a few milli seconds but fast enough to not have any user visible issues or jankiness. Thanks for pointing this out, this makes me wonder if there can be optimisations to the code.

**Comment by cfcoderatcodefactory** [comment]
OK. Thanks!
