### ISSUE TITLE
get id of a rendered camera

### ISSUE THREAD

**Issue by Hima-Pro** [mebjas/html5-qrcode#677]
Hello,
i am using html5QrCode class to build a section in my store to get the value of a product barcode by **html5-qrcode** lib using this class method :  
```
html5QrCode.start({ facingMode: "environment" }, config, qrCodeSuccessCallback);
```
then search for it in the database, so if i render a select element and the camera section only.

When i render the select element and append the <option> elements to the select element i set the value to the device id and the content to the device label but i can't set the selected one when i use the **environment** as the **facingMode** .

 So how to get the current camera id if we use that method.
Thanks 👍 !

**Comment by mebjas** [comment]
There is no good way that I know to get the camera id of a certain camera (user or environment).
