### ISSUE TITLE
Strange behavior on iOS running via ionic mobile app

### ISSUE THREAD

**Issue by ozamamurzleen** [mebjas/html5-qrcode#678]
**Describe the bug**
I am starting a scan and strange video popups up by the library.

<img width="420" alt="Screenshot 2023-01-20 at 1 47 28 AM" src="https://user-images.githubusercontent.com/62137583/213556462-4f6dc2d3-32a7-4c3a-b1a3-0eaeca425208.png">

Here's my code:

```
const html5QrcodeScanner = new Html5Qrcode('placardScanner');
html5QrcodeScanner.start({facingMode: "environment"}, { fps: 10, qrbox: { width: 350, height: 350 } }, onScanSuccess);
```

**Comment by ozamamurzleen** [comment]
@mebjas Please help. On ios it starts a black video. And then dont detect qr code kind of black screen. Please help its working fine in safari.

**Comment by ROBERT-MCDOWELL** [comment]
you should be much more precise if you need your issue to be debugged.
OS and version
Browser and version
device name and type
to say IOS does not work and safari works makes absolutely no sense unless you are using other browsers in IOS
which we need to study your case.

**Comment by ozamamurzleen** [comment]
iPadOS 16 running or iPad air 4 also on iPhone 13.

**Comment by ROBERT-MCDOWELL** [comment]
you still didn not specify which browser as you said it works on safari...

**Comment by ozamamurzleen** [comment]
@ROBERT-MCDOWELL This is only happening if i add above code in ionic app running on iOS. Same codebase is being used directly via website url. BUT when the code wraps in iOS .ipa file above thing happens.
I can also make a small video for you to see.

**Comment by ROBERT-MCDOWELL** [comment]
you should avoid all emulator at all as they never simulate hardware but only software.

**Comment by ozamamurzleen** [comment]
Not find anything. CLosing it.
