### ISSUE TITLE
Error getting userMedia, error = NotReadableError: Could not start video source

### ISSUE THREAD

**Issue by cfcoderatcodefactory** [mebjas/html5-qrcode#68]
I have created an application based on your qr code reader. It works very fine on iOS.

On Android I get the following error when I try to start scanning:

Error getting userMedia, error = NotReadableError: Could not start video source

**Comment by cfcoderatcodefactory** [comment]
Update: I have tried to use your demo (https://blog.minhazav.dev/research/html5-qrcode.html). 
On iOS it works fine when I select the «back» camera (environment).
On Android (Chrome) I get the same error as mentioned above when I select the back camera, while selecting the front («selfie») camera the strem starts.
A customer of mine, testing the app I am building, gets the same «NotReadableError» error message.

What baffles me is that this code worked just fine a few weeks back.

PLEASE HELP!!!

Chrome version: 83.0.4103.106
OS version: Android 10, moto g(8) Build: QPJS30.63-35-1-2

**Comment by mebjas** [comment]
If I understand correctly, the demo code is working on iOS (Safari I assume). While on Android on moto g8, it's not working for front camera on Chrome.

This is unusual, I tested the demo code and it seems to work seemlessly on Pixel3, I'll try to see if I can reproduce this issue on other android devices I have with me.

Meanwhile, this could very well be a Chrome bug, could you verify if this is happening with Firefox as well on the same android device? I'll try to dig more on this as well.

Thanks for posting.

**Comment by cfcoderatcodefactory** [comment]
Hi. I had – at some point – set framerate to 60, and Android (or at least the MotoG8) didn’t like that!

**Comment by leocharrua** [comment]
> Hi. I had – at some point – set framerate to 60, and Android (or at least the MotoG8) didn’t like that!

@cfcoderatcodefactory where did you set "framerate" to 60? I have the same issue sporadically.

Thanks

**Comment by ROBERT-MCDOWELL** [comment]
I'm sorry to say that set framerate to 60fps is absolute non sense for a scanner. for a game it's another story.
but please, go back to logic and even at 5fps a scanner is working very well.

**Comment by RedRush1** [comment]
I have this error as well. Only on android devices for some reason

**Comment by ROBERT-MCDOWELL** [comment]
@RedRush1 this error is in fact usually a input device permissions not allowed by the OS. so check if your browser can have access to the input devices with the authorization of your OS

**Comment by SanSoftInfoTech** [comment]
> > Hi. I had – at some point – set framerate to 60, and Android (or at least the MotoG8) didn’t like that!
> 
> @cfcoderatcodefactory where did you set "framerate" to 60? I have the same issue sporadically.
> 
> Thanks
here in javascript or javascript file fps 
var html5QrcodeScanner = new Html5QrcodeScanner(
"reader", {
    fps: 10, qrbox: 250
     , useBarCodeDetectorIfSupported: true,
    willReadFrequently: true,
    showZoomSliderIfSupported: true,
    defaultZoomValueIfSupported: 5,
    rememberLastUsedCamera: true,
    showTorchButtonIfSupported: true
});

**Comment by SanSoftInfoTech** [comment]
> Hi. I had – at some point – set framerate to 60, and Android (or at least the MotoG8) didn’t like that!

are u sure ? have you checked again by changing fps rate ? does it sotp working again  after changing fps rate ??

**Comment by ROBERT-MCDOWELL** [comment]
why the heck people set an QRcode scanner at 60fps? is it a bad gamer habit???
starting at 5fps is well enough for a mobile/desktop and you will avoid sucking battery, cpu, gpu etc....

**Comment by azzimuth** [comment]
> input device permissions not allowed by the OS. so check if your browser can have access to the input devices with the authorization of your OS
And if Chrome has access to camera? I have the same issue and I have even tried to remove the permission, and granted permission again but still getting this error...
