### ISSUE TITLE
How to allow spesific qr code, example only read qr code from database only.

### ISSUE THREAD

**Issue by Juraiz28** [mebjas/html5-qrcode#691]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ROBERT-MCDOWELL** [comment]
this is out of the project, must be coded on server side and receive the data in raw mode or already in jpg/pn/gif image and why not use the html5-qrcode scanner from FILE.

**Comment by mebjas** [comment]
1. Please add more context.
2. From the title, it looks like a business logic outside of scope of the library - please raise the question over stackoverflow or using the question template.
