### ISSUE TITLE
[Request] Where can I find demo's source code ?

### ISSUE THREAD

**Issue by apcloic** [mebjas/html5-qrcode#693]
Hi,

Thanks a lot for this really nice app.
I've build a basic custom UI based on the vuejs example but I would like to study demo code which looks better.
I mean the code used in https://scanapp.org/ or in https://qrcode.minhazav.dev/
Is it available somewhere ?
Regards,

**Comment by ROBERT-MCDOWELL** [comment]
check here for the name of the elements
https://github.com/mebjas/html5-qrcode/blob/master/src/ui/scanner/base.ts

**Comment by apcloic** [comment]
Thank you @ROBERT-MCDOWELL 
I've never seen theses kind of files *.ts, now I have to study how it works ;)
Regards

**Comment by ROBERT-MCDOWELL** [comment]
this file shows you the element ID, so just use the element you need to modify and code it in your css/javascript project file

**Comment by mebjas** [comment]
Demo code -https://github.com/mebjas/mebjas.github.io/blob/master/_layouts/research/html5qrcode/layout.html
