### ISSUE TITLE
[Feature Request] Please provide Angular example

### ISSUE THREAD

**Issue by DemeSteve** [mebjas/html5-qrcode#694]
**Is your feature request related to a problem? Please describe.**
I'm getting "Can't resolve all parameters for Html5QrcodeScanner" when trying use it in an Angular component.

**Describe the solution you'd like**
A working basic example of how to setup and use the Html5Qrcode in an Angular project.

**Comment by DemeSteve** [comment]
Sorry, no need. I made it work.

**Comment by mebjas** [comment]
Would you be interested in adding an example here -- https://github.com/mebjas/html5-qrcode/tree/master/examples

Happy to review and merge the PR.

**Comment by raydnersilva** [comment]
Hello everything is fine? I would like to know if I can upload my example in Angular
