### ISSUE TITLE
2.3.5 release min file malformed

### ISSUE THREAD

**Issue by RandomWhiteTrash** [mebjas/html5-qrcode#695]
**Describe the bug**
After the update min.js is cut short and doesn't work,

**To Reproduce**
Steps to reproduce the behaviour:
1. Load a new 2.3.5 version min.js file (from a CDN for example) and the library does not start

The file is only557bytes

**Comment by bensontrent** [comment]
Roll back to previous version to fix. See #696

**Comment by mebjas** [comment]
Fixed
