### ISSUE TITLE
video stream is zoomed on Android

### ISSUE THREAD

**Issue by cfcoderatcodefactory** [mebjas/html5-qrcode#73]
Hi.

When I start the video stream on iOS all is fine. When I do the same on Android (MotoG8) it appears that the camera is set to a pretty high zoom level.

Don’t understand why, and haven’t found anywhere in your code where zoom is set.

My (and your!) code is [here,](https://github.com/cfcoderatcodefactory/gangr) and the «interesting» files (created by me) are:
customFuncs.js
gangrCustomFuncs.js

**Comment by mebjas** [comment]
Can you share screenshot of zoom with this library and standard zoom with your camera app on same scene?

As a library it doesn't touch the zoom level so it's likely how the browser is handling the zoom in Android. Can you check this website to see if the zoom is supported in MotoG8 - https://googlechrome.github.io/samples/image-capture/update-camera-zoom.html

**Comment by cfcoderatcodefactory** [comment]
Hi - first, screenshot of zoom on Moto G8 with your library:
![Screenshot2](https://user-images.githubusercontent.com/6523291/86519484-7300c680-be3b-11ea-8b4a-cebaae8a5210.png)

Next: Picture taken with the Moto G8 camera, zoom x1:
![IMG_20200704_211320422](https://user-images.githubusercontent.com/6523291/86519494-9592df80-be3b-11ea-8e56-fb20c101c4e6.jpg)

They look similar when you preview them in this post, but IRL the screenshot taken from your lib (the first) is VERY much more zoomed than the one taken with the camera.

As for whether zoom is supported in Moto G8: I tested the URL you provided. I didn’t let me choose the back camera, but the selfie camera had support for zoom.

**Comment by cfcoderatcodefactory** [comment]
PS: BTW, is there any way to actually set the zoom level?

**Comment by mebjas** [comment]
> PS: BTW, is there any way to actually set the zoom level?

Not so far, I will explore this more and see if it's possible to be exposed by the library -  the control for zoom level.

**Comment by cfcoderatcodefactory** [comment]
If you want to check the difference in the zoom level in the app vs the actual camera app on your phone you can test my app here:
https://gangr.no

**Comment by mebjas** [comment]
@cfcoderatcodefactory I was able to reproduce this on https://gangr.no

I was working on something similar that might help (not sure) - https://github.com/mebjas/html5-qrcode/issues/82. Here I have added a support for aspect ratio as input and I was wondering if this would be fixed if you provide the screen's aspect ratio as input. Would you be able to try this out with [html5-qrcode.min.js](https://github.com/mebjas/html5-qrcode/blob/cf5e485713969f3391217d4f3c1d5d52f906d7b8/minified/html5-qrcode.min.js) (from a different branch currently in PR).

Use it with
```js
var desiredWidth = getDesiredWidth() // get this somehow based on your requirement;
var desiredHeight = getDesiredHeight() // get this somehow based on your requirement;

Html5Qrcode.getCameras().then(devices => {
    if (devices && devices.length) {
        scanner = new Html5Qrcode('ScanBox', false);
        scanner.start(devices[1].id, {
            fps: 10,
            qrbox: 250,
            aspectRatio: desiredWidth / desiredHeight
        }, success => {
            scanner.stop()
        })
    }
})
```

**Comment by mebjas** [comment]
That said please note that, the sensor's aspect ratio is usually `4:3`. But most of the cameras support aspect ratio like `16:9` which is mostly closer to the screen aspect ratio. In your case you need the viewfinder to be full screen and hence an aspect ratio closer to `16:9`.

To honour this the camera has to crop some region and the output won't be same as what you get from your default camera

![image](https://user-images.githubusercontent.com/3007365/87869956-87fe5d80-c9d6-11ea-9443-6863d07046b6.png)
This is how the crop is done for handling aspect ratio.

As a result it may look a bit zoomed w.r.t height.

**Comment by cfcoderatcodefactory** [comment]
Thanks, I’ll try to get around to testing this ASAP

**Comment by mebjas** [comment]
Any updates on this @cfcoderatcodefactory

**Comment by cfcoderatcodefactory** [comment]
Yes. Sorry, forgot all about it after I solved it by omitting all constraints, such as width, height, fps.

**Comment by mebjas** [comment]
I see, so this is no longer a problem?

**Comment by cfcoderatcodefactory** [comment]
Correct. Case closed.
