### ISSUE TITLE
facingMode not working

### ISSUE THREAD

**Issue by adam-a** [mebjas/html5-qrcode#761]
**Describe the bug**
Facing mode, even when set to "exact, environment" shows the front-facing camera

**To Reproduce**
Use camera

**Expected behavior**
Should throw if device has no back camera and show back camera otherwise

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macos
 - Browser chrome

**Smartphone (please complete the following information):**
 - Device: iphon e 14
 - OS: [ios 16.4
 - Browser safari

**Additional context**

```
      const openScanner = async () => {
        console.log(await Html5Qrcode.getCameras());
        await scanner?.current?.start(
          { facingMode: { exact: 'environment' } },
          {
            fps: 10,
            videoConstraints: { height: window.innerHeight + window.innerHeight * 0.5 },
            qrbox: { width: window.innerWidth / 1.5, height: window.innerHeight / 4 },
          },
          onScanSuccess,
          onScanFailure
        );
      };
      openScanner();
    }
```

**Comment by wombatstampede** [comment]
See this comment in html5-qrcode.ts:
`   /**
     * Optional, @beta(this config is not well supported yet).
     *
     * Important: When passed this will override other parameters like
     * 'cameraIdOrConfig' or configurations like 'aspectRatio'.
     * 'videoConstraints' should be of type {@link MediaTrackConstraints} as
     * defined in
     * https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackConstraints
     * and is used to specify a variety of video or camera controls like:
     * aspectRatio, facingMode, frameRate, etc.
     */
`
If you add videoConstraints then you have to add the facingMode to them as well.
https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackConstraints/facingMode
