### ISSUE TITLE
[Question] Are pause and resume methods deprecated, or is the documentation outdated?

### ISSUE THREAD

**Issue by jimokada** [mebjas/html5-qrcode#765]
**Describe the Question**
According to the API docs [https://scanapp.org/html5-qrcode-docs/docs/apis/classes/Html5Qrcode#pause](here),  using pause() and resume() methods in Html5Qrcode should pause or resume the ongoing scan. 

When I look at the actual methods available on Html5Qrcode, pause() and resume() doesn't exist. Is the documentation outdated, or is there something I am missing when initializing the API?

<img width="414" alt="Screenshot 2023-05-10 at 23 57 42" src="https://github.com/mebjas/html5-qrcode/assets/2733307/e4e803b4-ae9e-42e0-bb44-0a07df6b0b31">

**Comment by wombatstampede** [comment]
Look into: https://github.com/mebjas/html5-qrcode/blob/master/src/html5-qrcode.ts
And you'll see that both pause() and resum() are implemented and declared (TS) as public.

**Comment by jimokada** [comment]
@wombatstampede I realized that I was importing an outdated version of the minified script, your ref URL pointed me to a readme I've missed. Loaded the script from  https://unpkg.com/html5-qrcode and the issue was resolved. Thanks a lot!
