### ISSUE TITLE
Support devices that flip the image horizontally 

### ISSUE THREAD

**Issue by max2ti** [mebjas/html5-qrcode#77]
I have some devices that flip the image of the front camera horizontally, it's not configurable and it makes it impossible to read qr codes (they remain valid if rotated but can't be flipped).

I would like to be able to pass a flag in the constructor of html5-qrcode (or in the config param of the `start` function) to instruct it to flip the image before processing.
The flip itself is as easy as adding this two lines in the `setupUi` function (tested, working).

```javascript
...
            const canvasElement = this._createCanvasElement(
                qrRegion.width, qrRegion.height);
            const context = canvasElement.getContext('2d');
            context.canvas.width = qrRegion.width;
            context.canvas.height = qrRegion.height;

->          context.translate(context.canvas.width, 0);
->          context.scale(-1, 1);

            // Insert the canvas
            element.append(canvasElement);
            if (shouldShadingBeApplied) {
                this._possiblyInsertShadingElement(element, height, qrRegion);
            }
...
```

An even better solution would be to detect that the images are flipped automatically, but I don't know how feasible it would be.

**Comment by mebjas** [comment]
Thanks for the PR @max2ti - I was working on adding proper documentation and support where I realised there is still a problem that it would no longer be WYSIWYG as the video stream is not flipped only the hidden canvas that is scanned is flipped.

**Comment by max2ti** [comment]
You are right, it would not be WYSIWYG, but is it really important? For a user, centering the QRCode at a flipped (mirror-like) front camera is easier than doing the same at a "normal" camera, maybe separating what the user sees and what the library processes  would be better.

I'm not sure, anyway, a fix to keep the WYSIWYG might be something like:
```javascript
...
            const canvasElement = this._createCanvasElement(
                qrRegion.width, qrRegion.height);
            const context = canvasElement.getContext('2d');
            context.canvas.width = qrRegion.width;
            context.canvas.height = qrRegion.height;

            if (config.flipHorizontally) {
                context.translate(context.canvas.width, 0);
                context.scale(-1, 1);
->              $this._videoElement.style['-webkit-transform'] = "scaleX(-1)";
->              $this._videoElement.style['transform'] = "scaleX(-1)";
            }

            // Insert the canvas
            element.append(canvasElement);
            if (shouldShadingBeApplied) {
                this._possiblyInsertShadingElement(element, height, qrRegion);
            }
...
```
I'm not sure if this is the best way

**Comment by mebjas** [comment]
Hey @max2ti 

On further thinking I wonder how the consumers can generalise the use of this argument. I am assuming any solution build on top of this library cannot assume the input to be mirrored or otherwise.

A more general solution would be if the underlying scanner can handle a mirrored input. WDYT about that?

**Comment by max2ti** [comment]
@mebjas Hi, I've taken a look at how commercial libraries handle this, and yes they all handle mirrored images transparently, no manual settings, they just work.

The code is obfuscated so I don't know how they do it, the most naive way would be to process each frame twice (mirroring the second one), but that would lower overall performances. I'm sorry but I'm not really experienced in image manipulation and qr decoding in general (and also don't have much time) so don't count on me for anything more than the quick'n dirty "solution" in the pull request :(.

Ideally, a transparent solution would be the best (if performance suffers from it, maybe allow users who are sure they will not need it to disable it).

**Comment by mebjas** [comment]
That's ok @max2ti - thanks for the feedback, I'll take care of this.
