### ISSUE TITLE
Scanner camera freezing on android app (Capacitor Js wrapped app)

### ISSUE THREAD

**Issue by onesoftwareengineer** [mebjas/html5-qrcode#779]
**Describe the bug**
QR code scanner camera freezes after the first frame, on an android app.

**To Reproduce**
1. Wrapped a react app that uses html5-qrcode with ionic’s capacitor Js, then built apps for android and apple
2. The android app asks for permissions to use the camera, then the Qr code scanner starts and works flawlessly
3. After closing the app and restarting it, the Qr code scanner camera freezes after capturing the first frame
4. The camera stream starts working only if the screen is touched otherwise it stops

**Expected behavior**
Qr code scanner camera stream to work without freezing after the first frame

**Smartphone (please complete the following information):**
 - Device: Tested on several android devices, same behaviour
 - OS: Android no matter which version, tested on different android versions

**Additional context**
It's very weird that the qr code scanner works falwlessly the first time, then the freezing appears after the app is restarted. 
Perhaps there is a certain method that is called during the first use that helps it work the first time.

**Comment by old21** [comment]
Add a small animation on site(Add invisible block with infinite rotate animation) and bug will be fixed

**Comment by mark-hipecommerce** [comment]
I can confirm that the above-suggested workaround works. We had the exact same issue, and following the above advice, we added a 1-pixel rotating gif - and we now no longer have an issue with the camera preview freezing.

**Comment by onesoftwareengineer** [comment]
@old21 many thanks for helping out! :) Your recommendation didn't fix just the freezing problem with the qr library but also for the camera usage in general. Perhaps it's an ionic capacitor wrapping issue, since the app was working properly as a PWA.
