### ISSUE TITLE
is possible to change default camera

### ISSUE THREAD

**Issue by bagusandrewijaya** [mebjas/html5-qrcode#818]
can i chang the default camera use front or rear camera

**Comment by Snurppa** [comment]
@bagusandrewijaya  The second parameter to `start` method of `HTML5Qrcode` is `configuration: Html5QrcodeCameraScanConfig`.
If you pass for example `{videoConstraints: {facingMode: <mode>}}` where `<mode>` is `{ exact: "environment" }` for rear camera and `{exact: "user"}` for the front-facing camera, you should be able to decide which camera should open on start.

And if not already known, you can most likely (can't verify this now, so a guess) change the camera by applying new  `MediaTrackConstraints`: `.applyVideoConstraints({advanced: [{facingMode: {exact: <opposite-value>}}]})`

See [MediaTrackConstraints#facingMode](https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackConstraints/facingMode) from MDN and [Html5Qrcode#applyvideoconstraints](https://scanapp.org/html5-qrcode-docs/docs/apis/classes/Html5Qrcode#applyvideoconstraints) for more information.

**Comment by sunggyupaik** [comment]
[Default to Back Camera (if available) when using the Html5QrcodeScanner instead of Html5Qrcode](https://github.com/mebjas/html5-qrcode/issues/139)

it's possible in ``Html5Qrcode``, but not in ``Html5QrcodeScanner``
