### ISSUE TITLE
[Feature Request] Fullscreen support

### ISSUE THREAD

**Issue by SebScoFr** [mebjas/html5-qrcode#82]
THIS IS NOT A BUG

I'm just trying to get some feedback on how best to render the video feed in full screen on a smartphone.

I'm triggering the scanner programmatically like this (trimmed for the sake of this example):
```html
<div id="ScanBox"></div>
```
```javascript
Html5Qrcode.getCameras().then(devices => {
    if (devices && devices.length) {
        scanner = new Html5Qrcode('ScanBox', false);
        scanner.start(devices[1].id, {
            fps: 10,
            qrbox: 250
        }, success => {
            scanner.stop()
        })
    }
})
```

And this is what I see on my phone:

![qrcode](https://user-images.githubusercontent.com/22073633/87435633-e943bc80-c5e3-11ea-93a4-0c7791999ea4.jpg)

The phone camera is capable of displaying the feed on full screen as seen when using the camera app for instance, so I am wondering if there is a way to do the same with this library? (BTW, I'm not asking to remove the browser toolbars, simply to cover the entire viewport inside the browser)

Cheers 👍

**Comment by mebjas** [comment]
Thanks for raising this question. I think this is possible - the API supports a constraint for aspect ratio (https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackConstraints/aspectRatio). In most of devices the default camera sensor aspect ratio is `4:3`. That is what you are seeing in the screenshot you have attached. But most of the camera drivers (also known as Camera HAL) also supports cropping the input to `16:9` aspect ratio which is what most of the full resolutions would be like.

So from the library side it might be feasible to extend support of this configuration where you can pass `aspectRatio: constraint` and library can try to delegate this.

Let me get back to you on how it'd look like

**Comment by mebjas** [comment]
Screenshot based on experimental code on Pixel 3, Google Chrome, Android 10

| without constraints | With 16:9 constraints |
| ----- | ----- |
|![image](https://user-images.githubusercontent.com/3007365/87868647-b24a1e00-c9ca-11ea-9cb4-ed618c3c021b.png) |![image](https://user-images.githubusercontent.com/3007365/87869259-c6911980-c9d0-11ea-859b-b10c19033e24.png) |

**Comment by mebjas** [comment]
Once the library supports this, the consumer (you) can handle the full screen logic. What do you think?

**Comment by mebjas** [comment]
@SebScoFr I have raise a pull request for this.

Can you try this out if you can meet your requirements with this - [link to html5-qrcode.min.js](https://github.com/mebjas/html5-qrcode/blob/cf5e485713969f3391217d4f3c1d5d52f906d7b8/minified/html5-qrcode.min.js). 

Way to use this would be 
```js
Html5Qrcode.getCameras().then(devices => {
    if (devices && devices.length) {
        scanner = new Html5Qrcode('ScanBox', false);
        scanner.start(devices[1].id, {
            fps: 10,
            qrbox: 250,
            aspectRatio: 1.7777778
        }, success => {
            scanner.stop()
        })
    }
})
```

**Comment by SebScoFr** [comment]
Many thanks @mebjas for adding this feature.

It doesn't work for me when I pass the **aspectRatio** parameter on the **start** method like so. Though it works perfectly when I hardcode 1.7777778 directly in the js library file. (AKA replacing 1.33334 by 1.7777778)

**Comment by mebjas** [comment]
Did you try it with this library code - [html5-qrcode.min.js](https://github.com/mebjas/html5-qrcode/blob/cf5e485713969f3391217d4f3c1d5d52f906d7b8/minified/html5-qrcode.min.js) please note that this is not yet merged to master

**Comment by SebScoFr** [comment]
Yes I just tried again with this code. But like I said it works perfectly fine if I hardcode the value in the library. It's as if the aspectRatio param is not getting taken into account somehow.

**Comment by mebjas** [comment]
The PR had some hardcoded values - fixed those and merged to code - now the library supports aspect ratio as an argument.

Thanks for raising this feature request with concrete use-case!!

**Comment by dovdovrandom** [comment]
This is great!

Any plan to implement auto fullscreen? Passing in a 'fullscreen' parameter that covers the entire screen, regardless of device, and centers the scan area?

**Comment by luoluo5945** [comment]
获取浏览器视图窗口的宽高，aspectRatio设置宽度除以高度的纵横比： `aspectRatio: innerWidth / innerHeight`

Gets the width and height of the browser view window. aspectRatio sets the aspect ratio of the width divided by the height: `aspectRatio: innerWidth / innerHeight`
