### ISSUE TITLE
[Question] Toggling Torch in Html5Qrcode

### ISSUE THREAD

**Issue by c0uncer** [mebjas/html5-qrcode#848]
**Describe the Question**

How can I toggle torch on or off with 'Html5Qrcode'? There is an option called 'showTorchButtonIfSupported: true' in 'Html5QrcodeScanner' but I couldn't find a way to implement a torch button of my own into 'Html5Qrcode'. In a blog written in 30 Oct 2022(https://scanapp.org/blog/2022/10/30/using-flash-or-torch-with-html5-qrcode.html), it is said that torch can be enabled by using  applyVideoConstraints() API, but when I try it, I get the ` ''torch'' does not exist in type 'MediaTrackConstraints'. ` error.

```js

html5QrCode.applyVideoConstraints(
      {
        "torch": true,
        "advanced": [{ "torch": true }]
      }
    )

```

**Comment by ROBERT-MCDOWELL** [comment]
ALL HARDWARE  RELATED QUESTION IS LINKED TO YOUR CAMERA CAPABILITIES AND OS PERMISSIONS.
This said, in JS even if you activate the torch and your camera has no torch function or your browser/app has NO PERMISSIONS to access to the torch function so it won't work.

**Comment by nicolidin** [comment]
I have the same issue: in the doc it's specified:
This is only supported for Html5QrcodeScanner.

So not `html5QrCode`

**Comment by alingeopress** [comment]
same issue here, I have tried using Html5QrcodeScanner instead of html5QrCode but it's the same issue unfortunately

**Comment by maxwrlr** [comment]
`Html5QrcodeScanner` uses `getRunningTrackCameraCapabilities()` like so:
```ts
// Init scanner.
const scanner = new Html5Qrcode(...);
await scanner.start(...)

// ...

// Toggle flashlight.
const torch = scanner.getRunningTrackCameraCapabilities().torchFeature();
torch.apply(!torch.value());

**Comment by ollischlueter** [comment]
> `Html5QrcodeScanner` uses `getRunningTrackCameraCapabilities()` like so:
> 
> ```ts
> // Init scanner.
> const scanner = new Html5Qrcode(...);
> await scanner.start(...)
> 
> // ...
> 
> // Toggle flashlight.
> const torch = scanner.getRunningTrackCameraCapabilities().torchFeature();
> torch.apply(!torch.value());
> ```

Thank you so much! This works like a charm!
