### ISSUE TITLE
Initialize the camera from the beginning instead of displaying the 'Request Camera Permissions' button

### ISSUE THREAD

**Issue by hoaipd** [mebjas/html5-qrcode#871]
I want to enter the page for the first time and display a camera access request instead of having to click the 'Request Camera Permissions' button to ask for camera access. I don't know if the library supports this or not.
Thank you

**Comment by hoaipd** [comment]
Does it resolve to the page that displays the website's camera access request, and after clicking accept button, does it display the camera? i use reactjs. Thank you

**Comment by sododesign** [comment]
@hoaipd 

I don't use REACT, this is pure VANILLA JS. 

You should adapt it to your needs, but it does exactly what you asked for your project.

**Comment by hoaipd** [comment]
> @hoaipd
> 
> I don't use REACT, this is pure VANILLA JS.
> 
> You should adapt it to your needs, but it does exactly what you asked for your project.

I did it. Thank you for your support

**Comment by hoaipd** [comment]
@sododesign 
`const html5QrCode = new Html5Qrcode(
  "reader", { formatsToSupport: [ Html5QrcodeSupportedFormats.QR_CODE ] });
const qrCodeSuccessCallback = (decodedText, decodedResult) => {
    /* handle success */
};
const config = { fps: 10, qrbox: { width: 250, height: 250 } };

// If you want to prefer front camera
html5QrCode.start({ facingMode: "user" }, config, qrCodeSuccessCallback);`
