### ISSUE TITLE
HOW STOP AFTER SCANNED ITEM

### ISSUE THREAD

**Issue by fgirolami29** [mebjas/html5-qrcode#88]
hi how can i stop the scan after the first scan?

**Comment by mebjas** [comment]
Have a look at this https://github.com/mebjas/html5-qrcode/issues/72

A bug was recently fixed in v1.1.8 - please use that with the steps in linked issue.

**Comment by mebjas** [comment]
Please reopen if this issue is still observed in latest code.

**Comment by fgirolami29** [comment]
checking.... now ... can u interested about beep after scan?? other issue is the shadow box that it use px unit for render scan area, better use %

**Comment by fgirolami29** [comment]
> Please reopen if this issue is still observed in latest code.

checked no error
