### ISSUE TITLE
double camera

### ISSUE THREAD

**Issue by septianmalela** [mebjas/html5-qrcode#880]
Double camera when first load the page, but when me click 'stop scanning' and click again 'start scanning' show 1 camera. And found error JS
'NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.'

i'm using cdn
https://cdnjs.cloudflare.com/ajax/libs/html5-qrcode/2.3.8/html5-qrcode.min.js

![WhatsApp Image 2024-01-09 at 11 42 12](https://github.com/mebjas/html5-qrcode/assets/46917044/aa2b168d-3734-4343-ada2-a4cc6dd1a389)

` const scanner = new Html5QrcodeScanner('barcode-scanner', {
      fps: 10,
      qrbox: { width: 250, height: 250 },
      disableFlip: false,
      videoConstraints: {
        facingMode: 'environment',
        width: 9999,
      },
      // showTorchButtonIfSupported: true,
      upload: false
    })
`

Thanks in advanced.

**Comment by septianmalela** [comment]
Solved, Thanks.

**Comment by edwardsurjadi** [comment]
Hi @septianmalela is this fixed? what was the resolution?
