### ISSUE TITLE
[Feature Request] Barcode Scan

### ISSUE THREAD

**Issue by proautodinc** [mebjas/html5-qrcode#89]
Just installed your library and it's working great, It would be great to also have industrial Barcode scanning, in my case for vehicles VIN numbers. 

Thank you.

**Comment by mebjas** [comment]
Thanks for the feature request, I already have a duplicate issue for this - https://github.com/mebjas/html5-qrcode/issues/61

Please subscribe to that issue for updates. I'll try to work on it and add support for bar code as well.
