### ISSUE TITLE
Turn off file upload

### ISSUE THREAD

**Issue by eplatforms-uk** [mebjas/html5-qrcode#896]
How can we switch off the scan an image file? 

Also is it possible to change the graphic above Request Camera Permission and remove the (i) icon that appears top right ?

**Comment by ROBERT-MCDOWELL** [comment]
1) read the docs
2) no or go into the code and remove it yourself but the author won't be happy

**Comment by eplatforms-uk** [comment]
1. Thanks for your reply, have read the docs can't seem to see where though :-)
2. :-) Happy to seek out a commercial licence even. Just looking to customise the UI better that's all.

**Comment by ROBERT-MCDOWELL** [comment]
you can ask the main author directly (mejbas).

**Comment by ROBERT-MCDOWELL** [comment]
when you create a scanner object, in the config:
			exchange_scannerConfig = {fps: 8,
									  qrbox: {width: 250, height: 250},
									  rememberLastUsedCamera: true,
									  disableFlip: true,
									  ...
									  formatsToSupport: [Html5QrcodeSupportedFormats.QR_CODE];,
									  ...
									  useBarCodeDetectorIfSupported: true,
									  showZoomSliderIfSupported: true,
									  defaultZoomValueIfSupported: 2};
			exchange_scanner = new Html5QrcodeScanner("exchange-scanner",exchange_scannerConfig);

so the to put only [Html5QrcodeSupportedFormats.QR_CODE] remove the FILE scanner.

**Comment by eplatforms-uk** [comment]
many thanks Robert

**Comment by eplatforms-uk** [comment]
Many thanks Robert
